### ISSUE TITLE
missing images/license.txt and assets/

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gravity-and-orbits#1]

**Comment by samreid** [comment]
We are still missing several AI files here.

**Comment by samreid** [comment]
I added an AI file from piccolo-phet for the measuring tape in https://github.com/phetsims/gravity-and-orbits/commit/1d1e79666cd636073a40d093ca1f555c0385b5ad

**Comment by aaronsamuel137** [comment]
At some point measuring tape migrated to scenery-phet, so it is not needed here anymore. I have updated the image path to use the scenery-phet measuring tape and gotten rid of the png and ai file.

**Comment by aaronsamuel137** [comment]
There was an ai file for the reset all button, which doesn't belong here. I removed it.

**Comment by aaronsamuel137** [comment]
We don't have ai files for:

- earth.gif
- moon.png
- space-station.png
- reset_arrow.png
- icon_path.png

Perhaps some of these never existed?

**Comment by pixelzoom** [comment]
Here's license.txt from the Java version:

```
earth_satellite.gif source=NASA notes=see http://www.harmsy.freeuk.com/images/earth2.jpeg, http://cac-science8.wikispaces.com/ nasa copyright rules here http://www.nasa.gov/audience/formedia/features/MP_Photo_Guidelines.html
moon.png source=public domain notes=http://astro.unl.edu/misc/moonpics/moon08_th.jpg public domain license at http://astro.unl.edu/misc/moonpics
space-station.png source=nasa notes=http://www.nasa.gov/images/content/323090main_s119e009793_hires.jpg linked from http://www.nasa.gov/mission_pages/station/multimedia/iss_sts119_images.html
sun.png source=NASA notes=http://www.eos.unh.edu/images/newsl_0309/sun_lg.jpgcma
```

**Comment by aaronsamuel137** [comment]
We discussed in the last design meeting getting assets for the following:

- Reset arrow
- path icon (with gray dot)
- Satellite (Mariah)

We also mentioned that we want to make quick 3D sphere in Illustrator for Sun and non-Earth Planet (something like 600x600px).

Assigning to @ariel-phet for prioritization.

**Comment by ariel-phet** [comment]
@arouinfar can you make the two design assets that you are going to create a high priority? Can you also make an artwork task for Mariah describing what you would want (maybe include a screenshot for clarity of the current satellite). Please assign the artwork task to me first.

**Comment by samreid** [comment]
@aaronsamuel137 would it make sense to use SCENERY_PHET/ShadedSphereNode here?

**Comment by aaronsamuel137** [comment]
The reason we moved away from this was because of the performance losses of using RadialGradients, so I think it is better to keep them as images.

**Comment by samreid** [comment]
> The reason we moved away from this was because of the performance losses of using RadialGradients, so I think it is better to keep them as images.

Create radial gradient, then convert toImage() using scenery?

Tradeoffs with this approach:
1. Smaller download size (no need to ship multiple 600x600px rasters with the download), hence download will be faster
2. Easier & more maintainable to make changes to the exact size/color of the objects (changing a number in the code vs generating new images). 
3. Slightly more complex code (have to call toImage with a callback).
4. Slightly longer startup time as the raster is created during sim startup

**Comment by aaronsamuel137** [comment]
Decided to go with the toImage approach in the above commit and 3b5774b1d51a572da616cebba606bed1b58000d6.

Therefore we don't need the 3D spheres anymore @arouinfar.

**Comment by arouinfar** [comment]
Sounds good @aaronsamuel137. I will be sending you the other assets later today.

@ariel-phet I will create the artwork task this afternoon and assign it to you for prioritization.

**Comment by arouinfar** [comment]
Assets have been emailed to @aaronsamuel137.

**Comment by aaronsamuel137** [comment]
I've added these new assets to the sim. However, depending on whether or not we need to change the colors of these icons in projector mode, we may need to draw them in code instead. I'll wait until the project mode color scheme is done to do anything here.

I think all that is left for this issue is the artwork from Mariah.

**Comment by aaronsamuel137** [comment]
@arouinfar, there are a few issues I am running into using toImage around code complication, performance, and image resolution,  so I think it would be better to get the generic spheres made in illustrator after all.

We will need three colors - yellow for sun, gray for the generic planet, and pink for the generic moon. I would not be adverse to changing the pink to something else, it looks odd to me, but that is how it was in the Java.

Assigning to @arouinfar.

**Comment by samreid** [comment]
> a few issues I am running into using toImage around code complication, performance, and image resolution

My apologies for starting a wild goose chase--it would be good for me to better understand the issues with toImage code complication, performance and image resolution, in case it comes up again in the future.

**Comment by arouinfar** [comment]
@aaronsamuel137, the path icon colors will need to change in projector mode. I can send you a second asset, if you need it.  I'll also start working on the spheres and send them to you shortly.

**Comment by samreid** [comment]
@aaronsamuel137 and I discussed the issues with toImage and there were a few things we didn't understand, such as (potentially?) getting unexpected padding whithin a toImage render.  @aaronsamuel137 was considering discussing it with @jonathanolson.  We also discussed generating a sphere image in code while the simulation is being started, and using ImageRenderer within the sim.  But we both agreed using images for now would also be acceptable, and we could revisit this issue in the future if/when we need to reduce download size.

**Comment by arouinfar** [comment]
@aaronsamuel137, I've emailed you the requested spheres along with a projector-mode version of the path icon. Please let me know if there is anything else you need.

**Comment by aaronsamuel137** [comment]
That's great for now, just waiting on the new satellite now.

**Comment by aaronsamuel137** [comment]
I think we are waiting on a new satellite image, but that is not really the purpose of this issue. When the new satellite image is added, @jessegreenberg can check in the image and the assest and add it to license.json.

Closing

**Comment by arouinfar** [comment]
Just realized I hadn't created an artwork task for the satellite! The issue has now been created. https://github.com/phetsims/tasks/issues/436
