### ISSUE TITLE
Poor rendering of zoom slider in Windows 7 32 bit Chrome in iFrame

### ISSUE THREAD

**Issue by bryo5363** [phetsims/gravity-and-orbits#116]
![grav and orbits](https://cloud.githubusercontent.com/assets/7717368/3802551/5b915aec-1c10-11e4-8105-c2775f7cce12.png)

As you can see, the slider looks different than in other browsers. Only happens in iFrame

Chrome 36.0.1985.125

**Comment by aaronsamuel137** [comment]
Assigning to @jessegreenberg since he is taking over this sim and has a windows machine. It may be that this can just be closed, since this issue was created before the rewrite happened.

**Comment by ariel-phet** [comment]
No longer an issue on http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.0.0-dev.24/gravity-and-orbits_en-iframe.html

Closing
