### ISSUE TITLE
Poor rendering of icons on iPad iFrame mode

### ISSUE THREAD

**Issue by bryo5363** [phetsims/gravity-and-orbits#117]
![image](https://cloud.githubusercontent.com/assets/7717368/3813658/12ff2552-1cb5-11e4-92a5-70d0120561bb.jpg)

Pretty clear in the picture above.

iPad 7.1 running Safari 7

**Comment by aaronsamuel137** [comment]
If this is still an issue, we could presumably solve it with mipmap images.

**Comment by aaronsamuel137** [comment]
Used mipmap for icon images and verified better looking icons on Safari iFrame. Also changed earth.gif to be a png for consistency and so mipmap would work.

Closing
