### ISSUE TITLE
Performance on iPad is decreased when accessing path and vectors.

### ISSUE THREAD

**Issue by bryo5363** [phetsims/gravity-and-orbits#118]
The simulation runs slower when most of the buttons are accessed. The most noticeable performance issue is running the sun moon and earth mode with the path accessed as well as the vectors.

**Comment by aaronsamuel137** [comment]
In rewrite, the path and vectors don't seem to be the biggest performance issues, so I'll close this here and let testers open new performance issues if they arise.
