### ISSUE TITLE
Sharp turns cause rough and choppy path tracings

### ISSUE THREAD

**Issue by bryo5363** [phetsims/gravity-and-orbits#122]
Creating an extremely elliptical orbit causes the rendering of the paths to be choppy. Below is an example of a very sharp orbit with choppy rendering.

![screenshot 2014-08-12 13 42 41](https://cloud.githubusercontent.com/assets/7717368/3896596/c1147f1c-2259-11e4-9c8f-2a6b1fb4f284.png)

Tested on Chrome 36.0.1985.143 on OSX 10.7.5

**Comment by aaronsamuel137** [comment]
Not an issue in rewrite. Closing
