### ISSUE TITLE
Earth Moon and Sun runs slow in Firefox

### ISSUE THREAD

**Issue by bryo5363** [phetsims/gravity-and-orbits#123]
Steps to reproduce
-Open any sim mode
-click on earth moon and sun
-click path. press play
-let the earth and moon make one revolution around the sun
-the objects will revolve slower. even clicking fast forward will not really improve speed.

**Comment by aaronsamuel137** [comment]
Pre-rewrite issue, so very likely doesn't apply anymore. Closing
