### ISSUE TITLE
Dragging a planet with path on creates a strange path

### ISSUE THREAD

**Issue by bryo5363** [phetsims/gravity-and-orbits#124]
Steps to reproduce
-Open sim, either cartoon or to scale will work
-Use any mode. For the screenshot I used earth moon and sun because the celestial objects are easier to grab.
-Turn on path
-While objects are in motion, drag a planet (or moon) to some location on the screen.
-A strange path will be produced. 

![screen shot 2014-08-15 at 9 59 42 am](https://cloud.githubusercontent.com/assets/7717368/3935450/93cd6094-2495-11e4-8bec-5cfed949e1fd.png)

**Comment by aaronsamuel137** [comment]
Pre-rewrite issue, so very likely doesn't apply anymore. Closing
