### ISSUE TITLE
Measuring tape inconsistent/ incorrect scale.

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/gravity-and-orbits#126]
Tested 1.0.0-dev.19
This is a HTML 5 and Java inconsistency issue https://github.com/phetsims/gravity-and-orbits/issues/20

Checking between the "to scale scenes" between Java and the HTML 5, and the scale of the measuring tape to the grid shows discrepancy between the two.

On both scenes the major objects of interest are each on their own point on the grid (distance of 2 blocks), but the measuring tape falls at a different distance between the two (proportionally) and say the same value

JAVA (sun earth moon) Actual distance apart via Wikipedia 92,960,000 miles  
![java](https://cloud.githubusercontent.com/assets/5631059/3955746/71188eb8-2704-11e4-9425-21a0addaaf3e.PNG)

1.0.0-dev.19 (sun earth moon)  
![html](https://cloud.githubusercontent.com/assets/5631059/3955753/77927038-2704-11e4-9d78-6069a572b438.PNG)

JAVA (earth moon) Actual distance apart via Wikipedia  238,900 miles 
![java2](https://cloud.githubusercontent.com/assets/5631059/3955759/828de8e6-2704-11e4-8117-d541795a01fa.PNG)

1.0.0-dev.19 (earth moon)
![html2](https://cloud.githubusercontent.com/assets/5631059/3955760/888561ca-2704-11e4-92e3-8f8e906ac7f2.PNG)

**Comment by aaronsamuel137** [comment]
Fixed in rewrite, closing
