### ISSUE TITLE
Functionality of the 'rewind' button?

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/gravity-and-orbits#127]
In the HTML 5 1.0.0-dev.19 the rewind button has different possible responses. 
Related to issue https://github.com/phetsims/gravity-and-orbits/issues/20

Case 1:
'rewind' button returns orbit to original starting positions. 
This always occurs on the Java Version.

Case 2:
'rewind' button returns orbit to the point in time the 'pause' button was hit last.
This does not occur on the Java Version.
To Reproduce:
-Open sim
-Press 'Play'
-Wait until the object is on at a different point in its orbit. Press 'Pause'
-Press 'Play'
-Wait some time then hit 'rewind'
-The object will spawn in the location the 'Pause' button was hit last.

Case 3:
After changing between orbitals the 'rewind' button returns the orbit to the position prior to the change between the orbitals.
This does not occur on the Java Version.
To Reproduce:
-Open sim
-Press 'Play'
-Wait until the object is on at a different point in its orbit. (A few seconds) 
-Switch to another orbital
-Switch to back to the previous orbital
-Hit 'Rewind'
-The object will spawn in the location prior to changing between orbitals.

**Comment by aaronsamuel137** [comment]
Rewind functionality matches the Java in the rewrite. Closing.
