### ISSUE TITLE
Earth's small orbit in the Earth and Moon view is choppy

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/gravity-and-orbits#129]
Tested 1.0.0-dev.19
Earth's small orbit around the center of mass is very choppy in the earth and moon orbit. Seems like it is being displaced by a few pixels at a time. Does not look nearly as smooth as the subtle circular path on the java version.

**Comment by aaronsamuel137** [comment]
Pre-rewrite issue, so very likely doesn't apply anymore. Closing
