### ISSUE TITLE
Poor rendering of sim

### ISSUE THREAD

**Issue by bryo5363** [phetsims/gravity-and-orbits#130]
tested on dev.19. Upon opening the sim I noticed poor rendering of all of the icons.
![screen shot 2014-08-19 at 8 20 14 am](https://cloud.githubusercontent.com/assets/7717368/3967553/63e20d6e-27ae-11e4-940a-3935cfc09e41.png)

**Comment by aaronsamuel137** [comment]
Screen icons look a little better when mipmaped too. The only things that aren't mipmapped now are the path and mass icons. Not sure if they need to be.

**Comment by aaronsamuel137** [comment]
This was a pre-rewrite issue, so I am going to close. If testers notice any rendering issues that can reopen or create a new issue.
