### ISSUE TITLE
Simulation will remain zoomed out after pressing refresh. 

### ISSUE THREAD

**Issue by bryo5363** [phetsims/gravity-and-orbits#131]
This is quite a strange issue because I initially noticed it on IE9 but not when I tested on Chrome 36.0.1985.143. 

Essentially the simulation will remain zoomed out after pressing the smaller refresh button next to the orbital mode.

Steps to reproduce
-open sim
-slide the zoom slider to the minimum position
-press the refresh button next to the orbital mode
-the sim will remain zoomed out. even switching to different orbital modes will cause the sim to remain zoomed out.

**Comment by aaronsamuel137** [comment]
The behavior here currently matches the Java. Closing
