### ISSUE TITLE
Sometimes it is easy to shoot planet out of orbit

### ISSUE THREAD

**Issue by bryo5363** [phetsims/gravity-and-orbits#132]
I noticed this behavior on the Java version as well, which is why I am labeling this as a question. Basically moving an object that another celestial body is orbiting can cause the orbiting body to be shot out of orbit. I assume this is replication of escape velocity but occasionally this behavior is quite dramatic. I will make a screencast of this behavior.

https://drive.google.com/file/d/0B7WUaZM7uvVKWUYzdXhxd1BMMGM/edit?usp=sharing

My attempts at this are less than excellent but the issue occurs twice during the screencast.

Steps to reproduce
-open sim
-click on to scale tab, it is easier for this issue to occur when the celestial objects are smaller
-play simulation
-while the orbiting body is in motion, drag the heavier body very close to the orbiting one
-occasionally the orbiting body will shoot out of orbit without even revolving around the center of mass.

**Comment by ariel-phet** [comment]
I can reproduce, but this seems inevitable. When you bring the bodies close quickly you cause a large acceleration that can give the orbiting body enough velocity to escape. 

Matches the Java version, so no need to address. Closing
