### ISSUE TITLE
Inconsistent behavior with modified orbits. 

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/gravity-and-orbits#133]
Tested 1.0.0-rc.14

Strange bug where if you bring two objects close together and keep using the 'rewind' button the behavior afterwards is inconsistent. ie. the sun very close to earth in the 'To Scale' screen produces different orbital trajectories after each time 'rewind' has been hit.

To Reproduce:
-Open Sim 
-Select "To Scale"
-Bring the sun very close to earth
![1](https://cloud.githubusercontent.com/assets/5631059/3969637/9f38c7e0-27c2-11e4-901f-a50bda54c427.PNG)
-Hit Play and observe the trajectory
-Notice You may get different orbital trajectories
1)
![2](https://cloud.githubusercontent.com/assets/5631059/3969666/e519329a-27c2-11e4-926d-50121f4be50c.PNG)
2)
![3](https://cloud.githubusercontent.com/assets/5631059/3969856/eb6166d4-27c4-11e4-98d9-dc656d37a7ae.PNG)

**Comment by aaronsamuel137** [comment]
Not an issue in the rewrite, closing
