### ISSUE TITLE
Names of objects remain in the location of their destruction after hitting rewind. 

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/gravity-and-orbits#134]
Tested 1.0.0-dev.19 
May be related to issue https://github.com/phetsims/gravity-and-orbits/issues/111

Names of objects remain in the location of their destruction after hitting rewind. For this to occur the sim must be playing during the collision then paused afterwards.

To Reproduce:
-Open sim to "To Scale" scene
-Hit Play
-Destroy one or more of the objects by dragging them to the center object.
-Hit Pause
-Hit Rewind 

(Star and Planet)
![1](https://cloud.githubusercontent.com/assets/5631059/3970145/810e1ef0-27c7-11e4-8b81-639ce4276362.PNG)

(Earth and Satellite)
![2](https://cloud.githubusercontent.com/assets/5631059/3970146/85114fa4-27c7-11e4-9a59-876d926af21a.PNG)

**Comment by aaronsamuel137** [comment]
Pre-rewrite issue, so very likely doesn't apply anymore. Closing
