### ISSUE TITLE
Investigate WebGL

### ISSUE THREAD

**Issue by samreid** [phetsims/gravity-and-orbits#137]
I marked a number of issues that may be resolved when using WebGL for rendering.  We should probably work in a branch until we determine whether WebGL is a viable strategy at this time, for this sim.

**Comment by samreid** [comment]
@KatieWoe can you please test performance on some of PhET's slower supported devices?  Here's a fresh dev version: https://phet-dev.colorado.edu/html/gravity-and-orbits/1.2.0-dev.2/phet/gravity-and-orbits_en_phet.html

**Comment by KatieWoe** [comment]
Things look pretty ok.

**Comment by samreid** [comment]
Thanks, it seems we will not need to invest in WebGL for this sim at the moment, closing.
