### ISSUE TITLE
Investigate a rewrite

### ISSUE THREAD

**Issue by samreid** [phetsims/gravity-and-orbits#138]
@aaronsamuel137 and @samreid have noted numerous pervasive issues in the code that make it very difficult to navigate/read/refactor/debug/enhance/optimize/etc, and we would like to investigate a clean rewrite in a branch "rewrite".  We'll just spend a little time on it now to get an estimate of how long it would take to do the entire sim from scratch.  Also, note this Java sim is 4496 total lines of code (including comments, if any!).

**Comment by samreid** [comment]
I think @aaronsamuel137 is going to be the lead on this, when time allows (correct me if I'm wrong).

**Comment by aaronsamuel137** [comment]
I've been working on this. At this point, the rewrite branch has been merged into master and most files are ported.

**Comment by aaronsamuel137** [comment]
Rewrite is (mostly) done. Closing
