### ISSUE TITLE
Properties should have `Property` suffix

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gravity-and-orbits#140]
Examples of anti pattern:

RewindableProperty: this.different = new Property( !this.equalsRewindPoint() );
GravityAndOrbitsMode: this.zoomLevel = new Property( 1.0 );
GravityAndOrbitsMode: this.active = new Property( active );

**Comment by pixelzoom** [comment]
I believe that @aaronsamuel137 is now responsible for this repo, and that there may be some rewriting involved. So assigning to him to handle this.

**Comment by aaronsamuel137** [comment]
This has been addressed incrementally as the port progressed, so not every commit is here. Searching for "new Property" reveals that there are no longer cases of the anti pattern.

Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
I'll take your word for it :)

Closing.
