### ISSUE TITLE
invalid aspect ratio for screen icons in navbar

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gravity-and-orbits#148]
Screen icons for the navbar must have the same aspect ratio as either Screen.NAVBAR_ICON_SIZE or Screen.HOME_SCREEN_ICON_SIZE. See phetsims/joist#263 (comment). This sim does not, and fails when assertions are enabled.

**Comment by aaronsamuel137** [comment]
Fixed. Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
Visually inspected commit, looks good. I'll assume you tested with ?ea. Closing.
