### ISSUE TITLE
branch: exponentialDecompositionAlgorithm

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gravity-and-orbits#150]
Please describe this branch, what it's purpose is, when it is anticipated that it will be delete or merge into master.

**Comment by aaronsamuel137** [comment]
This a branch created by @phetsims/bereaphysics that uses a potentially more efficient algorithm for the model steps.

I anticipate it will be merged in to master when I have time to work on GAO again. I am currently not sure how to verify that all the behavior is still correct with this algorithm.

**Comment by aaronsamuel137** [comment]
Merged into master, see #169. Deleting the branch and closing this issue.
