### ISSUE TITLE
Dragable bodies don't stop

### ISSUE THREAD

**Issue by phet-steele** [phetsims/gravity-and-orbits#153]
Currently differs from Java. Clicking and holding a celestial object with noticeable velocity will not hold it in place but instead make it very difficult to control as it continues to move:

1.0.0-dev.21 and 1.0.0-experimental.2:
![gao3](https://cloud.githubusercontent.com/assets/5863899/10000413/34d9a24a-6059-11e5-974f-5493dcb7356e.gif)

Java:
![gao2](https://cloud.githubusercontent.com/assets/5863899/10000397/1ccc5c10-6059-11e5-8b4a-7008e4fcda92.gif)

**Comment by aaronsamuel137** [comment]
Good catch. I actually have already fixed this on master when addressing #151. Will be fixed on next dev release.

**Comment by bryo5363** [comment]
I think I found another issue related to this. I noticed that once an object crashes into a larger object (Earth crashing into Sun) the path for the crashed objects continues to animate.

**Comment by aaronsamuel137** [comment]
Fixed the path issue too. Closing
