### ISSUE TITLE
Moon orbit grows in inaccuracy

### ISSUE THREAD

**Issue by phet-steele** [phetsims/gravity-and-orbits#155]
The Earth/Moon/Sun orbit in 1.0.0-dev.21 slowly becomes increasingly inaccurate, and generally by 3000 (with fast forward selected) sim days the moon collides with the Earth. It begins by correctly showing around 12 orbits of the moon for every year, followed by showing fewer and fewer orbits until collision. Comparatively, 1.0.0-experimental.2 does not grow more inaccurate (it matches the Java), but still suffers from #154.

![gao4](https://cloud.githubusercontent.com/assets/5863899/10008253/f8811d56-6089-11e5-870c-95d53cb63af9.gif)

Can be done by just clicking play and waiting. Tested on Win 8.1 Chrome 45.

**Comment by orejolaphet** [comment]
Moon orbit looks stable at 5000+ earth days on http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.0.0-experimental.3/gravity-and-orbits_en.html

**Comment by aaronsamuel137** [comment]
Not an issue on the other branch, which has been merged into master now, so closing.
