### ISSUE TITLE
Return Object does not return moon

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/gravity-and-orbits#156]
Tested on http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.0.0-dev.20/gravity-and-orbits_en.html
and 
http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.0.0-experimental.1/gravity-and-orbits_en.html

For both the Cartoon and To Scale scenes, if you manage to remove the moon from the play area the "return object" button is displayed but does not return the moon.

To reproduce:
Open sim
Pick orbital model that includes the moon
Pause sim
Increase the moons velocity vector
Play sim allow moon to leave
Click "Return object"

**Comment by aaronsamuel137** [comment]
This is already fixed in http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.0.0-dev.21/gravity-and-orbits_en.html and http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.0.0-experimental.2/gravity-and-orbits_en.html

**Comment by aaronsamuel137** [comment]
Sorry if you weren't aware that this new versions were published. Closing
