### ISSUE TITLE
Grid does not span entire screen

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/gravity-and-orbits#157]
Tested http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.0.0-dev.20/gravity-and-orbits_en.html
On OSX 10.10.4

The large scale models, models that include the sun, when completely zoomed out the grid does not span entire screen.
<img width="1271" alt="screen shot 2015-09-22 at 11 31 12 am" src="https://cloud.githubusercontent.com/assets/5631059/10026258/e891dffe-611d-11e5-989c-1e1a0050946a.png">

**Comment by orejolaphet** [comment]
Issue still present in http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.0.0-dev.21/gravity-and-orbits_en.html

**Comment by aaronsamuel137** [comment]
Fixed on master.

**Comment by aaronsamuel137** [comment]
Closing
