### ISSUE TITLE
Gravity vector does not change direction when using rewind.

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/gravity-and-orbits#158]
Tested http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.0.0-dev.21/gravity-and-orbits_en.html
and
http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.0.0-experimental.2/gravity-and-orbits_en.html

With the gravity vector selected, pausing sim and clicking rewind returns orbit to previous state but displays prior gravity vector.

To reproduce:
Turn on gravity vector
Click play 
Wait a second
Click pause
Click rewind

<img width="1277" alt="screen shot 2015-09-22 at 11 42 40 am" src="https://cloud.githubusercontent.com/assets/5631059/10026533/881bdc2c-611f-11e5-84e9-1311eb4a4b0b.png">
<img width="1260" alt="screen shot 2015-09-22 at 11 42 28 am" src="https://cloud.githubusercontent.com/assets/5631059/10026534/881f50dc-611f-11e5-8af7-f94bba27d1c7.png">
<img width="1276" alt="screen shot 2015-09-22 at 11 42 49 am" src="https://cloud.githubusercontent.com/assets/5631059/10026535/881f648c-611f-11e5-9f59-2ac85264f65e.png">

**Comment by aaronsamuel137** [comment]
This issue seems to be present in the Java sim too. Can you verify @orejolaphet?

**Comment by aaronsamuel137** [comment]
And it looks like the gravity force vectors correct themselves as soon as you hit play again.

**Comment by aaronsamuel137** [comment]
Looks like a pretty easy fix.

**Comment by orejolaphet** [comment]
Verified fixed in version http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.0.0-experimental.3/gravity-and-orbits_en.html

**Comment by aaronsamuel137** [comment]
Great. Closing
