### ISSUE TITLE
Requirejs load errors in Safari

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/gravity-and-orbits#159]
The sim loads inconsistently in RequireJS mode on both iPad and OSX Safari. Here's a sample console output:

<img width="1122" alt="screen shot 2015-09-22 at 12 25 51 pm" src="https://cloud.githubusercontent.com/assets/3193912/10027627/4f683ed8-6125-11e5-82fb-9d1f12734f85.png">

The actual file that has a script error varies, it isn't always SubSupText.

**Comment by aaronsamuel137** [comment]
I suspected this might also be related to mipmaps like https://github.com/phetsims/scenery/issues/468. However, there is still an issue when all mipmaps are converted back to images:

<img width="1440" alt="screen shot 2015-09-22 at 12 39 24 pm" src="https://cloud.githubusercontent.com/assets/3193912/10027982/28a2b9ca-6127-11e5-99cc-1ad679de5029.png">

**Comment by aaronsamuel137** [comment]
Definitely looks like an issue with loading resources.

**Comment by aaronsamuel137** [comment]
Sometimes it works, but will take over 30 seconds to load, and sometimes it works normally with the expected load time of a few seconds.

**Comment by aaronsamuel137** [comment]
Reproduced similar load issues on iPad with Color Vision and on Safari in OSX with Charges and Fields.

Looks like this issue is probably not sim specific.

**Comment by aaronsamuel137** [comment]
OSX 10.10.5 and iOS 8.4.1

**Comment by jonathanolson** [comment]
Are the requests timing out? That might be one cause.

**Comment by samreid** [comment]
May be related to https://github.com/phetsims/bending-light/issues/269

**Comment by aaronsamuel137** [comment]
>May be related to phetsims/bending-light#269

I suspect it is. It seems to be an issue with loading resources and timing out.

**Comment by jonathanolson** [comment]
Similarly to https://github.com/phetsims/bending-light/issues/269, the sim is loading fine for me, using require.js mode through Apache.

**Comment by jonathanolson** [comment]
@aaronsamuel137, what web server are you using to host files? Apache has worked well for me.

**Comment by aaronsamuel137** [comment]
Python. It may be that using apache will fix this, I can give it a try.

**Comment by aaronsamuel137** [comment]
Seems to be fixed by using apache instead of python. Closing.

**Comment by samreid** [comment]
I had similar errors with node.js http-server which disappeared when I switched to Apache.
