### ISSUE TITLE
Projector Mode

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/gravity-and-orbits#163]
1. Change text in options to "Projector Mode"
2. Add panel background color to color profile

**Comment by aaronsamuel137** [comment]
The color scheme for the projector mode is still not finished being designed. To modify colors in real time, go to http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.0.0-dev.23/gravity-and-orbits-colors.html.

If there are any other colors that you want modifiable, please let me know.

Assigning to @ariel-phet.

**Comment by ariel-phet** [comment]
@arouinfar - I think @aaronsamuel137 is excited to polish off GAO, can we make this a high priority?

**Comment by arouinfar** [comment]
@aaronsamuel137, here are the RGB (R, G, B) values for Projector Mode. There were a few items that needed a color change that weren't in the gravity-and-orbits-color version, so I don't know how they're referred to in the code. Please let me know if you need any clarification.
* background (255, 255 , 255)
* bodyNodeText (0, 0, 0)
* bottomControlText (0, 0, 0)
* panelBackground (193, 217, 255)
* panelText (0, 0, 0)
* selection stroke around the chosen system (0, 0, 0)
* line between object and label (yellow line labeling the moon below) (0, 0, 0)
* checkbox fill (255, 255, 255)
* grid icon (0, 0, 0)

![image](https://cloud.githubusercontent.com/assets/8419308/10741556/fb78845c-7bed-11e5-9077-d9f91a89aeee.png)

Here's a mockup of the desired look of the checkboxes. The checkbox fill should be white and the grid and path icon colors should also be adjusted to match.
![image](https://cloud.githubusercontent.com/assets/8419308/10741791/2272afe6-7bef-11e5-8007-55ac1bee43a7.png)

One major problem with the projector mode, in general, is that the yellow dot representing the star on the To Scale screen will not show up well on lighter backgrounds. It's nearly impossible to see against white, but is somewhat better on a light gray (240, 240, 240). I'm not really fan of a gray background, however. I hope once the yellow lines are changed to black, it'll be easier to interpret.
![image](https://cloud.githubusercontent.com/assets/8419308/10741885/a5f5653e-7bef-11e5-990f-37d8980ad555.png)
![image](https://cloud.githubusercontent.com/assets/8419308/10741938/08c15f56-7bf0-11e5-978d-4f043fa04b26.png)

**Comment by aaronsamuel137** [comment]
I've made these updates, see http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.0.0-dev.24/gravity-and-orbits_en.html to review.

You can also use the color picker at http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.0.0-dev.24/gravity-and-orbits-colors.html.

Assigning to @arouinfar for review.

**Comment by arouinfar** [comment]
Thanks @aaronsamuel137! Overall, think it looks great. I only have one request -- can you make the selection stroke around the system (e.g. Earth + Moon) black?

**Comment by aaronsamuel137** [comment]
I've made this update. Let me know what you think.

Can you view it on master or do you need a new dev version published?

**Comment by arouinfar** [comment]
@aaronsamuel137 no need to publish a dev version. I can take a look on phettest once I get to the office. Thanks!

**Comment by arouinfar** [comment]
Just realized I hadn't commented on this issue @aaronsamuel137. I think it looks great! Closing.
