### ISSUE TITLE
Consider minimize button for menu?

### ISSUE THREAD

**Issue by bryo5363** [phetsims/gravity-and-orbits#165]
I believe adding a minimize feature to the orbit menu would benefit the user; when in 'To Scale' it is easy to displace the system by giving all objects some sort of velocity. The system sometimes will tend towards the right of the screen and in some instances gets blocked by the menu. By enabling some sort of minimization the user will be able to observe the orbits without any obstructions.

**Comment by ariel-phet** [comment]
An interesting thought, but we usually only have minimize buttons on controls as a teacher use or for scaffolding. Does not really fit with the design here. Closing
