### ISSUE TITLE
Internationalize "V" string

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/gravity-and-orbits#167]
This is a TODO from the Java:

```js
TODO: i18n of "V", also recommended to trim to 1 char
```

**Comment by aaronsamuel137** [comment]
Added a translatable string for "V". The TODO mentioned possibly trimming to one character. However, this is not really straightforward using our string plugin, possibly because of the embedding marks?

Logging vString.length yields 9 in requireJS mode and 3 in build mode, instead of the 1 that we'd expect.

@samreid, do you have any thoughts about whether trimming this to one char is necessary?

**Comment by samreid** [comment]
Trimming to one char doesn't seem necessary.  Rather we should make sure it is obvious to translators how it will appear in the simulation and that brevity is valuable (through documentation/examples?), and perhaps scale the text to fit within the allowed space.

**Comment by aaronsamuel137** [comment]
>Rather we should make sure it is obvious to translators how it will appear in the simulation and that brevity is valuable (through documentation/examples?)

Not sure where we will put this documentation/examples. I think Rosetta v2 will support things like hints, and that would probably be the place to put this.

>perhaps scale the text to fit within the allowed space.

Sounds like a good idea, I'll add scaling

**Comment by aaronsamuel137** [comment]
Scaling added. Closing for now.
