### ISSUE TITLE
Design Tweaks

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/gravity-and-orbits#170]
We discussed in the 9/24 design meeting a few design changes:

- Move Star/Planet sliders into separate panels
- Make sliders as large as possible
- Left aligned slider labels
- Try black panel.

I was under the impression I was waiting for a new mockup to make these changes, but I can also go ahead and make them myself and get feedback. What do you think @ariel-phet?

**Comment by ariel-phet** [comment]
@aaronsamuel137 why don't you go ahead and make these changes. I would say with the sliders not so much make them "as large possible" but more try to bring them closer to standard size, and add a bit of negative space between the two slider tracks if possible.

**Comment by aaronsamuel137** [comment]
I've made a first pass of these changes on master. Let me know what you think @ariel-phet.

**Comment by aaronsamuel137** [comment]
Other minor things to think about:

- When the moon is shrunk or grown, it changes to a weird hot pink color. Should we consider changing this?
- In the Java version the planet in the control panel doesn't change to a generic sphere when you change the mass, though it did in the MLL version so I kept this change. Do we want this to change or not?

**Comment by ariel-phet** [comment]
@aaronsamuel137 

1. I would be fine with changing the hot pink color...your choice
2. I think changing to the generic sphere in the control panel is a nice touch
3. Most of the other changes look good but when we said "separate control panel" for mass

I was thinking something like this:

![gao](https://cloud.githubusercontent.com/assets/4051174/10749380/5df42d0c-7c2f-11e5-8069-ab752b8e5665.PNG)

**Comment by aaronsamuel137** [comment]
OK I've made these changes. I'm okay with the hot pink for now, just wanted to bring it up for discussion.

I like the look of the new panels. Let me know what you think. Assigning to @ariel-phet.

**Comment by ariel-phet** [comment]
Looking good to me!

**Comment by arouinfar** [comment]
I wasn't tagged, so never saw this issue. My apologies for not chiming in sooner. I think the new panels look great @aaronsamuel137, but I have a few more requests:

- [ ] The panel corners seem pretty sharp, can you round them to be more consistent with PhET look-and-feel? The mockup below shows 5pt rounding.
- [ ] Connect slider tick marks to the track like this (please ignore other font/color differences)

![image](https://cloud.githubusercontent.com/assets/8419308/10977269/46772c94-83ad-11e5-9e80-ccfa7cdfc1db.png)

**Comment by aaronsamuel137** [comment]
I've made these changes and deployed to master. Let me know what you think @arouinfar.

**Comment by arouinfar** [comment]
Looks great! Thanks @aaronsamuel137.
