### ISSUE TITLE
no margin around Reset All button

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gravity-and-orbits#174]
Noticed during code review, https://github.com/phetsims/gravity-and-orbits/issues/173.

There is no margin between the right edge of the "Reset All" button, and very little margin below if. See screenshot below. This occurs in both screens.

![screenshot_56](https://cloud.githubusercontent.com/assets/3046552/11040072/cba51878-86c7-11e5-8680-d0ae5891cc90.png)

**Comment by pixelzoom** [comment]
Same issue with right edge of control panels.

**Comment by aaronsamuel137** [comment]
Added some more margin here and factored out MARGIN into a constant. Right now it is set to 5, do you think it needs more?

**Comment by pixelzoom** [comment]
I think this up to your design team or team leader. To my eye, everything looks a little close to the edges of the Screen.layoutBounds. But if it looks/works OK on iPad (where you will be interacting on the very edge of the physical screen) then perhaps its OK.

**Comment by aaronsamuel137** [comment]
It looks okay to me, but I'll ask @arouinfar what she thinks. Assigning to @arouinfar for comment.

**Comment by arouinfar** [comment]
I agree with @pixelzoom that reset all and control panel could use a little bit of padding to the right. I'll pull the latest from phettest when I get into the office so I can see what adjustments @aaronsamuel137 has made.

**Comment by arouinfar** [comment]
Just realized that I forgot to take care of this yesterday when verifying #83. The 5px margin looks good to me and is usable on iPad. Thanks @aaronsamuel137. Closing.
