### ISSUE TITLE
usability of check boxes?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gravity-and-orbits#175]
Noticed during code review https://github.com/phetsims/gravity-and-orbits/issues/173.

There is very little vertical space between the check boxes in the control panel, and they do not have dilated touch areas (as check boxes typically do in sims).  See screenshot below.  Has usability of this been evaluated on touch devices?

![screenshot_57](https://cloud.githubusercontent.com/assets/3046552/11040194/4ca18cae-86c8-11e5-99ee-09a83db33053.png)

**Comment by pixelzoom** [comment]
Also wondering why there are pointer areas set for the icon to the right of "Measuring Tap". Pointer areas are typically set for the entire check box component.

**Comment by pixelzoom** [comment]
Ah... The icon to the right of "Measuring Tape" is scenery-phet.MeasuringTape, which has a default touchArea and mouseArea.

As for the usability of the check boxes... This might be a question for your design team or team leader, and should be checked on iPad.

**Comment by aaronsamuel137** [comment]
I've increased the touch area for the checkboxes and tested on iPad. Seems much more usable than before.

Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
:+1: Closing.
