### ISSUE TITLE
many layout problems with stringTest=long

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gravity-and-orbits#176]
Related to code review https://github.com/phetsims/gravity-and-orbits/issues/173.

Running with `stringTest=long` query parameter reveals many i18n layout problems (in all screens) that need to be addressed.  For example, see screenshot below.

I see only 2 occurrences of option `maxWidth` in the source code. So my suspicion is that layout issues for i18n have not been addressed. 

![screenshot_58](https://cloud.githubusercontent.com/assets/3046552/11040486/bf9f25c6-86c9-11e5-9031-44c7c4289840.png)

**Comment by aaronsamuel137** [comment]
I've addressed these issues. Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
:+1: Closing.
