### ISSUE TITLE
create screenshot

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gravity-and-orbits#177]
Related to code review #173.

Create `assets/gravity-and-orbits-screenshot.png` before publication.

**Comment by pixelzoom** [comment]
@ariel-phet I think we should remove screenshot-related items from the code-review checklist, since the screenshot typically isn't created until the sim is completed.  The screenshot belongs on the sim-completion checklist (where it may already be). Do you agree?

**Comment by ariel-phet** [comment]
@pixelzoom I agree, and it is on the master checklist.

**Comment by pixelzoom** [comment]
OK, I've removed it from https://github.com/phetsims/phet-info/blob/master/checklists/code_review_checklist.md.

**Comment by aaronsamuel137** [comment]
I don't have the right kind of iPad to take this screenshot the way that is described in the deployment checklist (https://github.com/phetsims/phet-info/blob/master/sim_deployment.md).

Assigning to @ariel-phet for now to either take care of this or assign someone else.

**Comment by ariel-phet** [comment]
@arouinfar Can you take a screenshot for GAO? I think the model screen would be most appropriate and eye catching, and probably something similar to the screenshot used for the java version (unless you have strong opinions, then go with those).

**Comment by arouinfar** [comment]
@ariel-phet, I think we should wait to make the official screenshot until #83 is addressed, but I was thinking about something like this:
<img width="842" alt="screen shot 2015-11-18 at 11 06 21 am" src="https://cloud.githubusercontent.com/assets/8419308/11249508/858c07c4-8de4-11e5-8b1a-bd72cbfdca49.png">

**Comment by ariel-phet** [comment]
Awesome, looks good to me!

**Comment by arouinfar** [comment]
@aaronsamuel137 has taken care of #83, so I've created the screenshot and have emailed it to him to check in.

<img width="1024" alt="gravity-and-orbits-screenshot" src="https://cloud.githubusercontent.com/assets/8419308/11250170/5923c3a8-8de8-11e5-9f53-5c8c4af49333.png">

**Comment by aaronsamuel137** [comment]
Screenshot checked in. Closing
