### ISSUE TITLE
missing asset file for cartoon_icon.png

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gravity-and-orbits#178]
Related to code review https://github.com/phetsims/gravity-and-orbits/issues/173.

This entry in images/license.json has no associated .ai file in assets/.

```js
  "cartoon_icon.png": {
    "text": [
      "Copyright 2002-2015 University of Colorado Boulder"
    ],
    "projectURL": "http://phet.colorado.edu",
    "license": "contact phethelp@colorado.edu",
    "notes": "created by Bryce Gruneich and Sharon Siman-Tov"
  },
```

**Comment by aaronsamuel137** [comment]
It's included in the to_scale_icon.ai file. Would you recommend splitting these into 2 files or just renaming to something like screen_icons.ai?

**Comment by pixelzoom** [comment]
Since there is a 1:1 mapping from png:ai for all other files, I'd recommend splitting this out. Otherwise I'd never know which file to look in, and I'd assume that it's missing.

**Comment by pixelzoom** [comment]
:+1: Closing.

**Comment by pixelzoom** [comment]
whoops, closed the wrong issue.

**Comment by aaronsamuel137** [comment]
Split these out into 2 ai files. Closing
