### ISSUE TITLE
bad URL in model.md

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gravity-and-orbits#179]
Related to code review #173.

model.md references a bad URL:

`http://arxiv.org/pdf/cond-mat/0110585v<sub>1</sub>.pdf`

Presumably the `<sub>` tags should be removed?

**Comment by aaronsamuel137** [comment]
Good catch. Replaced "v1" with "v<sub>1</sub>" for the equations and didn't realize there was a v1 in the url too.

Fixed now. Closing
