### ISSUE TITLE
unused audio plugin appears in config.js

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gravity-and-orbits#181]
Related to code review #173.

The audio plugin appears in gravity-and-orbits-config.js, and the sim doesn't appear to use any audio (doesn't use VIBE). 

`audio: '../../chipper/js/requirejs-plugins/audio',`

There may be no harm in this, and I don't know if this increases the .html file size. But we typically don't include things that aren't used.

**Comment by aaronsamuel137** [comment]
Removed audio plugin. Closing
