### ISSUE TITLE
js/ directory is not properly structured

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gravity-and-orbits#182]
Related to code review #173.

The js/ directory currently has this structure:

```
gravity-and-orbits/
  model/
  module/
  view/
gravity-and-orbits-config.js
gravity-and-orbits-main.js
```

`doc/implementation-notes.md` describes the atypical structure of this sim, so I understand why there's a `modules/` subdirectory.  But I don't understand why that affects the ability to have a subdirectory per screen. 

So while it's likely to be painful, it's recommended to restructure the source to match PhET conventions. There should still be a subdirectory per screen, plus a subdirectory for common (shared) things, like this:

```
cartoon/
    model/
    module/
    view/
common/
    model/
    module/
    view/
toScale/
    model/
    module/
    view/
gravity-and-orbits-config.js
gravity-and-orbits-main.js
```

**Comment by pixelzoom** [comment]
While we're looking at the directory structure, I see currently see this:

```
gravity-and-orbits/
  view/
    bottom-control-panel/
    right-control-panel/
...
```

Both control panels are on the right, so "right-control-panel" is ambiguous. One is on top, one is on the bottom.  Recommended to rename "right-control-panel" to "top-control-pane".  Or better yet, give these control panels names indicative of their contents.

**Comment by aaronsamuel137** [comment]
>I don't understand why that affects the ability to have a subdirectory per screen.

There are really not many screen specific files in this sim. The two screens are nearly identical, and use the same files with a bit of conditional logic. Perhaps we could put CartoonModeList and RealModeList into different folders, but those are literally the only files, the rest would be common. Do you think its worth it to do that? I could just document more thoroughly why the directory structure is atypical.


> Both panels are on the right, so "right-control-panel" is ambiguous.

These folder are badly named. The files in "right-control-panel" include both the control panels on the right. The files in "bottom-control-panel" are all the controls on the bottom of the screen, though they are not actually in a panel. What would you think about renaming the directories "right-controls" and "bottom-controls"? Or just moving everything to view?

**Comment by pixelzoom** [comment]
> Perhaps we could put CartoonModeList and RealModeList into different folders, but those are literally the only files, the rest would be common. Do you think its worth it to do that?

Yes.

> What would you think about renaming the directories "right-controls" and "bottom-controls"? Or just moving everything to view?

I would move the files to view/.  And deal with choosing better names in https://github.com/phetsims/gravity-and-orbits/issues/192.

**Comment by aaronsamuel137** [comment]
Restructured the files as suggested. Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
:+1: Closing.
