### ISSUE TITLE
no visibility annotations for prototype functions

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gravity-and-orbits#183]
Related to code review #173.

Visibility annotations (@public, @protected, @private) are noticeably missing from prototype functions. For example, in Body.js, BodyState.js, GravityAndOrbitsClock.js,...  *All* parts of the JS interface that are publicly visible should have a visibility modifier to document the developer's intention.  This include adding a @public annotation to functions that are intended to be public; the default is no longer to assume that lack of an annotation means public.

**Comment by aaronsamuel137** [comment]
Added annotations. Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
Spot checked, looks good, closing.
