### ISSUE TITLE
bad type expressions in JSdoc

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gravity-and-orbits#184]
For example in Body.js:

`@param {Property<boolean>} playButtonPressedProperty`

should be

`@param {Property.<boolean>} playButtonPressedProperty`

Note the '.' before '<boolean>'.

This occurs throughout the code.

**Comment by pixelzoom** [comment]
Related to code review #173.

**Comment by aaronsamuel137** [comment]
Should be fixed. Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
Spot checked, looks great. Closing.
