### ISSUE TITLE
units are not documented

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gravity-and-orbits#185]
Related to code review #173.

There are lots of quantities in this sim that have units, but the units are not documented in the code. Examples:

Body.js has position, diameter, velocity, mass, ...

BodyState.js has position, velocity, acceleration, mass,... 

And there are likely other examples.  I think it would be fine to document units in model.md, if that makes life easier.

**Comment by aaronsamuel137** [comment]
I've documented units, anything I'm forgetting here?

Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
Looks good, closing.
