### ISSUE TITLE
magic numbers in CartoonModelList

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gravity-and-orbits#186]
Related to code review #173.

There are numerous magic numbers in CartoonModelList.

Issues:

• Some of these constants are documented as "tuned by hand", some are not documented. All magic numbers should be documented, along with any dependencies that other things may have on this numbers. (Eg, "If you change foo, be sure to change bar.")

• Some are duplicated in multiple places. For example `this.sun.radius *= 50` appears in 2 places. If I change one, do I need to change the other? Similarly for `this.earth.radius *= 800`.

• `this.timeScale = 365.0 / 334.0` is odd. Is there a significance to the numerator and denominator values? If so, document. If not, collapse to a single number.

**Comment by aaronsamuel137** [comment]
Factored out some of these into constants, and documented as best I can without knowing for sure where these came from (ported directly from Java with all comments).

Regarding 365.0 / 334.0, the 365 seems like is must refer to days in a year, but I am not 100% sure where these numbers came from. I am inclined to leave it as is. Perhaps @samreid has some memory of this?

**Comment by samreid** [comment]
This is fuzzy in my mind, but I recall manual adjustment of values was necessary to produce the desired macroscopic behavior.  The code comment in the context is:

```js
    // Have to artificially scale up the time readout so that Sun/Earth/Moon mode has a stable orbit with correct
    // periods since masses are nonphysical
    this.timeScale = 365.0 / 334.0;
```

**Comment by aaronsamuel137** [comment]
Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
@samreid In https://github.com/phetsims/gravity-and-orbits/issues/186#issuecomment-156219534, is `365` indeed the number of days in a year?

**Comment by samreid** [comment]
In this model, yes.

**Comment by pixelzoom** [comment]
Thanks. Noted in source code doc.
