### ISSUE TITLE
issues with Properties for measuring tape visibility

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gravity-and-orbits#187]
Related to code review #173.

Here's the code in question:

```js
 function GravityAndOrbitsModule( showMeasuringTape, createModes, initialModeIndex, showMassCheckBox ) {

    // Properties that are common to all "modes" should live here.
    PropertySet.call( this, {
      ...
      measuringTapeVisible: false,
      ...
      showMeasuringTape: false
    } );

    ...

    this.showMeasuringTape = showMeasuringTape;
```

(1) Why are there 2 properties related to visibility of the measuring tape? (measuringTapeVisible, showMeasuringTape)

(2) Why is the function argument not used to set the initial value of `showMeasuringTape` or `measuringTapeVisible`?

**Comment by aaronsamuel137** [comment]
Good catch. showMeasuringTape is supposed to be a boolean and not a property. I have corrected and documented. Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
:+1: Closing.
