### ISSUE TITLE
anti-pattern for reset

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gravity-and-orbits#188]
Related to code review #173.

Here's the reset function in GravityAndOrbitsModule, which extends PropertySet:

```js
    reset: function() {
      for ( var i = 0; i < this.modeList.modes.length; i++ ) {
        this.modeList.modes[ i ].reset();
      }
      this.showGravityForceProperty.reset();
      this.showPathProperty.reset();
      this.showGridProperty.reset();
      this.showVelocityProperty.reset();
      this.showMassProperty.reset();
      this.playButtonPressedProperty.reset();
      this.timeSpeedScaleProperty.reset();
      this.measuringTapeVisibleProperty.reset();
      this.gravityEnabledProperty.reset();
      this.steppingProperty.reset();
      this.rewindingProperty.reset();
      this.modeProperty.reset();
    }
```

The problem here is that if a Property is added to this set, you need to remember to add it to the reset function too.  And it's also totally unnecessary, since PropertySet defines reset. 

So the above should be:

```js
/**
 * @public
 * @override
 */
reset: function() {
  PropertySet.prototype.reset.call( this );
  for ( var i = 0; i < this.modeList.modes.length; i++ ) {
    this.modeList.modes[ i ].reset();
  }
}
```

Or move the supertype call after the `for` loop, if order is truly important.

The identical issue occurs in GravityAndOrbitsMode.js.

**Comment by pixelzoom** [comment]
Also note the `@override` annotation that was added to the JSdoc for `reset`.

**Comment by aaronsamuel137** [comment]
Good catch, this anti-pattern was carried over from the Java version. Fixed now. Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
One additional suggestion in GravityAndOrbitsModule... Instead of creating `modeProperty` like this:

` this.modeProperty = new Property( this.modeList.modes[ initialModeIndex ] );`

... add it to the PropertySet, like this:

`this.addProperty( 'mode', this.modeList.modes[ initialModeIndex ]  );`

Then you won't need to handle it explicitly in `reset`.

**Comment by aaronsamuel137** [comment]
Good suggestion, forgot about addProperty(). Made this change. Closing
