### ISSUE TITLE
anti-pattern for abstract types

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gravity-and-orbits#189]
Related to code review #173.

ModeConfig is intended to be an abstract base type, so the first thing would be to describe it as such in the JSdoc at the top of the file.

Then there's this function that must be implemented by subtypes:

```js
    // abstract
    /**
     * @returns {Array<BodyConfiguration}
     */
    getBodies: function() {}
```

This pattern is not recommended because (in the general case) it can succeed silently when it should fail.

The more typical pattern for functions in abstract types is to either (a) not define them so that they fail, or (b) implement a function that fails.  My preference is for (b), since it also provides the opportunity to document.   So recommended to replace the above with:

```
    /**
     * @returns {BodyConfiguration[]}
     * @public
     * @abstract
     */
    getBodies: function() {
      throw new Error( 'must be implemented by subtype' );
    }
```

**Comment by aaronsamuel137** [comment]
I've made these changes, assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
:+1: Closing.
