### ISSUE TITLE
missing visibility annotations for fields

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gravity-and-orbits#190]
Related to code review #173.

Lots of examples... BodyConfig, ModeConfig, ModeList, ModeListParameterList ... Looks like someone should go through all of the code again.

All publicly-visible fields (e.g., `this.foo`) must have an associated visibility modifier. Assuming @public in the absence of an annotation is no longer the convention.

**Comment by aaronsamuel137** [comment]
Added annotations. For some classes I commented like so:


```js
    // all fields are @public
    this.fixed = false; // True if the object doesn't move when the clock ticks
    this.mass = mass;
    this.radius = radius;
    this.x = x;
    this.y = y;
    this.vx = vx;
    this.vy = vy;
```

Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
@aaronsamuel137 If you have multiple fields that are public, and there are no blank lines between their declarations, the convention is to do this:

```js
   // @public
    this.fixed = false; // True if the object doesn't move when the clock ticks
    this.mass = mass;
    this.radius = radius;
    this.x = x;
    this.y = y;
    this.vx = vx;
    this.vy = vy;
```

Similarly for a PropertySet, the convention is:

```js
new PropertySet( {

  // @public
  mass: 10,
  radius: 10
} );
```

For a PropertySet with Properties of varying visibility, you can do either of these:

```js
new PropertySet( {
  p1: ...   // @public
  p2: ...   // @private
  p3: ...   // @public
  p4: ...   // @private
} );

new PropertySet( {

  // @public
  p1: ...
  p3: ...

  // @private
  p2: ...
  p4: ...
} );
```
