### ISSUE TITLE
reduce coupling to GravityAndOrbitsModule

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gravity-and-orbits#191]
Related to code review #173.

GravityModeMenu is the control for turning gravity on/off.  Here are the relevant pieces of its constructor:

```js
function GravityModeMenu( module, options ) {
...
  new AquaRadioButton( module.gravityEnabledProperty, true, onTextNode, RADIO_OPTIONS ),
  new AquaRadioButton( module.gravityEnabledProperty, false, offTextNode, RADIO_OPTIONS )
...
  }
```

By passing `module` into the constructor, unnecessary coupling between `GravityAndOrbitsModule` and `GravityModeMenu` is created. Increasing coupling (in general) increases the probability of bugs and increases maintenance costs. Eliminate this coupling by passing in only what is needed by GravityModeMenu; that is, `gravityEnabledProperty`.  I.e.:

```js
function GravityModeMenu( gravityEnabledProperty, options ) {
...
  new AquaRadioButton( gravityEnabledProperty, true, onTextNode, RADIO_OPTIONS ),
  new AquaRadioButton( gravityEnabledProperty, false, offTextNode, RADIO_OPTIONS )
...
  }
```

**Comment by pixelzoom** [comment]
Identical issue in TimeControlPanel, PlanetModePanel and (perhaps) SpaceObjectsPropertyCheckbox.

**Comment by aaronsamuel137** [comment]
I've addressed this issue for all the mentioned files except SpaceObjectsPropertyCheckbox. It seems like this file uses 7 or 8 attributes of module, so passing the whole module seems justifiable to me. What do you think?

Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
Good, closing.
