### ISSUE TITLE
nonintuitive and misleading type names

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gravity-and-orbits#192]
Related to code review #173.

Some (many?) of the type names in this sim are nonintuitive and downright misleading, making it unnecessarily difficult to navigate the code, or locate things by guessing their names.  This is no fault of @aaronsamuel137, it was inherited.

Some examples, not exhaustive:

• SpaceObjectsPropertyCheckbox - it's not a Property or a CheckBox, it's a Panel. SpaceObjectsPanel would be better. (What is a "space object", btw?)

• GravityModeMenu - it's not a menu, it's a pair of on/off radio buttons. GravityControl would be better.

• PlanetModeMenu - it's not a menu, it's a set of radio buttons. And it doesn't select a planet, it selects a configuration of planets and satellites. Not sure what the proper name would be, maybe something like SystemControl? 

• RightControlPanel - there are 2 control panels in the sim, and they are both on the right. How about a name that represents the nature of the stuff being controlled?

It's never fun to have to rename types (and their associated vars at call sites).  But if this isn't done now, it will mean more difficult maintenance in the future.

**Comment by pixelzoom** [comment]
`PlanetModeMenu` might be renamed to simply `ModeMenu`, since a "mode" in this sim is described (in see GravityAndOrbitsModule JSdoc) as a "configuration of bodies":

> * The GravityAndOrbitsModule has a set of "modes", one mode for each configuration of bodies (eg, Sun + Planet).

**Comment by aaronsamuel137** [comment]
I've renamed three of the files, let me know if these names seem clear enough to you.

Regarding RightControlPanel, it is difficult to name it something related to its content since it has 3 sections. ModeGravityCheckboxControlPanel seems weird.

What do you think about these?
- UpperRightControlPanel
- GravityAndOrbitsControlPanel (from Java)
- ControlPanel

**Comment by pixelzoom** [comment]
Let's go with UpperRightControlPanel.  I hate naming things based on their layout, but can't come up with anything better in this situation.  I'm going to go ahead and close this. @aaronsamuel137 if there's anything else, please reopen.
