### ISSUE TITLE
define symbols in model.md

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gravity-and-orbits#193]
Related to code review #173.

model.md refers the reader to http://arxiv.org/pdf/cond-mat/0110585v1.pdf, then summarizes the model equations used.  It defines some (but not all) of the symbols used in those equations. Since the pdf file could disappear at some point in the future, I think it's important to define *all* symbols used in the equations.  So let's define `f, h, m, r, t, v` (and any others that I may have missed) in the "where" section of model.md.  I.e.:

```
where

ξ = +0.1786178958448091E+00

λ = −0.2123418310626054E+00

χ = −0.6626458266981849E−01

f = 

h =

m = 

r = 

t = 

v = 
```

**Comment by aaronsamuel137** [comment]
Updated this document. Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
:+1: Closing.
