### ISSUE TITLE
odd touchAreas for zoom control

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gravity-and-orbits#194]
Related to code review #173.

Here's a screenshot with `showPointerAreas` query parameter. The red dashed lines are touchAreas. Look at the touchAreas for the zoom buttons (+,-).  They are surrounded by 2 red dashed boxes, indicating that they have 2 touchAreas, with odd overlapping.

![screenshot_59](https://cloud.githubusercontent.com/assets/3046552/11044145/60a39bce-86dd-11e5-98a9-63160972bcc9.png)

**Comment by pixelzoom** [comment]
I haven't inspected the code. But this could be caused by taking a node that has a default touchArea and mouseArea, then wrapping it in another node and setting the wrapper node's touchArea.  I suspect there's something like that going on here.

**Comment by pixelzoom** [comment]
Here's the problem... In ScaleSlider, the zoom buttons are instances of SliderButton, and they have their touchArea set.  They have a child of type RectangularPushButton that also has a default touchArea that's dilated by dx=5, dy=5 (see RectangularPushButton options `xTouchExpansion` and `yTouchExpansion`).
The solution is to make SliderButton extend RectangularPushButton instead of Node.

**Comment by aaronsamuel137** [comment]
I've made this change. Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
:+1: Closing.
