### ISSUE TITLE
RewindableProperty doc and API

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gravity-and-orbits#195]
Related to code review #173.

RewindableProperty is heavily used for various Properties that can be rewound. A few things...

(1)  The JSdoc is pretty sparse, and (I think) would benefit from some expansion/revision. It's also a little misleading where it says "it goes back to the value last set while the clock was paused". There is no dependency on the clock, it goes back to the value set by `storeRewindValueNoNotify` (which is probably called by something that's observing the clock). 

(2) `getInitialValue` is poorly named. The initial value for a Property is the value that is passed to its constructor, `this._initialValue`. This function returns `this.rewindValue`. So this should be renamed to `getRewindValue`. 

(3) There is some coupling here that seems misplaced. Specifically need to pass in and check Properties `playButtonPressedProperty, isSteppingProperty and isRewindingProperty` (in `set` override) has a bad-code smell.  Rather than passing in these 3 properties, it would be better to pass in 1 DerivedProperty that indicates the conditions under which a call to `set` results in adjusting the rewind value.  E.g. in Body.js:

```js
var changeRewindValueProperty = new DerivedProperty( 
  [ playButtonPressedProperty, isSteppingProperty, isRewindingProperty ], 
  function( playButtonPressed, isStepping, isRewinding ) {
    return !playButtonPressed && !isStepping && !isRewinding;
  }
);
this.positionProperty = new RewindableProperty( changeRewindValueProperty, new Vector2( x, y ) ); // @public
...
```

**Comment by aaronsamuel137** [comment]
I've made these changes. Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
Looks great, closing.
