### ISSUE TITLE
var names of type {Property} must have a 'Property' suffix

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gravity-and-orbits#196]
Related to code review #173.

In ModeListParameterList:

```js
/**
   *
   * @param {Property<boolean>} playButtonPressed
   * @param {Property<boolean>} gravityEnabled
   * @param {Property<boolean>} stepping
   * @param {Property<boolean>} rewinding
   * @param {Property<number>} timeSpeedScale
   * @constructor
   */
function ModeListParameterList( playButtonPressed, gravityEnabled, stepping, rewinding, timeSpeedScale ) 
```

Per PhET naming conventions, all of these parameters must be renamed to have a `Property` suffix. Eg:

playButtonPressed -> playButtonPressedProperty

**Comment by pixelzoom** [comment]
Same problem in GravityAndOrbitsClock, CartoonModeList and RealModeList.

**Comment by aaronsamuel137** [comment]
I've made these changes, assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
Spot checked, looks good, closing.
