### ISSUE TITLE
bug in CONTROL_PANEL_OPTIONS ?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gravity-and-orbits#197]
Related to code review #173.

In GravityAndOrbitsConstants:

```js
    CONTROL_PANEL_OPTIONS: {
      ...
      fill: GravityAndOrbitsColorProfile.panelBackgroundProperty
    },
```

This looks like a bug.  
Shouldn't it be `GravityAndOrbitsColorProfile.panelBackgroundProperty.get()`?

**Comment by pixelzoom** [comment]
Or perhaps I don't understand how the color profile works. If that's the case, please describe.

**Comment by aaronsamuel137** [comment]
It's not a bug. Scenery now supports Property as an allowed type for fills. Passing the property here makes so the panel color will update automatically when the projector mode is turned on.

Let me know if you have more questions here, otherwise feel free to close.
