### ISSUE TITLE
expand pointer areas for small bodies?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gravity-and-orbits#199]
Here's the "To Scale" screen:

![screenshot_105](https://cloud.githubusercontent.com/assets/3046552/11407116/f13fb162-936d-11e5-926b-8fd5b53549cd.png)

I was surprised to find that there are no mouseArea or touchArea dilations for the very small bodies (labeled Star, Moon, Planet).  On a desktop host, I struggled to select these bodies.  On a tablet, it will be next to impossible.   If the goal of the "To Scale" screen is to demonstrate that some bodies are so small that you can't possibly manipulate them, then screen has succeeded :)

**Comment by ariel-phet** [comment]
This might have been a carry over from the Java version, I have to admit I am not sure I realized they were selectable. @jessegreenberg please dilate these touch and mouse areas

**Comment by ariel-phet** [comment]
And thanks for pointing out @pixelzoom!

**Comment by pixelzoom** [comment]
yup.

**Comment by pixelzoom** [comment]
Btw... I think we should add a "?showPointerAreas" test to the general procedures for dev and RC testing.

**Comment by ariel-phet** [comment]
Why don't you go ahead and add that to the redeploy checklist for the moment

**Comment by pixelzoom** [comment]
Done, https://github.com/phetsims/phet-info/blob/master/checklists/S2015R_checklist.md

- [ ] showPointerAreas (touchArea=red, mouseArea=blue)

**Comment by jessegreenberg** [comment]
Done in commit above, but since small bodies are so close together, touch areas will overlap. This acceptable @ariel-phet?

![overlap1](https://cloud.githubusercontent.com/assets/6396244/16974805/7e54f054-4dfd-11e6-85b8-957614dd9c32.PNG)

![overlap2](https://cloud.githubusercontent.com/assets/6396244/16974807/81260f48-4dfd-11e6-977d-bcd52e1e2fbe.PNG)

**Comment by ariel-phet** [comment]
Looks good! closing
