### ISSUE TITLE
Model inconsistencies?

### ISSUE THREAD

**Issue by samreid** [phetsims/gravity-and-orbits#20]
I noticed that in the original Java Gravity and Orbits, the Moon goes around the Earth about 12 times per year.  However, it should be closer to 13.3 times (I think).  The HTML5 version shows about 13 rotations per year.  I am just wondering if there are some model inconsistencies between the versions and if they could cause any problems.  I'm attaching a screenshot that shows the difference in the moon orbital phase between the two models.
![gao](https://f.cloud.github.com/assets/679486/1510453/ef4b4e34-4a81-11e3-8b1a-71e3aeeb18cf.png)

On the left, the HTML5 version with 10 points on the magenta curve, and on the right the Java version showing 9 points for the same amount of time.

**Comment by aaronsamuel137** [comment]
Not relevant is rewrite. Closing
