### ISSUE TITLE
slider tracks aren't visible

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gravity-and-orbits#202]
Not sure when this problem was introduced, and I suspect it's probably changes that were made to HSlider.  But in 1.0.0-dev.24, sliders looked like this:

![screenshot_73](https://cloud.githubusercontent.com/assets/3046552/17228165/1d2684ea-54cf-11e6-88fd-966cdec02bea.png)

In master (67f1f83d92c707f994da051fbeab98bd96d78177) they look like this:

![screenshot_74](https://cloud.githubusercontent.com/assets/3046552/17228177/2d69dea6-54cf-11e6-89c1-b73bcb20aece.png)

Note that the slider tracks are not visible.  True of all sliders in all screens.

**Comment by pixelzoom** [comment]
Note that the tick marks also look different, longer in master.

**Comment by arouinfar** [comment]
Just to add to the discussion here -- the slider appearance in dev.24 is not the desired look. In the projector mode of master, the slider looks like this
![image](https://cloud.githubusercontent.com/assets/8419308/17502104/6babdee0-5da2-11e6-9722-8d425eead69c.png)

This is the desired appearance for the sliders. When fixing the slider in regular mode, please match this look, but with white track/ticks @jessegreenberg.

**Comment by veillette** [comment]
FYI, in the projector mode the slider is present, (in master)

![image](https://cloud.githubusercontent.com/assets/7633344/17706831/9cad93ee-63ab-11e6-92a7-4b76a0cc51d9.png)

but the slider track is absent when projector mode is turned off.

**Comment by veillette** [comment]
It is related to the Hslider in BodyMassControl. 
I think you want to comment out the trackfill and set the trackStroke instead. 

```
    var slider = new HSlider( body.massProperty, { min: min, max: max }, {
      trackSize: new Dimension2( WIDTH, 1 ),
      thumbSize: THUMB_SIZE,
      trackLineWidth: 0,
      //trackFill: GravityAndOrbitsColorProfile.panelTextProperty,
      trackStroke: GravityAndOrbitsColorProfile.panelTextProperty,
      // custom thumb
      thumbFillEnabled: '#98BECF',
      thumbFillHighlighted: '#B3D3E2'
    } );
```

I am not going to commit ince I dont fully undertsnad the role of trackLineWIdth and trackFill.

**Comment by jessegreenberg** [comment]
Thanks @veillette, I think you are right.  We need trackStroke here.  The stroke was defaulted to black since trackFill is not a recognized option, which made it invisible in the regular mode and visible in projector mode.  This was likely introduced from https://github.com/phetsims/sun/issues/224.

**Comment by jessegreenberg** [comment]
Fixed in commit above, sliders now look like this, in normal mode:
![capture1](https://cloud.githubusercontent.com/assets/6396244/17748691/d2838bbe-6477-11e6-9cf3-4a745a842e12.PNG)

And this in projector mode:
![capture2](https://cloud.githubusercontent.com/assets/6396244/17748704/dbd47d2c-6477-11e6-83c2-b669ab5ec3bd.PNG)

Closing.

**Comment by arouinfar** [comment]
👍
