### ISSUE TITLE
Update artwork for Earth and satellite

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gravity-and-orbits#204]
New artwork was created for the satellite in https://github.com/phetsims/tasks/issues/436 which still needs to be added to the sim. 

We've also discussed replacing the image of the Earth, as it's pretty aliased. I've found a [higher quality image](http://apod.nasa.gov/apod/image/0304/bluemarble2k_big.jpg) from NASA that we can use to replace it. I believe our usage would be in accordance with NASA's [Media Usage Guidelines](http://www.nasa.gov/multimedia/guidelines/index.html) which states

> NASA content - images, audio, video, and computer files used in the rendition of 3-dimensional models, such as texture maps and polygon data in any format - generally are not copyrighted. You may use this material for educational or informational purposes, including photo collections, textbooks, public exhibits, computer graphical simulations and Internet Web pages. This general permission extends to personal Web pages.

I've cropped the original image so it can be placed in the sim.

<img src="https://cloud.githubusercontent.com/assets/8419308/17502432/026d542e-5da5-11e6-9b64-42052e577bc5.png" width="350">

I've emailed the asset files to @jessegreenberg for implementation.

**Comment by jessegreenberg** [comment]
Assets updated, they look awesome!  We should also update the screen icons as well with the new images.  The icons are also image assets.  @arouinfar would you be able to easily update the icons with the new images?  If not, I can draw new icons with scenery.

**Comment by arouinfar** [comment]
@jessegreenberg the screen icons were an easy fix. I've emailed updated assets to you for implementation.

<img src="https://cloud.githubusercontent.com/assets/8419308/17748305/f9c99404-6475-11e6-9b1d-42ef68e1041b.png" width="350">

<img src="https://cloud.githubusercontent.com/assets/8419308/17748306/f9efd1b4-6475-11e6-910b-b4d490fb2e26.png" width="350">

**Comment by arouinfar** [comment]
The new satellite artwork has poor contrast against the panel in projector mode. I'll need to find an alternative color. 

![image](https://cloud.githubusercontent.com/assets/8419308/17748890/b3a90542-6478-11e6-94cf-ac406cdb3f01.png)

**Comment by jessegreenberg** [comment]
Thanks @arouinfar I added the new screen icons.  Good point about the image contrast in projector mode.  Here is a dev version with the new images added if it helps.

http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.0.0-dev.25/gravity-and-orbits_en.html

**Comment by arouinfar** [comment]
For some reason, I can't get dev.25 to load and master still shows the old icon artwork, but I trust that it's good @jessegreenberg.

I think a less saturated blue (right) will improve the contrast between the satellite and panel.
<img width="513" alt="screen shot 2016-08-17 at 1 07 54 pm" src="https://cloud.githubusercontent.com/assets/8419308/17749616/a3cfa330-647b-11e6-94e2-0e4fecece2fc.png">

Can you update the panel color to #deeaff @jessegreenberg?

**Comment by jessegreenberg** [comment]
Sure @arouinfar.  I can't get dev.25 to load either.  dev.24 loads for me, and a local built version loads correctly so I will see if I can find the problem.

**Comment by jessegreenberg** [comment]
Not sure why it wasn't working before.  I redeployed and it is working fine.  Here is the version with all changes thus far, including the panel color:

http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.0.0-dev.25/gravity-and-orbits_en.html

**Comment by arouinfar** [comment]
Thanks @jessegreenberg! Looks good.
