### ISSUE TITLE
Make text on "Return Objects" button black

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gravity-and-orbits#205]
White text is a little hard to read against the light blue button.  @jessegreenberg can you please make the text black?

![image](https://cloud.githubusercontent.com/assets/8419308/17530124/6e685474-5e33-11e6-87c4-0e9fd8fc0a10.png)

**Comment by jessegreenberg** [comment]
Done in the commit above.  Button now looks like this:
![capture1](https://cloud.githubusercontent.com/assets/6396244/17744069/60df0ec0-6463-11e6-9c1d-a4f0d35aafd0.PNG)

And in projector mode:
![capture2](https://cloud.githubusercontent.com/assets/6396244/17744070/6236e572-6463-11e6-878e-6348ade37e06.PNG)

Closing, but @arouinfar feel free to review and reopen if you wish.
