### ISSUE TITLE
Planet trace does not move at same speed as planet

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/gravity-and-orbits#207]
I am not sure if this is a bug or if this is intentional.  It seems that the path trace for the planet will move at the speed of the planet when it was in that position in the trace, not at the current speed of the planet.  This can lead to some interesting cases.  One example is shown below.

![recording 18](https://cloud.githubusercontent.com/assets/6396244/17756425/fded26aa-649c-11e6-8346-4682617b7791.gif)

@arouinfar can you please verify that this is the desired behavior?

**Comment by arouinfar** [comment]
@jessegreenberg this does not look correct to me.

I also find it strange that the length of the trace seems proportional to the playback speed. (Sim refreshed between screenshots below.)

Slow Motion:
![image](https://cloud.githubusercontent.com/assets/8419308/17784791/0fedd5d6-653b-11e6-8ede-728380769592.png)

Normal: 
![image](https://cloud.githubusercontent.com/assets/8419308/17784820/2f6eddec-653b-11e6-97ff-d4eb45336e85.png)

Fast Forward:
![image](https://cloud.githubusercontent.com/assets/8419308/17784804/209e77e6-653b-11e6-820c-fbb9244b17f8.png)

I think a more reasonable approach would be to show the same maximum trace length at all playback speeds. I would prefer to show 100% of the orbit, but if there are pedagogical reasons not to, then perhaps 85% would do. What do you think @ariel-phet?

**Comment by ariel-phet** [comment]
@arouinfar I think 75-85% is probably the way to go. I am not sure if I would go so far as to say pedagogical, but I think the trace is easier to interpret when it fades away (such as in rutherford scattering). So I think it is a more appropriate visual effect if it gives the "this is where I came from idea. Especially since you can alter parameters real time as the trace is occurings.

**Comment by jessegreenberg** [comment]
With fast forward, it looks like the trace covers closer to 150%, which is noticeable when there are more than one orbiting bodies.  Arrow points to the end of the fading trace.

![capture](https://cloud.githubusercontent.com/assets/6396244/17819865/45064164-6607-11e6-9851-738427cddd07.PNG)

Is this a useful visualization?

**Comment by ariel-phet** [comment]
I guess this comes down to a question of learning goals - the overlapping trace could be thought of as useful for comparison, but I am guessing it will lead mainly to some confusion and clutter.

I think the trace is mainly there to suggest the general nature of the orbit (is it nearly circular, elliptical, wobbling like the moon), so I think something in the 75-85% range achieves this goal nicely, you don't have to remember the path the celestial object took.

**Comment by arouinfar** [comment]
> So I think it is a more appropriate visual effect if it gives the "this is where I came from idea". 

Good point @ariel-phet.  I think we want to keep the trace long enough to determine determine the shape of an orbit, and it looks like the trace at normal speed falls in the 75-85% range for each system.

<img src="https://cloud.githubusercontent.com/assets/8419308/17820376/c464f976-6609-11e6-93b9-90f72fb3b431.png", width="250px">  <img src = "https://cloud.githubusercontent.com/assets/8419308/17820453/2ff008f2-660a-11e6-9370-33fbef75679b.png" width="250px"> <img src="https://cloud.githubusercontent.com/assets/8419308/17820568/a93ac6b6-660a-11e6-8f07-cb95ddee9dff.png" width="250px">

@ariel-phet can you think of any reason why we wouldn't want the trace length to be constant across playback speeds? The variance of trace length can create some strange situations, like the one in @jessegreenberg original post.

**Comment by ariel-phet** [comment]
No, I think keeping the trace length consistent is a good idea.

**Comment by arouinfar** [comment]
@jessegreenberg can you set the maximum trace length to match the trace length at the default settings (as pictured in my previous comment)? The maximum trace length should not change with playback speed.

**Comment by jessegreenberg** [comment]
I am finding that all traces have the same number of points along the path ( 1314 ).  I am not sure why this is, but it means that the smaller path is very dense.

In addition, the path for the largest bodies are also using the same number of points for the trace path, so for the images in (https://github.com/phetsims/gravity-and-orbits/issues/207#issuecomment-241103098) 2628 paths are being drawn.

**Comment by jessegreenberg** [comment]
This should be fixed in the commit above.  The path length is now ~80% of the orbit for default conditions, and length is independent of play speed.  @arouinfar would you please review this in the latest dev version to make sure this is now correct?

http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.0.0-dev.27/gravity-and-orbits_en.html

I also expect these changes to assist with #162.

**Comment by arouinfar** [comment]
Looks great @jessegreenberg!

**Comment by phet-steele** [comment]
@jessegreenberg this is not consistent for different zoom levels. Zoomed in I get ~50% of the orbit, zoomed out I get ~150% of the orbit.

**Comment by jessegreenberg** [comment]
Orbit path length calculated from model coordinates, perhaps I forgot to transform for zoom.

**Comment by jessegreenberg** [comment]
In addition, when zoomed out, the path does not fade out at all.

**Comment by jessegreenberg** [comment]
> https://github.com/phetsims/gravity-and-orbits/issues/207#issuecomment-249997890

This should be fixed, but the fade out is still not as clean when zoomed all the way out.

**Comment by jessegreenberg** [comment]
```js
      // while ( this.path.length > this.maxPathLength ) {
        // this.path.shift();
        // this.pointRemovedEmitter.emit1( this.name );
      // }
```

This is the cause of this issue.  this.path.length is the length of an array.  this.maxPathLength is the length of the body's path in view coordinates.

**Comment by jessegreenberg** [comment]
Fixed in the above commit.

**Comment by brroberts1231** [comment]
Fixed, closing
