### ISSUE TITLE
Sim doesn't run on iPad2

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/gravity-and-orbits#208]
While working on #162, I tried to launch the sim to test tablet performance.  The sim doesn't launch in iPad2 with RequireJS or built versions.  After a few seconds I see 'A problem occured with this webpage so it was reloaded."  After it happens once more, Safari doesn't try to reload again.

**Comment by brroberts1231** [comment]
For phetsims/tasks#679, reproduced on Witten and Lave.

**Comment by jessegreenberg** [comment]
Thanks @brroberts1231!

**Comment by jessegreenberg** [comment]
I wonder if this is because mipmaps are so heavily used.  I ran into an issue like this with forces-and-motion-basics.

**Comment by jessegreenberg** [comment]
In ModeList, changing all  ```mipmaps``` to ```image``` indeed fixes this problem.  But twhy?

**Comment by jessegreenberg** [comment]
Sim runs consistently again on iPad2.  Closing.
