### ISSUE TITLE
Constrain planet drag bounds

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/gravity-and-orbits#212]
Planets can be dragged outside of the simulation bounds.  @arouinfar @phet-steele can you think of any reason to not restrict dragging to the bounds of the simulation?

You can return the object with 'Return Object' button if you accidentally or intentionally drag a planet off screen, but it seems like it would be better if planets could only be dragged to the bounds of the screen.

**Comment by arouinfar** [comment]
@jessegreenberg I don't see why it would be necessary/helpful to allow an object to be dragged out of bounds.

**Comment by jessegreenberg** [comment]
Thanks @arouinfar, done in commit above. Closing.
