### ISSUE TITLE
delete GravityAndOrbitsScreen

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gravity-and-orbits#216]
Noted while working on https://github.com/phetsims/joist/issues/339.

It looks like `GravityAndOrbitsScreen` is not used anywhere.  If that's the case, please delete it.

**Comment by jessegreenberg** [comment]
Done in the commit above, GravityAndOrbitsScreen was not used.  gravity-and-orbits-main was creating models and views directly making it larger than necessary.  The commit above distributes out into separate screens so that gravity-and-orbits-main.js is smaller and looks more like other sims.
