### ISSUE TITLE
Sim relies on translated string comparisons

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/gravity-and-orbits#221]
@phet-steele noticed this when in a string test, and it's due to the same cause as https://github.com/phetsims/pendulum-lab/issues/145

If stringTest=x is passed in and paths are enabled, paths can be drawn between the sun and planet:
![screen shot 2016-09-27 at 1 47 09 pm](https://cloud.githubusercontent.com/assets/480878/18889169/ed805396-84b8-11e6-99d5-42a42baf75e6.png)
this is because PathCanvasNode's namedPoints is indexed by body.name, which is the translated string for the body. So when two bodies have the same translated string, things go badly (data is overwritten).

Additionally, this line in GravityAndOrbitsPlayArea compares a translated string to the English value for a condition, which seems very suspect:
```js
// space station gets 1 sig fig, the other bodies have 0
significantFigures: ( bodies[ 1 ].name === 'Satellite' ) ? 1 : 0
```
presumably this will act completely differently in any non-English language, which does not appear to be the intention.

I'd encourage a full review of how translated strings are reviewed (particularly body.name), so that we can find/eliminate similar bugs. For phetsims/tasks/issues/692.

**Comment by jessegreenberg** [comment]
Thanks @jonathanolson and @phet-steele.

> I'd encourage a full review of how translated strings are reviewed (particularly body.name), so that we can find/eliminate similar bugs.

I am on it!

**Comment by jessegreenberg** [comment]
Done in the commits above, I gave a full review of the strings.  No model properties should be dependent on these any more.

**Comment by jessegreenberg** [comment]
Path looks good with string test = x.  Sim passes extensive fuzz test, and I verified all cases where the sim was referencing getting bodies with translatable string names.
![stringtextx](https://cloud.githubusercontent.com/assets/6396244/18896674/c64a59c0-84e0-11e6-92aa-610e43621cec.PNG)

**Comment by jessegreenberg** [comment]
Closing.
