### ISSUE TITLE
Satellite orbit measuring tape needs more sig figs

### ISSUE THREAD

**Issue by phet-steele** [phetsims/gravity-and-orbits#222]
@arouinfar we talked about this before, please comment if this is a change to go ahead with. The measuring tape in the satellite orbit does not give very useful information. The range at which the measuring tape displays the same number for distance is huge. Not to mention, it quickly goes to "0 thousand miles" well before reaching the distance from the Earth to the satellite's orbit.

<img width="1119" alt="screen shot 2016-09-27 at 1 49 47 pm" src="https://cloud.githubusercontent.com/assets/5863899/18889269/77e2da7c-84b9-11e6-9858-e4878e6a2305.png">

Seen on macOS 10.12 Chrome. For phetsims/tasks/issues/692.

**Comment by arouinfar** [comment]
@phet-steele good catch. This measuring tape is completely useless in this situation. I'd recommend adding one decimal place @jessegreenberg.

**Comment by jessegreenberg** [comment]
From a comment in the code, it looks like the satellite is supposed to have 1 sig fig while all other bodies should have 0.
>       // space station gets 1 sig fig, the other bodies have 0
    
From @phet-steele's screenshot above, a bug is preventing this from happening.  @arouinfar would you like all bodies to have an extra decimal place or just the satellite?

**Comment by arouinfar** [comment]
@jessegreenberg let's go with 1 decimal for the satellite, and none for the other bodies.

**Comment by jessegreenberg** [comment]
Sounds good, thanks @arouinfar.  This was fixed via
https://github.com/phetsims/gravity-and-orbits/commit/45d1ad0a7b0252a6ded00973359e4e9d22e7be44

![fixed](https://cloud.githubusercontent.com/assets/6396244/18934169/7e09c604-8595-11e6-9356-66e30ba18f1c.PNG)


Closing.
