### ISSUE TITLE
Bodies can display mass labels independent of the checked option

### ISSUE THREAD

**Issue by phet-steele** [phetsims/gravity-and-orbits#224]
1. To Scale screen, Earth+Satellite orbit is easiest. Keep the sim paused (again just easier).
2. Check "Mass".
3. Drag the bodies to collide them into each other. The Satellite should now be gone.
4. Uncheck "Mass".
5. Press the orbit refresh button

The Satellite will still display a mass label. The opposite procedure works, where step 2 has the Mass checked already. Uncheck at that step instead. I'm sure there are more problems that share a root cause, so this is probably just one symptom.

<img width="1397" alt="screen shot 2016-09-27 at 3 32 11 pm" src="https://cloud.githubusercontent.com/assets/5863899/18892673/9e12de5a-84c7-11e6-9331-6c8231ee3317.png">

Seen on macOS 10.12 Chrome. For phetsims/tasks#692.
URL: http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.0.0-dev.30/gravity-and-orbits_en.html
Version: 1.0.0-dev.30 2016-09-08 16:14:29 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36
Language: en-US
Window: 1920x961
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"cf925265","branch":"master"},"babel":{"sha":"da2eb7f1","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"chipper":{"sha":"5c755230","branch":"master"},"dot":{"sha":"23b13772","branch":"master"},"gravity-and-orbits":{"sha":"19a982e6","branch":"master"},"joist":{"sha":"c0442ba8","branch":"master"},"kite":{"sha":"3b656b9a","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"83ea84c8","branch":"master"},"scenery":{"sha":"cee9ad57","branch":"master"},"scenery-phet":{"sha":"799d6f8d","branch":"master"},"sherpa":{"sha":"cd023acf","branch":"master"},"sun":{"sha":"c22a4261","branch":"master"},"tandem":{"sha":"4a8edbc9","branch":"master"}}

**Comment by jessegreenberg** [comment]
Fixed in the commit above.

> I'm sure there are more problems that share a root cause, so this is probably just one symptom.

Yes!  The position of the label was also not being reset so if the mass changed, the label would also be in the wrong place in addition to being incorrectly visible.

**Comment by jessegreenberg** [comment]
I don't see a need to verify this fix, closing.
