### ISSUE TITLE
Consider adding labels to mass sliders

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gravity-and-orbits#226]
@phet-steele has made two suggestions to improve the mass sldiers
- Add the word "Mass" to the slider labels, so they would read "Planet Mass", "Satellite Mass", etc.
- Add labels to the unlabeled tick marks to provide a better sense of scale. 

I think these are good suggestions. The slider values are relative to the benchmark object, and the tick marks correspond to 50%, 100%, 150%, 200%. However, this is only apparent if "Mass" is turned on.  I think making the scaling a bit clearer would benefit qualitative exploration.

Here's a quick mockup of two variations of what the updated sliders could look like.
<img width="500" alt="screen shot 2016-09-28 at 10 45 07 am" src="https://cloud.githubusercontent.com/assets/8419308/18923177/a750648c-8568-11e6-88e7-8454ec500246.png">

@ariel-phet what do you think about these changes? Is this something you think would be worth doing?

**Comment by ariel-phet** [comment]
@arouinfar I think if we put the words in (Star and Planet), we should remove the icons. In the mockup there seems like now there is some competition between the word "Earth" and the icon. so I would say remove the icons.

I think I might also just put in numbers not percents (0.5, 1.5, 2.0) just seems simpler and cleaner to me

Thoughts?

**Comment by arouinfar** [comment]
@ariel-phet, great suggestion. I think decimal values are a much better way to go. I think the icons may be there to help cue younger students which object is the planet and which is the star. However, I don't think they are necessary. It certainly looks cleaner without the icons.

<img width="350" alt="screen shot 2016-09-28 at 11 33 25 am" src="https://cloud.githubusercontent.com/assets/8419308/18925021/7bc341b6-856f-11e6-8752-c85460393611.png">

**Comment by ariel-phet** [comment]
@arouinfar can we also try the icons to the left of the text (that might remove the competition between the icons and the words Earth/Sun)

**Comment by phet-steele** [comment]
@ariel-phet @arouinfar would it be bad to put a little "x" before every number so they read "x0.5" etc..?

**Comment by arouinfar** [comment]
@ariel-phet I think it looks cleaner with the icons to the left.
<img width="350" alt="screen shot 2016-09-28 at 12 32 56 pm" src="https://cloud.githubusercontent.com/assets/8419308/18927116/b5ecb298-8577-11e6-9875-47a6c4c0dda5.png">

@phet-steele, while I understand the motivation behind your suggestion, I think the "x" would be confusing to students. It probably wouldn't internationalize very well, either.

**Comment by ariel-phet** [comment]
@arouinfar Looks good to me

I might move the siders both down a few pixels (the tick labels are pretty tight to the titles), just a bit more negative space

**Comment by arouinfar** [comment]
Here's the updated mockup. @ariel-phet has given it the thumbs up, so it's all yours @jessegreenberg.

<img width="530" alt="screen shot 2016-09-29 at 1 22 49 pm" src="https://cloud.githubusercontent.com/assets/8419308/18968827/d7fc8040-8647-11e6-8296-54cab39c4225.png">

**Comment by jessegreenberg** [comment]
The current implementation in BodyMassControl uses HBoxes ad VBoxes to add ticks and labels to the slider.  This was likely done before HSlider supported labelled ticks.  BodyMassControl can be simplified a bit by using ticks and labels provided by HSlider.

**Comment by jessegreenberg** [comment]
@arouinfar should it be 'Satellite' or 'Space Station'?  When the mass labels are turned on, the small body is labelled in 'Space Station masses'.  The new artwork looks more like a satellite than the old image.

**Comment by jessegreenberg** [comment]
I see a mix of 'Satellite' and 'Space Station' in some of the documentation.  Is it important to use one vs the other?

**Comment by jessegreenberg** [comment]
Both terms are used for labels in the Java version as well.

**Comment by jessegreenberg** [comment]
Commits above should complete this, other than https://github.com/phetsims/gravity-and-orbits/issues/226#issuecomment-252761112

**Comment by arouinfar** [comment]
@jessegreenberg I do agree that the new satellite artwork does look less space station-y than the original satellite artwork. However, I think we should leave mass labels in terms of space station masses, since that is the benchmark object. The label above the slider should remain "Satellite" and the 2nd notch should be "Space Station".

**Comment by jessegreenberg** [comment]
Sounds good, thanks @arouinfar.  In that case, this will be ready for review in the next dev version.

**Comment by jessegreenberg** [comment]
Sorry @arouinfar I forgot to assign this to you in the latest dev test.  Can you review the new layout and close this issue if it looks good?

http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.0.0-dev.31/gravity-and-orbits_en.html

**Comment by arouinfar** [comment]
Looks great @jessegreenberg. Thanks!
