### ISSUE TITLE
Items to Include in the Teacher Tips

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gravity-and-orbits#228]
In addition to what's noted in the Tips for the Java version, we'll also need to clarify
- [x] Slider scales - #226
- [x] Gravity force vectors in the 3-body system are net gravitational forces (this is most noticeable on the Moon)
- [x] An object's velocity can be changed by dragging its velocity vector
- [x] Playback speed - #253 
- [x] ?projectorMode 
- [x] Perspective of Earth and Moon is different

**Comment by arouinfar** [comment]
Marking as on-hold until the sim is closer to publication.

**Comment by jessegreenberg** [comment]
Another potentially helpful item:  The sim includes the query parameter ?projectorMode so that the sim can be immediately loaded with projector colors.

**Comment by arouinfar** [comment]
Uploaded!
