### ISSUE TITLE
Zoom changes can push bodies

### ISSUE THREAD

**Issue by phet-steele** [phetsims/gravity-and-orbits#230]
Bodies can be pushed around by changing bounds (when zooming in/out) and changes their orbits. This seems problematic, and can happen when the sim is either running or paused. I've done custom setups that become ruined when zooming in. To demonstrate (not as a custom setup):

![gao02](https://cloud.githubusercontent.com/assets/5863899/18963146/f33bf898-8630-11e6-8f63-eab475ae2cdd.gif)

For example, I can destroy the Moon by simply changing my zoom level. Shouldn't the zoom only change what the user sees, but not actually move the bodies around?

![gao03](https://cloud.githubusercontent.com/assets/5863899/18963155/fab8e9be-8630-11e6-85c1-8bd9e3210a2c.gif)

Seen on macOS 10.12 Chrome. For phetsims/tasks#692.
URL: http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.0.0-dev.30/gravity-and-orbits_en.html
Version: 1.0.0-dev.30 2016-09-08 16:14:29 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36
Language: en-US
Window: 1920x961
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"cf925265","branch":"master"},"babel":{"sha":"da2eb7f1","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"chipper":{"sha":"5c755230","branch":"master"},"dot":{"sha":"23b13772","branch":"master"},"gravity-and-orbits":{"sha":"19a982e6","branch":"master"},"joist":{"sha":"c0442ba8","branch":"master"},"kite":{"sha":"3b656b9a","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"83ea84c8","branch":"master"},"scenery":{"sha":"cee9ad57","branch":"master"},"scenery-phet":{"sha":"799d6f8d","branch":"master"},"sherpa":{"sha":"cd023acf","branch":"master"},"sun":{"sha":"c22a4261","branch":"master"},"tandem":{"sha":"4a8edbc9","branch":"master"}}

**Comment by arouinfar** [comment]
> Shouldn't the zoom only change what the user sees, but not actually move the bodies around?

Yes, I would think so @phet-steele. However, if the zoom level causes an object to go off-screen, that object would need to be retrieved by the Return Objects button. Otherwise, I think things would get too complicated.

**Comment by jessegreenberg** [comment]
This is an accidental side effect of https://github.com/phetsims/gravity-and-orbits/commit/bd9b438aab86c93f90ff9d7962805e2c864b937a from #212.

**Comment by jessegreenberg** [comment]
The drag handler is also restricting the bounds of the planet when transform changes.  Once the workaround is discovered, we should determine if something should be changed in MovableDragHandler.

**Comment by jessegreenberg** [comment]
Sould be fixed in the commit above, but it would be nice to verify this in the next dev version.

**Comment by BryceAG** [comment]
This has been fixed for planets, but not for the tape measure in the scale section of the lab; the base will be dragged when zooming, but not the free end. This can result in the end of the tape measure being off screen and difficult to bring back on screen.

**Comment by jessegreenberg** [comment]
Nice catch @BryceAG, thanks.  It seems like the free end *should* get pushed off screen, otherwise the measured distance might change or be incorrect for the current zoom.  But, there is a weird bug where the length of the tape measure will grow indefinitely in certain cases.

I also notice that if the measure is on the edge of teh bounds when zooming in, the zooming action will force it to rotate.

**Comment by jessegreenberg** [comment]
If the measure is in the center of the area, the tape will grow with the transform as expected.  If the end of the measure is outside of transform bounds, it will grow very quickly.
![1](https://cloud.githubusercontent.com/assets/6396244/19787771/c2361c1e-9c61-11e6-914d-fc52cfed74a4.PNG)
![2](https://cloud.githubusercontent.com/assets/6396244/19787777/c59c7fec-9c61-11e6-80c3-f7adb39a6ea8.PNG)
![3](https://cloud.githubusercontent.com/assets/6396244/19787783/c7f172ca-9c61-11e6-870d-5ee6f6992fe5.PNG)
![4](https://cloud.githubusercontent.com/assets/6396244/19787784/c9d6f86c-9c61-11e6-936b-ca4a7f46565d.PNG)

**Comment by jessegreenberg** [comment]
Actually, it looks like in the bottom case, the length value property is also changing.

**Comment by jessegreenberg** [comment]
In this sim, the base is bounded to the drag bounds, but the tip is not.   We want the tip of the measure to extend outside of the drag bounds to follow the planets and conserve the measured value.

To restrict the bounds of the base, the basePositionProperty value is changing, and the tip value is staying the same, which is why the length grows very long.  When the base position changes to stay in the boundary, we want to subtract the difference from the position of the tip so that the measured distance remains the same.

This is a sim specific case, so it doesn't seem appropriate to modify the common MeasuringTape component.  In other cases, we might want to restrict the drag bounds of the tip, and there is already common support for that.

**Comment by jessegreenberg** [comment]
Should be fixed in the commit above, but should be reviewed since this is sort of a unique case.

**Comment by jessegreenberg** [comment]
@arouinfar and @phet-steele can you test the behavior of the tape measure in 
http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.0.0-dev.33/gravity-and-orbits_en.html and make sure that it is correct?

Specifically, I want to make sure that these assumptions are correct:
> In this sim, the base is bounded to the drag bounds, but the tip is not. We want the tip of the measure to extend outside of the drag bounds to follow the planets and conserve the measured value.

> When the base position changes to stay in the boundary, we want to subtract the difference from the position of the tip so that the measured distance remains the same.

**Comment by jessegreenberg** [comment]
Here is an example of what I mean.  The red line is the edge of dev and drag bounds.

Broken ( as in https://github.com/phetsims/gravity-and-orbits/issues/230#issuecomment-256787231):
![broken](https://cloud.githubusercontent.com/assets/6396244/19873644/cede4a3c-9f85-11e6-98d0-931086b02b1d.gif)

Fixed:
![fixed](https://cloud.githubusercontent.com/assets/6396244/19873647/d1a86b30-9f85-11e6-8fe7-edbafa51b058.gif)

**Comment by phet-steele** [comment]
I'm okay with how this behaves, thank you @jessegreenberg and @BryceAG.

**Comment by arouinfar** [comment]
Looks good to me too. Thanks!

**Comment by jessegreenberg** [comment]
Great, thanks @phet-steele @BryceAG and @arouinfar.  Closing this issue.
