### ISSUE TITLE
Explosions while paused

### ISSUE THREAD

**Issue by phet-steele** [phetsims/gravity-and-orbits#232]
The explosion animation behaves weirdly while the sim is paused. For instance, pausing the sim and dragging a body into another will begin an explosion; the explosion will only continue to progress if the user continues to "drag" the now destroyed object, otherwise if they release the body, the animation will pause. Furthermore, the image for a paused explosion does not scale or move while adjusting the zoom level, so one can start an explosion while zoomed way in and pause it (stop dragging). If they zoom back out, they've made an explosion bigger than the sun. @arouinfar I move to having the explosion animation progress regardless of the sim being played/paused.

The Moon is being obscured:
<img width="1547" alt="screen shot 2016-09-29 at 4 04 49 pm" src="https://cloud.githubusercontent.com/assets/5863899/18974137/82c10382-865e-11e6-9bd2-4003174f0366.png">

Seen on macOS 10.12 Chrome. For phetsims/tasks#692.
URL: http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.0.0-dev.30/gravity-and-orbits_en.html
Version: 1.0.0-dev.30 2016-09-08 16:14:29 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36
Language: en-US
Window: 1920x961
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"cf925265","branch":"master"},"babel":{"sha":"da2eb7f1","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"chipper":{"sha":"5c755230","branch":"master"},"dot":{"sha":"23b13772","branch":"master"},"gravity-and-orbits":{"sha":"19a982e6","branch":"master"},"joist":{"sha":"c0442ba8","branch":"master"},"kite":{"sha":"3b656b9a","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"83ea84c8","branch":"master"},"scenery":{"sha":"cee9ad57","branch":"master"},"scenery-phet":{"sha":"799d6f8d","branch":"master"},"sherpa":{"sha":"cd023acf","branch":"master"},"sun":{"sha":"c22a4261","branch":"master"},"tandem":{"sha":"4a8edbc9","branch":"master"}}

**Comment by arouinfar** [comment]
>  @arouinfar I move to having the explosion animation progress regardless of the sim being played/paused.

Sounds reasonable to me @phet-steele.

**Comment by jessegreenberg** [comment]
Done in the commit above, closing.
