### ISSUE TITLE
Paths drawn when manipulating bodies

### ISSUE THREAD

**Issue by phet-steele** [phetsims/gravity-and-orbits#233]
Probably not a huge deal but a little messy. When "Path" is enabled and a body becomes user controlled, a path is drawn between an objects start point and end point as a straight line. The video below shows how to do this when the sim is paused or when the sim is running. @arouinfar I would almost suggest that we limit the Path to only being drawn when a body is not user controlled, and erasing any previous path once a body is grabbed.

![gao04](https://cloud.githubusercontent.com/assets/5863899/18972564/ea88b242-8656-11e6-8b7a-6d3d870565f8.gif)

Seen on macOS 10.12 Chrome. For phetsims/tasks#692.
URL: http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.0.0-dev.30/gravity-and-orbits_en.html
Version: 1.0.0-dev.30 2016-09-08 16:14:29 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36
Language: en-US
Window: 1920x961
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"cf925265","branch":"master"},"babel":{"sha":"da2eb7f1","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"chipper":{"sha":"5c755230","branch":"master"},"dot":{"sha":"23b13772","branch":"master"},"gravity-and-orbits":{"sha":"19a982e6","branch":"master"},"joist":{"sha":"c0442ba8","branch":"master"},"kite":{"sha":"3b656b9a","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"83ea84c8","branch":"master"},"scenery":{"sha":"cee9ad57","branch":"master"},"scenery-phet":{"sha":"799d6f8d","branch":"master"},"sherpa":{"sha":"cd023acf","branch":"master"},"sun":{"sha":"c22a4261","branch":"master"},"tandem":{"sha":"4a8edbc9","branch":"master"}}

**Comment by arouinfar** [comment]
@phet-steele I don't particularly see how the paths in your .gif are at all useful to students.

> I would almost suggest that we limit the Path to only being drawn when a body is not user controlled, and erasing any previous path once a body is grabbed.

I would agree; so long as the bodies not being dragged by the user would still have the path drawn. Like the Earth in this situation

![path](https://cloud.githubusercontent.com/assets/8419308/19005135/28383daa-8716-11e6-9e36-2e75428e7c86.gif)

To recap:
* Previous paths are erased when an object is grabbed
* If an object is being dragged by the user, its path is not drawn (Sun's path would not be drawn when released like it is in the .gif above).
* Paths do not need to be drawn when the sim is paused and the objects are rearranged (like @phet-steele's .gif)

How does that sound @phet-steele?

**Comment by jessegreenberg** [comment]
> Previous paths are erased when an object is grabbed. In the example above, the Earth's path would start over once the Sun was dragged.

So in the gif of https://github.com/phetsims/gravity-and-orbits/issues/233#issuecomment-250840117 we would never see a path for as long as the sun is picked up for dragging?

**Comment by arouinfar** [comment]
@jessegreenberg say the Path option was on while the earth was orbiting the sun. Once the sun is picked up, that path clears. The Earth will create a new path (like the custom one in that .gif) but the Sun will not have any path because it is being directly manipulated by the user.  Does that make sense?

**Comment by phet-steele** [comment]
> Previous paths are erased when an object is grabbed. In the example above, the Earth's path would start over once the Sun was dragged.

@arouinfar, I don't think the Earth's path should **ever** be erased unless **IT** is the object being manipulated. I was imagining that the only paths being erased are the ones belonging to the manipulated body.

When I said:
> erasing any previous path once a body is grabbed.

I should have said "erasing any previous path *of the body being grabbed*. My bad there. In @arouinfar's above .gif, I think the Earth's path is actually a useful learning experience. Paths would only be rendered useless when they are effectively "tracing" a users movement, ie. dragging a body around.

**Comment by phet-steele** [comment]
> The Earth will create a new path

I see now where you were going with this @arouinfar, but I think retaining the non-controlled object's path is valuable.

**Comment by jessegreenberg** [comment]
@arouinfar I understand https://github.com/phetsims/gravity-and-orbits/issues/233#issuecomment-250874213, thanks for the extra example.

What do you think about @phet-steele's comments above?  I tend to agree that it seems valuable to keep the paths of other bodies while dragging an object.

**Comment by arouinfar** [comment]
@jessegreenberg, I just spoke to @phet-steele, and I agree that it would be valuable to retain the paths of the other bodies. I'll amend my comment above.

**Comment by jessegreenberg** [comment]
Thanks @arouinfar and @phet-steele, I'm on it.

**Comment by jessegreenberg** [comment]
Fixed in the above commit, but this would be good to verify in the next dev version.

**Comment by brroberts1231** [comment]
Fixed, closing.
