### ISSUE TITLE
Should 'Return Object' button appear after collision?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/gravity-and-orbits#235]
It seems like when a body collides with another body, there is no way to return it other then pressing 'Reset All'.  @arouinfar is this correct, or should there be a way to return the body after a collision?

**Comment by arouinfar** [comment]
@jessegreenberg I think we want to reserve the Return Object button for objects that escape off-screen. If an object is annihilated, I think it could be recovered using the Reset All or by using the reset button next to the selected system.

**Comment by jessegreenberg** [comment]
Thanks @arouinfar just wanted to make sure that it was considered.  I forgot about the 'reset system' button.
