### ISSUE TITLE
Should 'Return Object' reset day counter?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/gravity-and-orbits#236]
When an object is dragged while the sim is paused, the day counter is now reset (see #168).  When 'Return Object' button is pressed after a body leaves the play area, the simulation is paused.  At this point, should the day counter be reset?

> After dropping the object, the timer should be set to 0. In this case, we might expect that users are setting up an experiment by moving the sun/earth/etc. that they may want to repeat like in this situation. The sim is paused, the sun is moved, and then the sim is played.

It seems like this would also apply to the 'Return Object' button.  @arouinfar do you agree?

**Comment by arouinfar** [comment]
Agreed @jessegreenberg.

**Comment by jessegreenberg** [comment]
Thanks @arouinfar, done in the commit above. I found bug #237 while working on this, but this issue can be closed.
