### ISSUE TITLE
Paths are erased when changing zoom

### ISSUE THREAD

**Issue by brroberts1231** [phetsims/gravity-and-orbits#238]
Seen on Win 8, chrome. For phetsims/tasks#719.

When paths are shown and you zoom in or out, any previous paths will be erased and started again at the new positions of the bodies after you stop zooming. I'm not entirely sure if this is a bug or was an intended behavior, but prior to 1.0.0-dev.20, the paths were kept while zooming, which I think would be better. I couldn't find any issues referring directly to why this may have been changed. 

@jessegreenberg and @arouinfar agreed in #233 that 

>  it seems valuable to keep the paths of other bodies while dragging an object.

so, wouldn't it also be valuable to keep the paths of the objects when they aren't actually being moved, but the screen is just being zoomed? If you moved the sun around and ended up changing the earth's orbit to be a wide elliptical orbit, I think it would be nice to be able to zoom out to see the full orbit and not have its path be erased while doing so. 

Here's the current behavior in dev.31: 
![gao](https://cloud.githubusercontent.com/assets/11947677/19778327/74d84cbc-9c39-11e6-9fff-c5fe3d5e0622.gif)

And here's how it worked in dev.19:
![gao2](https://cloud.githubusercontent.com/assets/11947677/19778578/a6ccaa64-9c3a-11e6-8a30-6e8495d787ce.gif)

@phet-steele mentioned that a potential problem could be that the line width is thicker when you are more zoomed in on the old version, but I think it would still be valuable to try to retain the paths when zooming. 

Troubleshooting information (do not edit):
Name: ‪Gravity And Orbits‬
URL: http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.0.0-dev.31/gravity-and-orbits_en.html
Version: 1.0.0-dev.31 2016-10-26 19:43:33 UTC
Features missing: generatedcontent, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36
Language: en-US
Window: 1536x760
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"845be6b5","branch":"master"},"axon":{"sha":"bd3a64f4","branch":"master"},"babel":{"sha":"a106d6f8","branch":"master"},"brand":{"sha":"880a18de","branch":"master"},"chipper":{"sha":"bd3a1b56","branch":"master"},"dot":{"sha":"da3b5dd4","branch":"master"},"gravity-and-orbits":{"sha":"a4d6eb12","branch":"master"},"joist":{"sha":"f34eb9b6","branch":"master"},"kite":{"sha":"d506825f","branch":"master"},"phet-core":{"sha":"4222a05a","branch":"master"},"phetcommon":{"sha":"8df1bf7d","branch":"master"},"query-string-machine":{"sha":"438cfac1","branch":"master"},"scenery":{"sha":"60ae8f18","branch":"master"},"scenery-phet":{"sha":"7aa025e8","branch":"master"},"sherpa":{"sha":"83940ff7","branch":"master"},"sun":{"sha":"ad23b8e2","branch":"master"},"tandem":{"sha":"01cae1dc","branch":"master"}}

**Comment by arouinfar** [comment]
Good catch @brroberts1231. I think this is an unintended change. @jessegreenberg please leave paths intact while zooming.

**Comment by jessegreenberg** [comment]
@arouinfar, I can certainly add this in, but it is not an unintended change.  I think this was added as of dev.20 to match the Java version of the sim, which also removes the paths when the zoom changes.

Are you OK that this is a deviation from the Java?

**Comment by jessegreenberg** [comment]
Here is the code the handles this, placed in PathsNode when @aaronsamuel137 did the initial port.
```js
    transformProperty.link( function() {
      for ( i = 0; i < bodies.length; i++ ) {
        self.bodies[ i ].clearPath();
      }
    } );
```

**Comment by arouinfar** [comment]
@jessegreenberg I'm not worried about this being a variation from Java. I think it would be a nice touch, but I don't think it's worth putting significant time into. If you think this is a relatively straight-forward change, then I would recommend that we allow the paths to scale with the zoom. However, the stroke weight should remain a constant (this is contrary to dev.19 where zooming in creates a very thick stroke).

**Comment by jessegreenberg** [comment]
Sounds good @arouinfar I will take a look.  I agree with the comment about scaling the stroke.

**Comment by jessegreenberg** [comment]
Simply redacting ```clearPath``` creates this kind of thing:
![strange](https://cloud.githubusercontent.com/assets/6396244/19789155/92429ede-9c6a-11e6-941b-48bd9138a289.PNG)

**Comment by jessegreenberg** [comment]
Points are transformed as they enter they are added to an array in PathsCanvasNode.  To fix this we will need to clear the array in PathsCanvasNode, loop through the points in each body's path and transform them, and finally paint the canvas.

**Comment by arouinfar** [comment]
>  To fix this we will need to clear the array in PathsCanvasNode, loop through the points in each body's path and transform them, and finally paint the canvas.

That sounds expensive @jessegreenberg. Do you think performance would noticeably suffer?

**Comment by jessegreenberg** [comment]
The above commit should fix this.  @arouinfar I don't expect it to be too bad, but I will check a couple platforms.

**Comment by jessegreenberg** [comment]
Here is a version with this change.  I tried it out on an iPad2 and performance seems similar to the previous version.

http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.0.0-dev.32/gravity-and-orbits_en.html

@arouinfar could you please review the behavior and performance?

**Comment by jessegreenberg** [comment]
@phet-steele if you have access to devices, would you be able to compare performance (while zooming) between 
http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.0.0-dev.32/gravity-and-orbits_en.html

and 

http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.0.0-dev.31/gravity-and-orbits_en.html

**Comment by arouinfar** [comment]
@jessegreenberg looks good to me, but I think it would still be good for @phet-steele to compare the performance.

**Comment by brroberts1231** [comment]
Performance looks acceptable while zooming, closing

**Comment by jessegreenberg** [comment]
Thanks a lot for checking @brroberts1231.
