### ISSUE TITLE
Larger bodies do not have a path

### ISSUE THREAD

**Issue by BryceAG** [phetsims/gravity-and-orbits#239]
Test device:
Bates

Operating System:
Windows 7

Browser:
Chrome

Problem description:
Larger bodies do not have a path, such as the sun in the first two orbits, or the earth in the other two.

Steps to reproduce:
select paths and velocities, give the larger object a velocity

Severity:

Screenshots:
![image](https://cloud.githubusercontent.com/assets/15327201/19779671/5f2e9b68-9c3f-11e6-94ce-f4c247e32f48.png)

Troubleshooting information (do not edit):
Name: ‪Gravity And Orbits‬
URL: http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.0.0-dev.31/gravity-and-orbits_en.html
Version: 1.0.0-dev.31 2016-10-26 19:43:33 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36
Language: en-US
Window: 1366x662
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 10 uniform: 253
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"845be6b5","branch":"master"},"axon":{"sha":"bd3a64f4","branch":"master"},"babel":{"sha":"a106d6f8","branch":"master"},"brand":{"sha":"880a18de","branch":"master"},"chipper":{"sha":"bd3a1b56","branch":"master"},"dot":{"sha":"da3b5dd4","branch":"master"},"gravity-and-orbits":{"sha":"a4d6eb12","branch":"master"},"joist":{"sha":"f34eb9b6","branch":"master"},"kite":{"sha":"d506825f","branch":"master"},"phet-core":{"sha":"4222a05a","branch":"master"},"phetcommon":{"sha":"8df1bf7d","branch":"master"},"query-string-machine":{"sha":"438cfac1","branch":"master"},"scenery":{"sha":"60ae8f18","branch":"master"},"scenery-phet":{"sha":"7aa025e8","branch":"master"},"sherpa":{"sha":"83940ff7","branch":"master"},"sun":{"sha":"ad23b8e2","branch":"master"},"tandem":{"sha":"01cae1dc","branch":"master"}}

related to phetsims/tasks#719

**Comment by jessegreenberg** [comment]
Thanks for catching this, the larger bodies should have a path.

**Comment by jessegreenberg** [comment]
Paths are back!

![capture](https://cloud.githubusercontent.com/assets/6396244/19787201/c16a4542-9c5e-11e6-87f4-878c4690ce34.PNG)

closing.
