### ISSUE TITLE
Prepare screenshot icon

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/gravity-and-orbits#242]
This sim is almost ready for a release candidate.  @arouinfar can you give me an example image of what the sim icon should look like on the website?  I can create the actual icon from there.

**Comment by arouinfar** [comment]
@jessegreenberg let's go with something like this:
<img width="1156" alt="screen shot 2016-11-03 at 10 24 00 am" src="https://cloud.githubusercontent.com/assets/8419308/19974921/c5534d24-a1af-11e6-9329-cd4529d50d2c.png">

I  think we want the full path showing, but I don't have a strong opinion about where the Earth/Moon would be within the orbit.

**Comment by jessegreenberg** [comment]
Sounds good, thanks @arouinfar.  I will create a screenshot like the one above while the sim is in RC testing.

**Comment by jessegreenberg** [comment]
Here is the screenshot taken with an iPad3:

![screenshot-extended](https://cloud.githubusercontent.com/assets/6396244/20224193/77e91540-a7fa-11e6-822a-ee348609c829.png)

Does this seem OK @arouinfar?

**Comment by arouinfar** [comment]
Looks great @jessegreenberg!

**Comment by jessegreenberg** [comment]
Great thanks!  Closing this issue.
