### ISSUE TITLE
Zoom is setting state

### ISSUE THREAD

**Issue by phet-steele** [phetsims/gravity-and-orbits#246]
1. Set a state.
2. Let the sim run.
3. Pause the sim.
4. Don't touch any objects, just adjust the zoom.
5. You now have a new state. Let the sim run and press rewind to observe.

@arouinfar what do you think? Should zoom be affecting state? My vote is no, students may wish to view the same set up two times in a row at different zoom levels. Having your original set up potentially overwritten while zooming in/out would ruin that.

For phetsims/tasks/issues/728.

**Comment by arouinfar** [comment]
> @arouinfar what do you think? Should zoom be affecting state? 

I would also vote no @phet-steele.

**Comment by jessegreenberg** [comment]
Zoom is currently setting rewind values, which is interfering with #249.  This should be fixed before the others.

**Comment by jessegreenberg** [comment]
RewindableProperty was trying to determine when to store rewindable values internally.  I find this confusing and it is the reason for this issue.  I think it would be much more clear if the API were to explicitly define when values should be stored.  I am going to proceed with this but with caution because other places in the sim might have been relying on this 'invisible' setting of the rewind value.

**Comment by jessegreenberg** [comment]
Yes, pretty much everything other than position is counting on RewindableProperty setting the rewind value in this way.  But this is problematic because the transform property cannot be easily added to the derived property in body to prevent setting state when the zoom changes.

**Comment by jessegreenberg** [comment]
Hmm, unfortunately, it is the UI components don't have easy access to the mode either, so they can't easily save mode state when sim is paused.

**Comment by jessegreenberg** [comment]
The sliders, draggable arrows, and bodies would all have to be responsible for saving mode state.  Maybe it would be best to pass the zoom property to the Body from the mode, and let the RewindableProperty handle when the saving should happen.

**Comment by jessegreenberg** [comment]
Fix needs to be merged to the 1.0 branch.

**Comment by phet-steele** [comment]
Nice work @jessegreenberg.
