### ISSUE TITLE
Gravity force vector visibility saved with state

### ISSUE THREAD

**Issue by phet-steele** [phetsims/gravity-and-orbits#247]
1. Play the sim with Gravity Force vectors enabled
2. While playing, turn Gravity on/off
3. Pause the sim
4. Press rewind. Gravity force vectors will either be displayed or hidden, but will be opposite of the current on/off value of Gravity. For example, Gravity is off but force vectors are still on (until the sim is played):

![gao06](https://cloud.githubusercontent.com/assets/5863899/20278766/25c7e320-aa63-11e6-9024-d6414410a40b.gif)

Seen on macOS 10.12.1 Chrome. For phetsims/tasks/issues/728.

URL: http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.0.0-rc.1/gravity-and-orbits_en.html
Version: 1.0.0-rc.1 2016-11-11 00:38:23 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.87 Safari/537.36
Language: en-US
Window: 1921x1000
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"845be6b5","branch":"HEAD"},"axon":{"sha":"8353fe86","branch":"HEAD"},"babel":{"sha":"1294f048","branch":"master"},"brand":{"sha":"880a18de","branch":"HEAD"},"chipper":{"sha":"23f68a56","branch":"HEAD"},"dot":{"sha":"2765eb4d","branch":"HEAD"},"gravity-and-orbits":{"sha":"4d044323","branch":"HEAD"},"joist":{"sha":"76fd7b30","branch":"HEAD"},"kite":{"sha":"48cb255e","branch":"HEAD"},"phet-core":{"sha":"4222a05a","branch":"HEAD"},"phetcommon":{"sha":"2a68c3a8","branch":"HEAD"},"query-string-machine":{"sha":"13ba45df","branch":"HEAD"},"scenery":{"sha":"fb9d77c5","branch":"HEAD"},"scenery-phet":{"sha":"88fdc1dc","branch":"HEAD"},"sherpa":{"sha":"7a7b88b0","branch":"HEAD"},"sun":{"sha":"0e06f113","branch":"HEAD"},"tandem":{"sha":"005c5582","branch":"HEAD"}}

**Comment by jessegreenberg** [comment]
@phet-steele @arouinfar should gravity on/off state be saved?  It seems like if body mass is saved, gravity should be as well.

**Comment by phet-steele** [comment]
@jessegreenberg changing gravity on/off does set the state when the sim is paused. It seems only natural to restore it when rewind is pressed.

**Comment by jessegreenberg** [comment]
Thanks @phet-steele.  The commit above fixes the bug reported in the initial comment, but @arouinfar do you agree that gravity on/off setting should be restored when rewind is pressed?

**Comment by arouinfar** [comment]
Good catch @phet-steele!

> @arouinfar do you agree that gravity on/off setting should be restored when rewind is pressed?

Yes, I do @jessegreenberg.

**Comment by jessegreenberg** [comment]
Thanks! Ok, I will make the gravity setting rewindable.

**Comment by jessegreenberg** [comment]
@arouinfar @phet-steele on second thought, the gravity enabled setting applies to all orbits of the entire screen - I think it makes less sense now to make this rewindable.  This also means that it would take a bit of work to add this to the set of rewindable properties.  Are you OK with keeping it as is?

**Comment by arouinfar** [comment]
>Are you OK with keeping it as is?

@jessegreenberg given the complications, it seems fine to keep things as is, so long as the bug @phet-steele described is taken care of.

**Comment by jessegreenberg** [comment]
Sounds good, thanks @arouinfar.  Marking testing.

**Comment by phet-steele** [comment]
Looks great.
