### ISSUE TITLE
Rewind button stays enabled after affecting an object's mass

### ISSUE THREAD

**Issue by phet-steele** [phetsims/gravity-and-orbits#248]
Small bug:

1. Play the sim
2. While playing, change the mass of any/all objects.
3. Pause the sim
4. Press the rewind button. The sim will return to the earlier state, but the rewind button will still be enabled.

![gao05](https://cloud.githubusercontent.com/assets/5863899/20278472/23b37ea6-aa62-11e6-99e7-355e8129668f.gif)

Seen on macOS 10.12.1 Chrome. For phetsims/tasks/issues/728.

URL: http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.0.0-rc.1/gravity-and-orbits_en.html
Version: 1.0.0-rc.1 2016-11-11 00:38:23 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.87 Safari/537.36
Language: en-US
Window: 1921x1000
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"845be6b5","branch":"HEAD"},"axon":{"sha":"8353fe86","branch":"HEAD"},"babel":{"sha":"1294f048","branch":"master"},"brand":{"sha":"880a18de","branch":"HEAD"},"chipper":{"sha":"23f68a56","branch":"HEAD"},"dot":{"sha":"2765eb4d","branch":"HEAD"},"gravity-and-orbits":{"sha":"4d044323","branch":"HEAD"},"joist":{"sha":"76fd7b30","branch":"HEAD"},"kite":{"sha":"48cb255e","branch":"HEAD"},"phet-core":{"sha":"4222a05a","branch":"HEAD"},"phetcommon":{"sha":"2a68c3a8","branch":"HEAD"},"query-string-machine":{"sha":"13ba45df","branch":"HEAD"},"scenery":{"sha":"fb9d77c5","branch":"HEAD"},"scenery-phet":{"sha":"88fdc1dc","branch":"HEAD"},"sherpa":{"sha":"7a7b88b0","branch":"HEAD"},"sun":{"sha":"0e06f113","branch":"HEAD"},"tandem":{"sha":"005c5582","branch":"HEAD"}}

**Comment by jessegreenberg** [comment]
It looks like this is not necessarily related to the mass, this happens if position changes too.

**Comment by jessegreenberg** [comment]
It looks like there are several cases where the button is not disabled after rewind is pressed.

**Comment by jessegreenberg** [comment]
This is probably all caused by this:
```js
    // @public
    equalsRewindPoint: function() {
      return this.rewindValue === this.get();
    },
```

Comparing two unique objects like this will always return false unless vectors happen to be at initial values.

So we need an equality check for all types of rewindable properties?

**Comment by jessegreenberg** [comment]
Looks like that includes boolean number and Vector2.  So the above should be working for everything except position, velocity, and force.

**Comment by jessegreenberg** [comment]
Should be fixed above.

**Comment by jessegreenberg** [comment]
Not quite.  I would expect the rewind button to disable any time a rewindable property is not equal to its rewind value.  This is not always true.

**Comment by jessegreenberg** [comment]
Fixed above, re-adding label.

**Comment by phet-steele** [comment]
:+1:
