### ISSUE TITLE
Addendum to Return Objects button behaviour

### ISSUE THREAD

**Issue by phet-steele** [phetsims/gravity-and-orbits#249]
@jessegreenberg there is one behaviour of the Return Objects button that the Java does a bit better than the ported guy, and another behaviour of the ported guy that could be improved. (@arouinfar has approved of the change below). 

1. The Java sim does NOT check for an object's visibility while zooming in or out:

![gao7](https://cloud.githubusercontent.com/assets/5863899/20281268/125146a6-aa6d-11e6-921b-3a0ad85b5fbc.gif)

2. The HTML5 sim is very strict about showing the button if an object is not visible. If the location the object is returned to is *still* not within visible bounds, the button never goes away and looks broken:

![gao08](https://cloud.githubusercontent.com/assets/5863899/20281423/ab7d865a-aa6d-11e6-9297-99d11b3e005f.gif)

These could both be addressed by having two constraints on the Return Objects button that both must be fulfilled for it to be visible:

- A body must be out of visible bounds
- The same body must be in a location that is different from its "returned" location.

Expected changes to point 1: In the case of all objects being at their saved positions, zooming in/out would not present the Return Objects button on its own. This is not to say that zooming should NEVER check for the above conditions; the button should still show if objects are not at their saved location after moving outside the view bounds.

Expected changes to point 2: The button should be hidden after the first press, since it can only be the first press that returns an object. Once all objects are at their saved locations, what good does the Return Objects button have? Even though bodies may still not be visible, it would be up to the user to zoom out to see them. 

For phetsims/tasks/issues/728.

**Comment by jessegreenberg** [comment]
Done in the commit above, and I think that the fix handles the cases described in https://github.com/phetsims/gravity-and-orbits/issues/249#issue-189225100

**Comment by phet-steele** [comment]
Great work, thanks @jessegreenberg. I really like how all this behaves now.
