### ISSUE TITLE
Return Objects button can be sticky when zooming out

### ISSUE THREAD

**Issue by phet-steele** [phetsims/gravity-and-orbits#250]
1. Pause the sim with an object near the edge of the stage bounds.
2. Zooming in should make the the object leave your view in your setup. This prompts the Return Objects button to appear.
3. While zooming back out, the Return Objects should hide, but occasionally it does not. This happens more often with quick motions to zoom out.

End result is a visible Return Objects button even though all objects are within the stage bounds:

![gao09](https://cloud.githubusercontent.com/assets/5863899/20283006/710ca382-aa74-11e6-8008-ac5bafad00f8.gif)

Seen on macOS 10.12.1 Chrome. For phetsims/tasks#728.

URL: http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.0.0-rc.1/gravity-and-orbits_en.html
Version: 1.0.0-rc.1 2016-11-11 00:38:23 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.87 Safari/537.36
Language: en-US
Window: 1921x1000
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"845be6b5","branch":"HEAD"},"axon":{"sha":"8353fe86","branch":"HEAD"},"babel":{"sha":"1294f048","branch":"master"},"brand":{"sha":"880a18de","branch":"HEAD"},"chipper":{"sha":"23f68a56","branch":"HEAD"},"dot":{"sha":"2765eb4d","branch":"HEAD"},"gravity-and-orbits":{"sha":"4d044323","branch":"HEAD"},"joist":{"sha":"76fd7b30","branch":"HEAD"},"kite":{"sha":"48cb255e","branch":"HEAD"},"phet-core":{"sha":"4222a05a","branch":"HEAD"},"phetcommon":{"sha":"2a68c3a8","branch":"HEAD"},"query-string-machine":{"sha":"13ba45df","branch":"HEAD"},"scenery":{"sha":"fb9d77c5","branch":"HEAD"},"scenery-phet":{"sha":"88fdc1dc","branch":"HEAD"},"sherpa":{"sha":"7a7b88b0","branch":"HEAD"},"sun":{"sha":"0e06f113","branch":"HEAD"},"tandem":{"sha":"005c5582","branch":"HEAD"}}

**Comment by jessegreenberg** [comment]
Fixed in the above commits.

**Comment by phet-steele** [comment]
Working, thanks @jessegreenberg.
