### ISSUE TITLE
Velocity saved state is incomplete

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gravity-and-orbits#252]
Found during https://github.com/phetsims/tasks/issues/728

If a new state is saved by dragging the velocity vector while paused, not all information will be saved.

To reproduce:
1. Turn on path & velocity
2. Press play
3. Adjust star and/or planet mass
4. Pause the sim
5. Drag velocity vector
6. Press play
7. Press rewind. Velocity has been saved, but masses and object location revert.

Here's a screencapture:
![velocity](https://cloud.githubusercontent.com/assets/8419308/20291177/be6f690c-aaa1-11e6-8a8b-3faf0c34ff3f.gif)

@jessegreenberg in this situation, the object masses and locations should also be saved with state; not just the velocity vector.

**Comment by jessegreenberg** [comment]
Yes they should, thanks @arouinfar.

**Comment by jessegreenberg** [comment]
Fixed in above commit.

**Comment by phet-steele** [comment]
Fantastic!
