### ISSUE TITLE
Picture of earth should show the pole (probably north pole)

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/gravity-and-orbits#255]
@arouinfar my apologies on this...I just saw an unfuddle ticket (not sure how this got missed before)

In the unfuddle ticket:

> The simulator shows the moon orbiting over the poles, which is completely wrong: it orbits roughly over the equator, more precisely on a plane that makes a 5 degree angle with the ecliptic. The way you show the moon, there wood be no tides at all during certain times of the month, because the moon would be over the poles. By the way: the strongest tides take place precisely when the moon is most faraway from the eqautor, during at the equinoxes.

This should be a pretty easy fix for a maintenance release, but we will need to find an appropriate picture (with the same licensing as the current picture, I imagine it is creative commons, but would be good to check with @jessegreenberg)

**Comment by arouinfar** [comment]
@ariel-phet the image is from NASA, which we are free to use. I will search for a replacement image that is centered on one of the poles.

**Comment by arouinfar** [comment]
What about this @ariel-phet?

http://visibleearth.nasa.gov/view.php?id=56236
<img width="696" alt="screen shot 2016-11-29 at 10 10 40 am" src="https://cloud.githubusercontent.com/assets/8419308/20720377/1c0d065c-b61c-11e6-9296-c2ed63506e73.png">

**Comment by ariel-phet** [comment]
@arouinfar that works for me...obviously we will want to crop out just the earth, but otherwise looks good.

**Comment by arouinfar** [comment]
@ariel-phet I suspected that you'd be fine with the image, so I was working on cropping.
<img src="https://cloud.githubusercontent.com/assets/8419308/20721474/1bc09aac-b620-11e6-8bc3-df4a4002eab1.png" width=400>


@jessegreenberg here are two updated .png files. The resolution of earth_lowres.png matches the dimensions of the earth.png file that's checked into this repo.
[earth_highres.png](https://cloud.githubusercontent.com/assets/8419308/20721359/c74e1f08-b61f-11e6-8aa2-4bdebfe319e6.png)
[earth_lowres.png](https://cloud.githubusercontent.com/assets/8419308/20721360/c74e782c-b61f-11e6-93ae-066aa20dabd2.png)

**Comment by arouinfar** [comment]
@jessegreenberg the new image is from NASA.

I edited the <a href="http://eoimages.gsfc.nasa.gov/images/imagerecords/56000/56236/np_layered_day.tif">np_layered_day.tif</a> image from this page:
http://visibleearth.nasa.gov/view.php?id=56236

**Comment by jessegreenberg** [comment]
@arouinfar, thanks for the low res image!  here it is in the sim:

http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.1.0-dev.1/gravity-and-orbits_en.html

Do we need to update the "To Scale" screen icon as well to match the new earth?

**Comment by arouinfar** [comment]
Looks great @jessegreenberg! I think we should update both screen icons because they contain the old earth image.

**Comment by jessegreenberg** [comment]
@arouinfar I am pretty clumsy with image editing, would you mind updating the icons and sending them to me like in https://github.com/phetsims/gravity-and-orbits/issues/204?

**Comment by arouinfar** [comment]
Oh, I'd forgotten that I'd made the original icons. Thanks @jessegreenberg, I'll update the artwork and send it your way.

**Comment by arouinfar** [comment]
@jessegreenberg I've updated the asset files. However, it appears the .ai file I have for the earth is ridiculously large (not sure how to make it smaller), so I've temporarily stored the new screen icon assets on Drive for you to download.
https://drive.google.com/drive/folders/0BwZJWzOg9l4DWmlTUS14MmM4d2s?usp=sharing

**Comment by jessegreenberg** [comment]
Thanks @arouinfar!  I updated the icons in the sim and added files to assets.
![capture](https://cloud.githubusercontent.com/assets/6396244/20771838/5ff847ae-b708-11e6-9609-e6d983dd9826.PNG)

Closing.
