### ISSUE TITLE
Velocity vector color in play area is different than velocity vector icon

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/gravity-and-orbits#256]
@arouinfar I am a little surprised @phet-steele never asked this....

Why is the color of the velocity vector in the play area different from the color of the velocity vector icon in the control panel? Shouldn't these be the same color?

![arrow](https://cloud.githubusercontent.com/assets/4051174/20697805/6d156ab6-b5b9-11e6-8154-e0573349721a.PNG)

Perhaps when we fix #255 we should make this change as well (I imagine it is pretty much a one line change)

**Comment by arouinfar** [comment]
Good catch @ariel-phet, both velocity vectors should have the same color, colorblind red.

**Comment by jessegreenberg** [comment]
![capture](https://cloud.githubusercontent.com/assets/6396244/20768606/c435a07a-b6fb-11e6-9d44-3f6092cfff7c.PNG)
![capture2](https://cloud.githubusercontent.com/assets/6396244/20768610/c5418920-b6fb-11e6-8250-a68c103af19b.PNG)

Good catch!  Done in the commit above.  Closing.
