### ISSUE TITLE
Add AP to credits

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/gravity-and-orbits#257]
@jessegreenberg I should probably be in the "team" section of the credits when we do a maintenance release

**Comment by arouinfar** [comment]
While we're on the topic of credits, I believe we should also acknowledge MLL in the "Thanks to" section.

**Comment by ariel-phet** [comment]
@arouinfar true

**Comment by jessegreenberg** [comment]
![capture](https://cloud.githubusercontent.com/assets/6396244/20768163/177c13f6-b6fa-11e6-82f8-6dc32e37eaad.PNG)

I added AP to credits, alphabetized the names and added the 'Thanks' section for MLL.

**Comment by jessegreenberg** [comment]
Thanks @arouinfar, closing.
