### ISSUE TITLE
Tweaks to Planet and Body Mass Sliders....

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/gravity-and-orbits#259]
I hate to be THAT guy, but while we are making some tweaks I was noticing that the Sliders for planet and body mass in the sim have the information a bit cramped to each other, making them a bit harder to visually pars (notice how Moon Mass is quite close vertically to the top slider):

![slider1](https://cloud.githubusercontent.com/assets/4051174/20769611/fa4a3d48-b6ff-11e6-873c-a7659045e111.PNG)

I was thinking we could tweak a little like so:

![gao slider](https://cloud.githubusercontent.com/assets/4051174/20769650/13df24d0-b700-11e6-908e-6b7f9302f0f5.PNG)

Here I did the following:
- reduce the length of the tick marks slightly (a few pixels)
- moved the tick labels down accordingly
- separated the two slider groups a bit more vertically

See what you think @arouinfar and @jessegreenberg

**Comment by arouinfar** [comment]
@ariel-phet I suppose now is the best time to be "THAT guy" :)

I think the updated sliders look much cleaner. Thanks for mocking it up @ariel-phet.

**Comment by jessegreenberg** [comment]
@ariel-phet what do you think of this spacing?

http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.1.0-dev.2/gravity-and-orbits_en.html

**Comment by ariel-phet** [comment]
Did some more polishing with @jessegreenberg over skype, looking great!

**Comment by jessegreenberg** [comment]
Commit above contains changes made with @ariel-phet.  Closing!
