### ISSUE TITLE
User reported issue: synchronous rotation of moon

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/gravity-and-orbits#261]
> Dear
> 
> I love your animations!
> But I noticed a mistake in the animation https://phet.colorado.edu/en/simulation/gravity-and-orbits
> when I set it to Earth and Moon.
> In the animation, Moon does not rotate. It just revolves around Earth. Notice that in a revolution, Moon shows all its "faces" to Earth, what actually does not happen. 
> Remember there is a "hidden" or "Dark side of the moon" (not dark at all) and we always see the same face of it.
> So the animation should shows the same part of the Moon always facing Earth. The same to satellite. If it gives its back to us, we lost the communication.
> 
> Thank you for your attention

**Comment by ariel-phet** [comment]
@jessegreenberg this user is correct...the moon's rotational period should match its orbital period. 

My guess is that there is nothing in the model to rotate the moon (or a satellite). This really only is necessary on the "model" screen since neither the image of the moon or satellite are particularly visible on the "to scale" screen.

Can you give an estimate of what it would take to implement this functionality? Since this does incorrectly depict the orbital nature of the moon, it would be good to fix sooner than later.

**Comment by jessegreenberg** [comment]
Yes I can take a look at this today.

**Comment by jessegreenberg** [comment]
There is currently nothing in the model that implement body rotation.  @ariel-phet I estimate about 1 hour to implement rotation for the bodies.  We will definitely want to hand the sim off to the QA team though when we are done, so they can test that the changes work well with save/rewind feature in this sim.

**Comment by jessegreenberg** [comment]
Which bodies should rotate?  Just the moon and satelite in the "Model" screen and the satelite in the "To Scale" screen?

**Comment by jessegreenberg** [comment]
Regarding https://github.com/phetsims/gravity-and-orbits/issues/261#issuecomment-278180672, a full RC is probably overkill unless we want to pull in master SHAs anway.

**Comment by jessegreenberg** [comment]
The above commit adds support for body rotation and applies it to the moon in the Model screen.

**Comment by jessegreenberg** [comment]
Done for the Moon and Satellite in the "Model" view, and the Satellite in the "To Scale" view since these bodies are big enough to see the rotation.

**Comment by jessegreenberg** [comment]
By about 3000 earth minutes, rotation of the satellite begins to be incorrect, its orbital period needs to be more accurate.

**Comment by jessegreenberg** [comment]
The above commit improves it quite a bit, sim ran fast forward for 50 minutes (~81000 earth minutes) and the rotation looked good.

**Comment by jessegreenberg** [comment]
@ariel-phet @arouinfar could you please review the rotation behavior in this version?

http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.1.0-dev.3/gravity-and-orbits_en.html

The moon will rotate in the Earth + Moon system, and the satellite will rotate in both.

**Comment by jessegreenberg** [comment]
Other bodies could rotate, but these were the only that seemed big enough to notice, unless we want the Earth to spin as well.

**Comment by ariel-phet** [comment]
The satellite rotation looks awesome! The moon looks good too to my eye, nice work!

**Comment by arouinfar** [comment]
Looks awesome @jessegreenberg!

**Comment by jessegreenberg** [comment]
Thanks @ariel-phet and @arouinfar I will prepare an RC with these changes.

**Comment by phet-steele** [comment]
Also agree it looks good. Assigning to @oliver-phet to email after release.

**Comment by oliver-phet** [comment]
@jessegreenberg Is this in the queue for publication?

**Comment by jessegreenberg** [comment]
It is, https://github.com/phetsims/tasks/issues/783 is finished up and the sim is ready for redeploy, I will do so this afternoon.

**Comment by jessegreenberg** [comment]
@oliver-phet gravity-and-orbits has been redeployed!

https://phet.colorado.edu/sims/html/gravity-and-orbits/latest/gravity-and-orbits_en.html

**Comment by oliver-phet** [comment]
User notified. Closing!
