### ISSUE TITLE
Replace PropertySet with Property

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/gravity-and-orbits#263]
From phetsims/axon#102, PropertySet is deprecated and should be replaced with Property.

**Comment by jessegreenberg** [comment]
@mbarlow12, this issue and phetsims/forces-and-motion-basics#226 are some of the last sims that need to go through this.  Ill work on FAMB, would you please tackle this one?

**Comment by jessegreenberg** [comment]
I see 4 usages of PropertySet.call, but the structure of this sim is a little strange, let me know if you have any questions.

**Comment by mbarlow12** [comment]
Will do.

**Comment by mbarlow12** [comment]
Closing.
