### ISSUE TITLE
User suggestion: satellite velocity

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/gravity-and-orbits#264]
> "I used your updated sim. Great job. I suggest adding a slider control for the velocity of the satellites. Currently, the best work around is to freeze the sim, click and drag the velocity vector, then start the sim again. A slider control would allow this to happen without the pause, and then the orbit trail can be seen to show the changed radius of orbit with the new speed. In a similar theme , maybe you could have an option to add additional moons, each with a differing speed, but I suppose it could get complicated with several moons, but this is like jupiter. Maybe one of the scene options could be a planet like Jupiter with several moons in different orbits.
Thanks"

**Comment by oliver-phet** [comment]
This was submitted from our google form

**Comment by oliver-phet** [comment]
Assigning to @arouinfar a to decide if this is worth pursuing, delegate, and prioritize.

**Comment by arouinfar** [comment]
>A slider control would allow this to happen without the pause, and then the orbit trail can be seen to show the changed radius of orbit with the new speed.

I suspect the user's goal is to demonstrate that larger orbits have a slower orbital speed (and vice versa). A speed slider would not be sufficient to support this goal. The speed slider would control the magnitude of the velocity, but without also moving the satellite accordingly, the satellite would either crash into the Earth or escape. The satellite wouldn't automatically readjust its position to occupy an orbit with an appropriately smaller/larger radius. 

> maybe you could have an option to add additional moons, each with a differing speed, but I suppose it could get complicated with several moons, but this is like jupiter. Maybe one of the scene options could be a planet like Jupiter with several moons in different orbits.

This is beyond the scope of Gravity and Orbits, but perhaps the user could try using My Solar System instead, which allows up to four bodies. One of the presets could be modified to have the initial conditions appropriate for a body + 3 moons.

Back to you @oliver-phet.

**Comment by oliver-phet** [comment]
Reply to user sent. Closing.
