### ISSUE TITLE
transparent rectangle behind the measuring tape readout?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gravity-and-orbits#266]
https://github.com/phetsims/scenery-phet/issues/339 added a new feature to MeasuringTapeNode, an optional transparent rectangle behind the readout.  It sure looks like gravity-and-orbits might want to take advantage of this feature:

![screenshot_405](https://user-images.githubusercontent.com/3046552/31145807-03e9ff08-a842-11e7-8e44-e4bc5d6f53ee.png)

**Comment by pixelzoom** [comment]
Much better, `'rgba( 0, 0, 0, 0.65 )'`, screenshot below.  @arouinfar please review, feel free to close if it looks OK.

![screenshot_406](https://user-images.githubusercontent.com/3046552/31151178-88b1022a-a853-11e7-852f-73d0f2eff697.png)

**Comment by arouinfar** [comment]
Looks great, thanks!

**Comment by samreid** [comment]
This implementation led to problems for projector mode, see https://github.com/phetsims/gravity-and-orbits/issues/329

**Comment by samreid** [comment]
Fixed in the commits.

@pixelzoom is the documentation correct, or should it use something like `PaintDef`?

**Comment by pixelzoom** [comment]
Type expression in MeasuringTapeNode should be `{ColorDef}`, done in the above commit.

**Comment by samreid** [comment]
Thanks, closing.
