### ISSUE TITLE
branch: pdomTransform

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/gravity-and-orbits#272]
To explore https://github.com/phetsims/scenery/issues/852.

**Comment by jessegreenberg** [comment]
https://phet-dev.colorado.edu/html/gravity-and-orbits/1.2.0-pdomTransform.1/phet/gravity-and-orbits_en_phet.html?mobileA11yTest&accessibility

**Comment by samreid** [comment]
In discussion today, @jessegreenberg said this branch can be deleted because master already supports this.
