### ISSUE TITLE
Use title case in sim name

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gravity-and-orbits#273]
Related to https://github.com/phetsims/tasks/issues/953

The sim title is improperly cased, and currently reads "Gravity **And** Orbits"

`gravity-and-orbits.title` in <a href="https://github.com/phetsims/gravity-and-orbits/blob/master/gravity-and-orbits-strings_en.json#L2">gravity-and-orbits-strings_en.json</a>  should be updated to "Gravity and Orbits" next time this sim gets worked on.

**Comment by samreid** [comment]
Fixed in master and will go out with next release, closing.
