### ISSUE TITLE
Zoom slider buttons off

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-and-orbits#274]
Found when exploring https://github.com/phetsims/QA/issues/209 with @jessegreenberg.  Appears on iOS 10 and Win 10 at least.

The + and - buttons that should be on either end of the zoom slider are instead translated down and to the right.  This is the case on both screens.
![zoombutton](https://user-images.githubusercontent.com/41024075/47743772-6c24b800-dc45-11e8-9988-2b7854f23fb5.PNG)

**Comment by jessegreenberg** [comment]
Thanks for making an issue @KatieWoe - this commit and related changes in sun seem like the most likely cause https://github.com/phetsims/gravity-and-orbits/commit/d99eea00f5d7c08f2848abeedccae349ec2db9af

**Comment by jessegreenberg** [comment]
Fixed in the above commit.
