### ISSUE TITLE
Slight ResetAllButton repositioning

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/gravity-and-orbits#277]
The ResetAllButton in this sim could use slight repositioning. With the dilated touch area the right side is slightly close to the dev bounds, would be good to move it left a bit

![gravitytouch](https://user-images.githubusercontent.com/4051174/51954933-4e5f1e80-23ff-11e9-907a-21d517db5fbf.PNG)

**Comment by samreid** [comment]
Fixed in the preceding commit:

![image](https://user-images.githubusercontent.com/679486/66954034-d6806500-f01c-11e9-8372-5f45c2b2ee43.png)

Can you please review, @ariel-phet?  Close if all is well.

**Comment by ariel-phet** [comment]
Looks good. Closing
