### ISSUE TITLE
Regression test after gravitational constant change

### ISSUE THREAD

**Issue by zepumph** [phetsims/gravity-and-orbits#279]
In https://github.com/phetsims/gravity-force-lab-basics/issues/123#issuecomment-487738577 we factored out the gravitational constant to PhysicalConstants.js. @jessegreenberg please make sure that nothing has changed for this sim because of https://github.com/phetsims/gravity-and-orbits/commit/02d389ec47ca66fe87b8a6b147f59756169be8c7

**Comment by jessegreenberg** [comment]
Thanks @zepumph, I tested master vs the published sim and I couldn't see any differences. @ariel-phet the published version of this sim had the gravitational constant slightly incorrect. It was changed from 6.67428E-11 to 6.67408E-11. Would you like to test this change any further?

**Comment by ariel-phet** [comment]
@jessegreenberg no I think that testing is sufficient. Such a small change should not affect anything major, and your testing appears to confirm this. Closing
