### ISSUE TITLE
sim title is improperly cased

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gravity-and-orbits#280]
As pointed out by @arouinfar in https://github.com/phetsims/charges-and-fields/issues/165#issuecomment-511915777, the title of this sim should be "Gravity and Orbits".   It is currently "Gravity And Orbits".

> The HTML5 version of Gravity and Orbits is also improperly cased, so if we decide to fix this sim, we should do the same for GAO.

**Comment by arouinfar** [comment]
This has already been reported in #273, so closing.
