### ISSUE TITLE
Improve performance and smoothness

### ISSUE THREAD

**Issue by samreid** [phetsims/gravity-and-orbits#286]
In https://github.com/phetsims/gravity-and-orbits/issues/281#issuecomment-544684595 @ariel-phet said:

> If we were going to invest time in improvements, I would be much more inclined to improve performance (to me, in the published version, the sim still runs just a bit chunky, as if garbage collections are occurring). If there are some ways to improve that performance without major changes, that would be a better use of time in my opinion.

I wasn't sure whether this is the same as the issue reported in https://github.com/phetsims/gravity-and-orbits/issues/162 which seemed like it eventually focused on a single long pause in firefox.

@ariel-phet can you please report what hardware and browser you are running, and quantify the performance problem you are seeing?  Does the severity of the problem differ on different browsers?

**Comment by ariel-phet** [comment]
@samreid I was seeing the somewhat stuttering behavior on Win 7 Chrome. I have not done a thorough comparison of platforms. I just wonder if given the age of this sim there are some performance improvements to be had that are low hanging fruit (things we have learned since then).

We could have QA take a brief look at some point to see if performance issues are platform specific. I think having various options on (vectors, values, path, etc) makes things more obvious.

**Comment by samreid** [comment]
QA characterized the performance across a range of platforms in https://github.com/phetsims/QA/issues/443#issuecomment-545496827.  @ariel-phet can you please help identify which platforms we should focus on, what target performance we would like to shoot for as part of our next publication, and how much time should be allocated for it?

**Comment by ariel-phet** [comment]
@samreid I think we should focus on just two platforms, I think if you make some headway on these two, it will probably be good enough:

1. Windows 7 Chrome
2. ChromeOS

The goal should not really be FPS but more eliminating "stutters" in the orbit. It looks like ChromeOS does drop in FPS sometimes, so maybe that would be a quantifiable place to start. 

I would say lets start in the 8 hour range. Mainly I am wondering if there is some low hanging fruit in terms of modern practices for performance. So basically spend a day trying to improve performance. Let's see what that buys us. Feel free to ask @jonathanolson for some suggestions after you do a couple hours of investigation.

**Comment by samreid** [comment]
Summarizing the results from https://github.com/phetsims/QA/issues/443#issuecomment-545496827 for the requested platforms:

Windows 7 Chrome has subjective performance "Decent. Some lag" and 55-60fps.
ChromeOS has subjective performance "Ok. Some lag" and 50-60fps but does dip much lower.

**Comment by samreid** [comment]
I've been unable to profile using Chrome 79.0.3945.130 on MacOS 10.15.1 for several days, receiving a problem like this:

![image](https://user-images.githubusercontent.com/679486/73278176-70bd8080-41a8-11ea-867e-5d633291e613.png)

**Comment by samreid** [comment]
I was able to use Chrome Canary for performance profiling.  I'm seeing 32% time taken in "Update Layer Tree", 9% in "setAttribute" and 5% in "watchedBoundsScan".  Here's everything that takes 1% or more self-time from "bottom up" view:

![image](https://user-images.githubusercontent.com/679486/73323731-9c228880-4205-11ea-88d8-5c13bac3c4aa.png)

@ariel-phet most of these are related to scenery or browser costs, would it be possible to have @jonathanolson take a look?

**Comment by ariel-phet** [comment]
@samreid yes, feel free to have @jonathanolson take a look with you, but only briefly (a couple of hours).

We have dropped windows 7 support, so really ChromeOS would be the question mark now. Looking on Win 10 chrome, things just don't seem quite as smooth as I would expect still. However, this sim has been out in the public for a LONG time without any complaints, so if after a couple hours we haven't gotten anywhere in terms of moving towards smoother orbit motion, it is probably not worth more effort currently.

**Comment by samreid** [comment]
@jonathanolson and I took a quick look at the performance profile on MacOS Chrome Canary today, and didn't see any obvious problems.  We will schedule to meet on Thursday with a Chromebook.  @KatieWoe can you please let us know if/how we can check out a Chromebook on Thursday for investigation here?  I'm not sure which device was used in https://github.com/phetsims/QA/issues/443#issuecomment-545496827, nor am I sure we would need the same device.

**Comment by KatieWoe** [comment]
Just let me know. If you're taking it for more than a day sign it out on the assets inventory. Probably Lovelace was used, and it is the most up to date.

**Comment by jonathanolson** [comment]
Really dug into this with @samreid! It looks like we have a fixed-timestep physics model underneath, and we are properly using EventTimer to keep the time consistent, BUT we are not interpolating the display between the previous and next state (leading to jittery-ness, where one frame it might not run a physics step and would stay in the same position, and the next it could run two physics steps and jump far).

This doesn't look related to GCs or other performance, although those may contribute (GCs seemed fast-ish on the Chromebook, although we did see some random style recalculation that was significant, that might also contribute to jitter occasionally).

**Comment by samreid** [comment]
The above commit blends the view coordinates using the interpolation ratio from the EventTimer.  @jonathanolson you indicated this should be done in the model, but it made sense to me to implement in the view as we had done for Wave Interference.  Can you please take a look and advise?

Even after this change, I'm still seeing non-smooth motion on my MBP.  It seems we can save around 1% CPU if we left-align instead of center align the "days" readout.  We could probably save another 1% if we check the center of the planet node rather than its entire `bounds` to determine whether it should be marked as offscreen (to show the return button).  @ariel-phet do you want to make either of those design changes in attempt to improve performance?

**Comment by jonathanolson** [comment]
> @jonathanolson you indicated this should be done in the model, but it made sense to me to implement in the view as we had done for Wave Interference. Can you please take a look and advise?

Above commit looks good. The "blend in the model" was only if you were storing the blended state in the model. Since it happens in the BodyNode, having that in the view seems perfect!

> Even after this change, I'm still seeing non-smooth motion on my MBP.

Improved at all?

**Comment by samreid** [comment]
Performance in a built version seems roughly the same to me.

**Comment by ariel-phet** [comment]
@samreid no need to make either of the design changes mentioned in https://github.com/phetsims/gravity-and-orbits/issues/286#issuecomment-583225134

It seems you and @jonathanolson have given some effort to this issue and made a potential improvement, I think it can be closed now.

**Comment by samreid** [comment]
Understood, thanks, closing.

**Comment by samreid** [comment]
This caused a bug in #303, and since it is not a measurable improvement, I'm planning to roll it back.

**Comment by samreid** [comment]
Rolled back, remaining closed.
