### ISSUE TITLE
It takes 700 days to go around the sun once

### ISSUE THREAD

**Issue by samreid** [phetsims/gravity-and-orbits#292]
During https://github.com/phetsims/gravity-and-orbits/issues/284, I noticed it's taking way too long for the earth to go around the sun.   This is not buggy in the published version.  This will block publication.

**Comment by samreid** [comment]
Tagging @kathy-phet, @arouinfar and @ariel-phet so they are aware of this problem.

**Comment by kathy-phet** [comment]
Hi Sam, Could this be related to your dt changes to correct the difference in the outcomes for running in slow versus fast motion? I don't recall the ticket number.

**Comment by samreid** [comment]
It's possible, I'll investigate there first.

**Comment by samreid** [comment]
I committed a proposed fix and tested a few scenes and playback speeds.  It seems better now.  Still, I'd like QA to take a closer look at testing time, so I'll leave this issue open until then.

**Comment by samreid** [comment]
I tested this again and am more confident that it is OK, or at least will be caught during regular design or RC testing.  Closing.
