### ISSUE TITLE
Use TimeControlNode for Play/Pause/Step buttons 

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/gravity-and-orbits#294]
From phetsims/scenery-phet#561. A scenery-phet/TimeControlNode was created that combines the PlayPauseButton and StepForwardButton and includes PhET-iO and PDOM instrumentation. It should be used in this sim. Assigning to responsible dev.

**Comment by samreid** [comment]
It is unclear how to combine the RewindButton with the TimeControlNode.  It seems suboptimal to place the RewindButton next to the TimeControlNode--it seems like the RewindButton should be a child of the TimeControlNode.  @jessegreenberg can you please advise how to proceed?

**Comment by jessegreenberg** [comment]
It seems useful to me to add a RewindButton to TimeControlNode, Ill do that.

**Comment by jessegreenberg** [comment]
I began to add the RewindButton to the TimeControlNode but this sim needs access to it or a way to set it enabled/disabled based on sim specific Properties/logic which adds some complexity.

**Comment by jessegreenberg** [comment]
Im not sure what is best, I opened https://github.com/phetsims/scenery-phet/issues/574 to get feedback from original authors.

**Comment by samreid** [comment]
Now tracked in https://github.com/phetsims/scenery-phet/issues/575.  Until that's resolved, we should probably use the decorator pattern by placing the RewindButton next to the TImeControlNode.

**Comment by kathy-phet** [comment]
@samreid - This seems like it should also move forward before delivery to client to at least get parts of this on TimeControlNode.

**Comment by kathy-phet** [comment]
Also, we don't understand why each scene has a "TimeControlPanel" because if we interact with play/pause, its current state is effects all scenes in the same way. That is the scene doesn't remember the state of its own play/pause button. They would each need a unique rewind button because that is stateful for each scene.

**Comment by samreid** [comment]
After the commits, there is one TimeControlPanel per screen (not per scene), and it uses TimeControlNode.  After https://github.com/phetsims/scenery-phet/issues/575 is in master, we can take further steps in that direction which will clean up the studio tree.

**Comment by samreid** [comment]
I noticed the review completed, but the TimeControlNode changes are still in the branch, going back on hold.

**Comment by samreid** [comment]
@jessegreenberg did most of the work, and I took additional steps to improve the tandems for Gravity and Orbits.  @arouinfar can you please review?

**Comment by jessegreenberg** [comment]
Thanks @samreid, was going to report back here that this was done. Looks like you have already seen GravityAndOrbitsTimeContorlNode, let me know if more needs to be done regarding TimeControlNode.

**Comment by kathy-phet** [comment]
We reviewed TimeControlNode, and it is looking a lot better in Studio. It's great to have just one per screen. A few issues came up that need to be addressed, so sending this back to you @samreid: 

- [ ] The StepBackwardButton name is wrong. It should be stepForwardButton. Is this a bug in common code or this sim? gravityAndOrbits.modelScreen.view.timeControlNode.playPauseStepButtons.stepBackwardButton
it should be gravityAndOrbits.modelScreen.view.timeControlNode.playPauseStepButtons.stepForwardButton

- [ ] Can you confirm that restartButton is not part of the common code, but just layered in to make it visually look like it goes with the sim. We think it looks good in the tree.

- [ ] The speedRadioButtonGroup has a duplicate level (2 of this same name). Can you remove one? 
gravityAndOrbits.modelScreen.view.timeControlNode.speedRadioButtonGroup.speedRadioButtonGroup.normal

- [ ] Can you please implement the feature defaults for vertical aqua buttons: 
https://github.com/phetsims/sun/issues/564

- [ ] Can you please implement the feature defaults for TimeControlNode: 
https://github.com/phetsims/scenery-phet/issues/577

- [ ] Making Enbled=false dims the controls a lot, making them hard to see. It looks like it it is setting things to about 30% opacity. We would recommend 50%. Can you look at the defaults here? 
![image](https://user-images.githubusercontent.com/5096804/76984137-0dc4ac00-6904-11ea-8b8c-bf8d06d5d157.png)

**Comment by kathy-phet** [comment]
If some of the above small issues belong over in 
https://github.com/phetsims/scenery-phet/issues/575
can you move them? Or link the issues if you just make the changes. Thx!

**Comment by samreid** [comment]
> The StepBackwardButton name is wrong. It should be stepForwardButton. Is this a bug in common code or this sim?

Good catch!  I corrected this in the commits.

> Can you confirm that restartButton is not part of the common code, but just layered in to make it visually look like it goes with the sim. We think it looks good in the tree.

Yes, it was interleaved manually and I agree it worked out well.

> The speedRadioButtonGroup has a duplicate level (2 of this same name). Can you remove one? 
gravityAndOrbits.modelScreen.view.timeControlNode.speedRadioButtonGroup.speedRadioButtonGroup.normal

Fixed, thanks!

> Can you please implement the feature defaults for vertical aqua buttons: 
https://github.com/phetsims/sun/issues/564

Implemented in that issue, let's discuss there.

> Can you please implement the feature defaults for TimeControlNode: 
https://github.com/phetsims/scenery-phet/issues/577

Implemented in that issue, let's discuss there.

> Making Enbled=false dims the controls a lot, making them hard to see. It looks like it it is setting things to about 30% opacity. We would recommend 50%. Can you look at the defaults here? 

I opened https://github.com/phetsims/sun/issues/578 and addressed it there. @zepumph can you please review the implementation side here?  Many changes were common code changes.  @arouinfar or @kathy-phet can you please review the phet-io design changes?

**Comment by arouinfar** [comment]
@samreid this is all looking good to me. Since remaining work is being tracked separately, I'll go ahead and close.
