### ISSUE TITLE
Add derived properties to the model for the data stream

### ISSUE THREAD

**Issue by samreid** [phetsims/gravity-and-orbits#295]
From #293:

> - [ ] For saving data out of the simulation, we would like to create several new properties that would be natural data that you would want as an instructional designer having students save or plot data: 
1. a "forceMagnitudeProperty" for each body and perhaps a "forceDirectionProperty" (in degrees where 0 is horizontal to the right and conventions as in "Vector Addition")
2. a "velocityMagnitudeProperty" for each body and perhaps a "velocityDirectionProperty"
3. a "planetMoonDistanceProperty" at the scene level for each pair of bodies in that scene. e.g. 
gravityAndOrbits.modelScreen.model.planetMoonScene.planetMoonDistanceProperty
We understand these can be "calculated" from properties that already exist, but since these are the data you would want to have students collect as an instructional designer I think we should do the work in the sim and not ask each client to do it in the wrappers.

**Comment by samreid** [comment]
For context, the existing force properties already output in x,y form like so:

```json
{
  "index": 351,
  "time": 1580305147137,
  "type": "MODEL",
  "phetioID": "gravityAndOrbits.modelScreen.model.starPlanetScene.star.forceProperty",
  "name": "changed",
  "componentType": "PropertyIO<Vector2IO>",
  "data": {
    "oldValue": {
      "x": 3.738068478314458e+26,
      "y": 0
    },
    "newValue": {
      "x": 3.738066754101029e+26,
      "y": 3.638178548568346e+23
    }
  },
  "metadata": {
    "units": "N"
  }
}
```

It won't be very hard to add these new proposed derived Properties for the data stream, but I wanted to verify that we are on the same page about them before I proceed.  If I recall correctly, we have made contrasting decisions as a team.  One principle we have settled on as a team is:

* For the data stream, clarity is more valuable than conciseness, even when we duplicate information.  We discussed this in the context of "frontloading" schema data in https://github.com/phetsims/phet-io/issues/1400 and decided we preferred verbosity

On the other hand, I thought we had also decided that the responsibility for these "trivially derivable" attributed belonged with the wrapper.  I can't find a paper trail for it, but I recall a wrapper where we demonstrated how this should be accomplished.

I'm inclined to recommend that this responsibility lies with the wrapper, to keep the simulation side implementation simple, and because not all clients will want this additional data.  And the clients that do want this additional data, it is trivial to compute.  That being said, implementing it in the simulation side is a good way for us to guarantee that it is factored out and standardized (say, so it has the units and values we want, like -180 degrees to 180 degrees).

Anyways, I'm happy to proceed either way, but just wanted to make sure we were on the same page regarding policy for this pattern, for this case and future cases.

Tagging @pixelzoom @zepumph and @chrisklus since I vaguely recall they was involved with this discussion before.  Then once we discuss it, we can bring it back to @kathy-phet and @arouinfar.

**Comment by pixelzoom** [comment]
I don't recall a discussion about whether this responsibility belongs in the sim or in the wrapper. 

What I can say is that putting PhET-iO-only features (like these DerivedProperties) in the sim creates a QA dilemma.   How will those features be verifies? In this case, these DerivedProperties will not be exercised by the sim proper, and will therefore not be tested when running the sim in CT or otherwise. How will you verify (and continue to verify as part of QA) that they are correct?

**Comment by kathy-phet** [comment]
For some simulations, like this one, a benefit we expect clients to take advantage of is the ability to pull more quantitative data from the simulation. I do not want to ask every client to have to build their own quantitative data creator for the natural quantities you would want to collect to show common relationships from a sim like this one. 

I agree that we will want QA to have access to these derived properties for checks. Can we have a dev query parameter that displays them on the screen for sanity checking?

**Comment by samreid** [comment]
Can the QA team use the readouts in studio or in the data stream?

**Comment by samreid** [comment]
In the above commits, I added:

* `forceMagnitudeProperty`
* `speedProperty` -- seemed a better name than `velocityMagnitudeProperty`
* pairs and a `distanceProperty` for each pair.  I did this instead of flat values like `planetMoonDistanceProperty` in case we want to add other pairwise quantities in the future.

I didn't add the direction properties, since their importance was unclear ("perhaps" mentioned several times in the issue description), but I'm happy to add them if they should be added.

@arouinfar and @kathy-phet would you like to review and discuss?

**Comment by kathy-phet** [comment]
We discussed, and we like the structure and feel we can defer any directionProperties until we get client input that that is needed. They can calculate it from the vector. 

@arouinfar will check the veracity of the values in the model to make sure they match reality (with the exception of the Model screen earth-moon distance).

**Comment by arouinfar** [comment]
I checked the `massProperty`, `diameterProperty`, `speedProperty`, `forceMagnitudeProperty`, and the pair-wise `distanceProperty` on the To Scale screen for all bodies. For the most part things are looking good, but I did notice some discrepancies for the satellite (defaults should match the International Space Station).

| Property | satellite default | [ISS](https://www.nasa.gov/feature/facts-and-figures) | 
| --- | --- | --- | 
| mass | 369914 kg | 419725 kg | 
| diameter | 218000 m | 73m x 109m |

`satellite.diamterProperty` is way off the mark, but I'm not sure if it's actually used for anything in the model. A more reasonable value would probably be the average of the length/width which would be 91 m. Likewise, `satellite.massProperty` is off by a fair amount, so we should probably update that as well.

Back to @samreid to update these values on both screens.

**Comment by samreid** [comment]
I moved the prior comment to a new issue, and based on feedback in preceding comments, it sounds like this issue is ready to close.
