### ISSUE TITLE
isMovableProperty is creating bugs in the sim

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/gravity-and-orbits#298]
@arouinfar and @kathy-phet found some odd behavior when experimenting with the isMovableProperty of objects. Two observed behaviors (not consistent behavior): 
- isMovableProperty was set to "false" but @arouinfar was still able to move it. 
- we also saw a situation where you would click on the moon when it was "isMoveable=false" and the moon would not move but its velocity would and it would get out of sync (see red arrow disconnect from moon). 
![image](https://user-images.githubusercontent.com/5096804/74173811-09fc8600-4bf0-11ea-816e-cebfa8db535e.png)
@samreid - Can you try to track down this bug?

We can definitely see clients wanting to set the moon or other objects as not pickable, but we don't know if the model property "isMoveable" is the best way to be making this choice. Maybe "isMoveable" should be read-only and we should use moonNode.PickableProperty to do that. One of these should listen to the other one. It seems like the "PickableProperty" would be the more natural for instructional designers to toggle if they didn't want students messing with the location of a body/object.

**Comment by kathy-phet** [comment]
Also, you said in https://github.com/phetsims/gravity-and-orbits/issues/293 that the sun's isMoveableProperty is false, but in the published sim it moves and in the phettest sim it moves, so we are also confused about this.

**Comment by samreid** [comment]
@arouinfar said this problem could be reproduced without using studio to change `isMovableProperty`

**Comment by samreid** [comment]
It seems the bodies get away from the mouse, that may be the root of the problem.

**Comment by samreid** [comment]
I discovered the true meaning of `isMovableProperty` is whether the body can be moved by the physics during the step function.  I updated the documentation.  @arouinfar or @kathy-phet  should we also give it a different name?  What else do you recommend for this issue?

**Comment by arouinfar** [comment]
Reviewed with @kathy-phet. The updated documentation looks fine, but we think all `isMoveableProperty`s should be `phetioReadOnly: true`.

**Comment by samreid** [comment]
I set `isMovableProperty` to `phetioReadOnly: true`.  Anything else for this issue?  Please close if all is well.

**Comment by arouinfar** [comment]
Looks good in master. Thanks @samreid.
