### ISSUE TITLE
Several properties should be phetioHighFrequency: true

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gravity-and-orbits#299]
Related to #293 and #295

There are several properties that should be phetioHighFrequency: true.

For each screen/scene:
- [x] clock.timeProperty (e.g. `gravityAndOrbits.modelScreen.model.planetMoonScene.clock.timeProperty`)

For each screen/scene/body:
- [x] forceProperty (e.g. `gravityAndOrbits.modelScreen.model.planetMoonScene.moon.forceProperty`)
- [x] forceMagnitudeProperty 
- [x] positionProperty
- [x] rotationProperty
- [x] speedProperty
- [x] velocityProperty

For each screen/scene/pair:
- [x] distanceProperty (e.g. `gravityAndOrbits.modelScreen.model.planetMoonScene.planetMoonPair.distanceProperty`)

**Comment by samreid** [comment]
Fixed in the commit, @arouinfar can you please review?

**Comment by arouinfar** [comment]
Looks good in studio @samreid. Thanks!
