### ISSUE TITLE
Improvements for isRunningProperty and isPlayingProperty

### ISSUE THREAD

**Issue by samreid** [phetsims/gravity-and-orbits#300]
From https://github.com/phetsims/gravity-and-orbits/issues/293

@kathy-phet said:

> Regarding, isRunningProperty and isPlayingProperty, we would like to have documentation on both of these. Suggestion:
> isRunningProperty = "This value is true when [INSERT SCENE NAME] is the active scene AND the sim is playing (isPlayingProperty is 'true')."
> isPlayingProperty = "This value is true [SCREEN] is the active screen AND the play/pause button is in play mode."
> NOTE: We are a bit confused about how these Properties should change when you change screens. There do not seem to be any messages logged to the console when you change screens?

**Comment by samreid** [comment]
@pixelzoom replied:

@kathy-phet Regarding your descriptions in the previous comment.... 
> isRunningProperty = "This value is true when [INSERT SCENE NAME] is the active scene AND the sim is playing (isPlayingProperty is 'true')."
> isPlayingProperty = "This value is true [SCREEN] is the active screen AND the play/pause button is in play mode."

I just examined GAO in the debugger.  I see no change to isPlayingProperty when a screen becomes inactive.  And isRunningProperty is also therefore unaffected by whether the screen is active.

**Comment by samreid** [comment]
@pixelzoom continued:

Here's what I see in GAO for these 2 Properties:

* `isPlayingProperty` applies to a screen's model, and is true if the play/pause button for the screen is in the "play" mode.

* `isRunningProperty` applies to a scene, and is true if the scene is selected and `isPlayingProperty` is true for the model that the scene belongs to.

Switching between screens results in no change to either Property.

**Comment by samreid** [comment]
I added the changes @kathy-phet recommended.  @pixelzoom is correct in what he commented about the Properties, and I would add that it is a common pattern in our sims that the selected screen acts as a "filter" for `step` events, and we do not track that information with sim-specific Properties or data.

**Comment by kathy-phet** [comment]
Yes @pixelzoom - I saw what you saw ... 

> NOTE: We are a bit confused about how these Properties should change when you change screens. There do not seem to be any messages logged to the console when you change screens?

However, what I didn't understand was should it change when you change screens? What controls the clock from proceeding. isRunningProperty for instance seems to control the clock for each scene, but I observe that if I change screens, the clock does stop on the other screen, and picks back up where I left it when I switched back. 

I just want to know if this is the intention for how isRunningProperty was supposed to work. If so, what do we combine with "isRunningProperty" to know that it is not actually "running". What does the sim use to do that?

**Comment by samreid** [comment]
In discussion, we clarified that time only flows to a screen when that screen is selected.  And each screen will often keep track of its own "is running" parameters, which only operate if the screen is selected and the browser tab is active.  Back to @kathy-phet to see if there are refinements to make.

**Comment by kathy-phet** [comment]
@arouinfar @samreid - Can you review these suggestions - this is not easy to explain: 

gravityAndOrbits.modelScreen.model.isPlayingProperty
This value is true if the play/pause button on this screen is in play mode. (It remains true even if the user switches screens. Use in combination with 'gravityAndOrbits.general.model.screenProperty'.)

gravityAndOrbits.modelScreen.model.planetMoonScene.clock.isRunningProperty
This value is true when 'gravityAndOrbits.modelScreen.model.planetMoonScene' is the selected scene and the play/pause button is in play mode. (It remains true even if the user switches screens. Use in combination with 'gravityAndOrbits.general.model.screenProperty'.)

**Comment by arouinfar** [comment]
@kathy-phet the recommended documentation looks good to me.

**Comment by samreid** [comment]
I added both new docs, @arouinfar can you please review?

**Comment by arouinfar** [comment]
Looks good in master, thanks @samreid
