### ISSUE TITLE
Instrument the measuring tape node

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/gravity-and-orbits#301]
This to-do was left over from #293. The measuringTapeCheckbox is instrumented, but the MeasuringTapeNode itself does not appear to be instrumented.

See also this related issue about new features - derived properties - for measuring tape node: 
https://github.com/phetsims/phet-io/issues/1596

Assigning to @samreid

**Comment by samreid** [comment]
In the latest version, it looks like the measuring tape node is instrumented:

![image](https://user-images.githubusercontent.com/679486/76175303-a07d8200-6171-11ea-9e5e-ffa0482423ef.png)

Leaving self-assigned as a reminder about https://github.com/phetsims/phet-io/issues/1596

**Comment by arouinfar** [comment]
@samreid when reviewing https://github.com/phetsims/phet-io/issues/1596, I noticed that the measuringTapeNode is appearing in the tree for the Model screen. However, there isn't a measuringTapeNode on this screen, so it should be removed. 

For example:
![image](https://user-images.githubusercontent.com/8419308/77033433-dd652800-696c-11ea-869a-3226bac56264.png)

**Comment by samreid** [comment]
After the commit, we are only creating the MeasuringTape on the "To Scale" screen.  Anything else for this issue?

**Comment by arouinfar** [comment]
Looks good in master @samreid, thanks!
