### ISSUE TITLE
Reset all button does not properly reset objects

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-and-orbits#305]
**Test device**
Dell or iPad
**Operating System**
Win 10 or iPadOS 13
**Browser**
Chrome or Safari
**Problem description**
Found during https://github.com/phetsims/chipper/issues/878, but seems unrelated to that change.
When you hit reset all there is a chance that the objects won't return to their proper place and won't be in the place they appear to be. Dragging them around can be difficult to impossible and things can collide even if they don't appear to. Results can be inconsistent, so you may need a few tries. Seems to occur on and screen or scene.
**Steps to reproduce**
1. Go to a chosen scene
2. Play the sim and then pause the sim again
3. Hit reset all
4. Drag things around, pause, play, and reset

**Visuals**
![resetallproblem](https://user-images.githubusercontent.com/41024075/74879514-8ac12d80-5326-11ea-9c7f-032eaa36fd40.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Gravity and Orbits‬
URL: http://phettest.colorado.edu/gravity-and-orbits/gravity-and-orbits_en.html?ea&brand=phet
Version: 1.2.0-dev.7 (require.js)
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by samreid** [comment]
It looks like this was introduced by #286 and fixed when that was reverted.  @KatieWoe can you please test?

**Comment by KatieWoe** [comment]
Looks good on master
