### ISSUE TITLE
The GravityAndOrbitsScene constructor is out of control

### ISSUE THREAD

**Issue by samreid** [phetsims/gravity-and-orbits#308]
It looks like this, with a record of 21 required parameters.

```
  constructor( forceScale, active, dt, timeFormatter, iconImage,
               velocityVectorScale, massReadoutFactory, initialMeasuringTapeLocation,
               defaultZoomScale, zoomOffset, gridSpacing, gridCenter, model, radioButtonTandemName, resetButtonTandemName,
               tandemName, massControlPanelTandemName, tandem, sceneViewTandem, bodies, pairs ) {
```

Also related to #306

**Comment by samreid** [comment]
We are down to a dozen, that seems reasonable, closing.

**Comment by samreid** [comment]
On second thought, @arouinfar can you please review master and make sure behavior for the different scenes hasn't changed?  This was a medium complexity refactoring and it would be nice to confirm nothing was disturbed.

**Comment by arouinfar** [comment]
@samreid I don't exactly know what things I should be looking for here, but what I did was compare the behavior of master and latest for one full orbit for each scene/screen with the vectors, grid, and path on. The only visual difference I noted was the diameter of the orbits on the Model screen and the moon's velocity vector on the star/planet/moon scene, but my guess is that the changes are likely related to #302.

| Master | Latest |
| --- | --- | 
| <img src="https://user-images.githubusercontent.com/8419308/76796753-ba325100-6791-11ea-97cb-7dabcf0a4209.png" width=300> | <img src="https://user-images.githubusercontent.com/8419308/76796764-c1595f00-6791-11ea-9f70-519da2044c36.png" width = 300> |
| <img src="https://user-images.githubusercontent.com/8419308/76796784-c9190380-6791-11ea-9ca0-11aa17e644b2.png" width=300> | <img src="https://user-images.githubusercontent.com/8419308/76797241-b2bf7780-6792-11ea-9d87-7b4aad01e198.png" width=300> |
|  <img src="https://user-images.githubusercontent.com/8419308/76796815-d7671f80-6791-11ea-89b1-c05ea8cee329.png" width=300> | <img src="https://user-images.githubusercontent.com/8419308/76796820-ddf59700-6791-11ea-8fe6-591e2a02a5ac.png" width=300> |
|  <img src="https://user-images.githubusercontent.com/8419308/76796831-e4840e80-6791-11ea-90f5-40cb1b2f87a5.png" width=300> | <img src="https://user-images.githubusercontent.com/8419308/76796843-e9e15900-6791-11ea-886e-14668b6a7314.png" width=300> |

**Comment by samreid** [comment]
Thanks!  It seems this can be closed.  I agree those differences were most likely due to #302.
