### ISSUE TITLE
Should the sim display "1 Earth Days"?

### ISSUE THREAD

**Issue by samreid** [phetsims/gravity-and-orbits#310]
The simulation is capable of showing "1 Earth Days"

![image](https://user-images.githubusercontent.com/679486/76417362-5c9d9f00-6362-11ea-9688-00bdae76b4cb.png)

Can that be changed to say "1 Earth Day"?  Or do we prefer to avoid that complexity in the i18n?

**Comment by arouinfar** [comment]
@samreid I think we generally avoid that complexity for i18n wherever possible. Since the time  passes relatively quickly, it's unlikely the grammatically incorrect `1 Earth Days` is visible on screen often or for long periods. I'm inclined to leave it as-is, but appreciate you bringing it up.
