### ISSUE TITLE
Position of clear button should not shift

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gravity-and-orbits#312]
In master, the position of the clear button currently shifts to the right as the string above it increases in length.
![image](https://user-images.githubusercontent.com/8419308/77032574-62027700-696a-11ea-9023-4cd7932cd7e9.png)
![image](https://user-images.githubusercontent.com/8419308/77032592-6af34880-696a-11ea-9ff6-4df346daad5f.png)
![image](https://user-images.githubusercontent.com/8419308/77032559-5616b500-696a-11ea-9bfb-9b133890690e.png)

This looks odd, and is deviation from the behavior in latest published version of the sim. It would be preferable for the button to have a fixed position and center the string above it.

**Comment by samreid** [comment]
Proposed fix committed, ready for review.

**Comment by arouinfar** [comment]
Looks good in master @samreid
