### ISSUE TITLE
Update phetioMetadata for the return objects button

### ISSUE THREAD

**Issue by samreid** [phetsims/gravity-and-orbits#313]
Sam Reid:house_with_garden:  26 minutes ago
Is there an issue for making “Return Objects” button in GAO read only?  I’m happy to create one, just let me know.

Amy Rouinfar  16 minutes ago
We think the enabledProperty, opacityProperty, pickableProperty, and visibleProperty should all be read only.

**Comment by samreid** [comment]
I marked those properties as read-only, @arouinfar can you please review?

**Comment by arouinfar** [comment]
Looks good in master @samreid!
