### ISSUE TITLE
Label "featured" items in studio:admin

### ISSUE THREAD

**Issue by samreid** [phetsims/gravity-and-orbits#314]
We need to specify which phetioIDs are featured and non-featured.

**Comment by arouinfar** [comment]
@samreid we've decided which elements to feature, but this is currently blocked by #316 because we've requested some changes to the tree.

**Comment by arouinfar** [comment]
Overrides have been committed. Leaving self-assigned to double check things in studio.

**Comment by arouinfar** [comment]
Everything looks good in studio, closing.
