### ISSUE TITLE
Dev testing

### ISSUE THREAD

**Issue by samreid** [phetsims/gravity-and-orbits#315]
We would like to run a QA "dev test" before sharing this to the client.  I have a few issues to wrap up first, then I can create a dev version.  @ariel-phet indicates April 1 may not be a strict deadline.

**Comment by samreid** [comment]
Our new milestone is to share this with clients May 22 or so.  In order to reach that goal, we will need to start dev testing soon.

**Comment by arouinfar** [comment]
@samreid we're ready for dev testing

**Comment by samreid** [comment]
I asked if we need to solve the "blocks-publication" issues for this dev version, and @kathy-phet said they are not essential for this dev version.

**Comment by samreid** [comment]
Deployed: https://phet-dev.colorado.edu/html/gravity-and-orbits/1.2.0-dev.9/phet/gravity-and-orbits_en_phet.html
Deployed: https://phet-dev.colorado.edu/html/gravity-and-orbits/1.2.0-dev.9/phet-io/

I also asked @arouinfar if we come up with a list of instructions or phetioIDs to address the client specifications.

**Comment by samreid** [comment]
During today's meeting, @pixelzoom recommended the designer take a closer look at all of the blocks publication issues to see if any need to be addressed for this version.  @arouinfar can you please take a look?

https://github.com/issues?q=is%3Aissue+label%3Astatus%3Ablocks-publication+is%3Aopen+sort%3Acreated-asc

**Comment by arouinfar** [comment]
@samreid I do not understand these issues well enough to make a determination. If an issue is not sim-breaking, it likely doesn't matter for dev delivery.

The dev version is intended for client evaluation and to ensure their desired customizations are possible. It does not need to be production quality and will not be integrated into their product.

In the process of creating the [client request doc](https://docs.google.com/document/d/1etMh7XCDL0mQL258R6XTm4mVavimbLl6VhKUcOmpL3g/edit#) (only visible to PhET-iO design team and Katie), I discovered a few elements we overlooked when originally committing the phetioFeatured overrides. I've updated the overrides, so please publish a new dev version before creating the QA issue @samreid.

**Comment by pixelzoom** [comment]
> During today's meeting, @pixelzoom recommended the designer take a closer look at all of the blocks publication issues

To clarify...  I recommended that the simulation team (not just the designer) take a look at the "blocks publication" issues before publishing any version that will be released outside of PhET.    That recommendation was based on the process that the pH Scale team established in https://github.com/phetsims/ph-scale/issues/164, prior to releasing a dev version of pH Scale to the client for evaluation.

I understand that PhET-iO processes are still evolving.  But the processes that are being establishing are not being disseminated.

**Comment by samreid** [comment]
> I've updated the overrides, so please publish a new dev version before creating the QA issue @samreid.

I pulled changes and created a dev version, linked above.

**Comment by samreid** [comment]
Dev testing complete, closing.
