### ISSUE TITLE
PhET-iO design review comments - part 2

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gravity-and-orbits#316]
For #284 and a continuation of #293. @kathy-phet and I reviewed #314, and have a few more requests.

- [ ] Remove the slider from the studio control for `*Screen.model.*Scene.*.massProperty`, and `*Screen.model.*Scene.*.rotationProperty`.

- [ ] Make `*Screen.model.*Scene.clock.isRunningProperty`, `*Screen.model.*Scene.clock.timeProperty`, `*Screen.model.*Scene.*.diameterProperty`, and `*Screen.model.*Scene.*.forceProperty` phetioReadOnly: true.

- [ ] Make the opacityProperty, pickableProperty, and visibleProperty under `*Screen.view.playAreaNode.*SceneView.*GravityVectorNode` and `*Screen.view.playAreaNode.*SceneView.*VelocityVectorNode` phetioReadOnly: true.

- [ ] `*Screen.view.controlPanel.gravityControl` should have a linked property to `*Screen.model.gravityEnabledProperty`.

- [ ] `modelScreen.view.playAreaNode.planetMoonSceneView.moonNode.indicatorNode` seems irrelevant to this scene. Even with the smallest mass and the most zoomed-out view, the Moon's indicatorNode never appears. Can it be removed?

- [ ] We recommend adjusting the tree structure/naming of the `modelScreen.view.massesControlPanel` and `toScaleScreen.view.massesControlPanel` in each scene to make things more readable. Essentially, it amounts to the icon, massLabel, and massControl of each body being grouped in a container. This also allows some simplification in the naming (moonIcon > moon.icon). Here's an outline of the proposed tree structure:
```
massesControlPanel
    opacityProperty
    pickableProperty
    visibleProperty
   -planetMoonSceneMassesControlPanel
        -moon
            opacityProperty
            pickableProperty
            visibleProperty     
            +icon 
            +massControl
            +massLabel
        +planet (contents parallel to moon)
   (repeat for other three scenes)
```

- [ ] We'd like to make similar changes to the `view.PlayAreaNode` on both screens. It would be nice if we could group all the body-specific things under a common container.  This doesn't seem quite as straightforward as the above item, so happy to discuss further. (An alternative we had considered was to put the {{body}}Node under the dummy {{body}} container like moon.moonNode, but that seems a little clunkier.)
```
playAreaNode
    opacityProperty
    pickableProperty
    visibleProperty
   -planetMoonSceneView
        -moon 
            opacityProperty
            pickableProperty
            visibleProperty
            +dragHandler  
            +gravityVectorNode  
            +velocityVectorNode
        +planet (contents parallel to moon)
   (repeat for other three scenes)
```

**Comment by samreid** [comment]
I'm going to split these out into separate issues so they can be tracked, assigned and labeled separately.

**Comment by samreid** [comment]
By having these as separate issues, we can have discussion threads on each one without them getting interleaved.  I moved the checkboxes to separate issues and will close this one.
