### ISSUE TITLE
Remove the slider from the studio control for massProperty, and rotationProperty

### ISSUE THREAD

**Issue by samreid** [phetsims/gravity-and-orbits#317]
From https://github.com/phetsims/gravity-and-orbits/issues/316

> Remove the slider from the studio control for `*Screen.model.*Scene.*.massProperty`, and `*Screen.model.*Scene.*.rotationProperty`.

**Comment by samreid** [comment]
Fixed, please review.

**Comment by arouinfar** [comment]
Looks good in master, thanks @samreid.
