### ISSUE TITLE
Mark some elements as phetioReadOnly: true

### ISSUE THREAD

**Issue by samreid** [phetsims/gravity-and-orbits#318]
From #316,

- [x] Make `*Screen.model.*Scene.clock.isRunningProperty`, `*Screen.model.*Scene.clock.timeProperty`, `*Screen.model.*Scene.*.diameterProperty`, and `*Screen.model.*Scene.*.forceProperty` phetioReadOnly: true.

- [x] Make the opacityProperty, pickableProperty, and visibleProperty under `*Screen.view.playAreaNode.*SceneView.*GravityVectorNode` and `*Screen.view.playAreaNode.*SceneView.*VelocityVectorNode` phetioReadOnly: true.

**Comment by samreid** [comment]
I implemented the proposed changes and verified them by reading the baseline file.  @arouinfar can you please review?

**Comment by arouinfar** [comment]
@samreid looks like you did exactly what I asked for. However, I think I made a mistake in requesting `velocityVectorNode.pickableProperty` to be phetioReadOnly: true.

The velocity vectors are draggable, but some clients may want to disable this behavior. If I'm not mistaken, the only place the client could access this is through `velocityVectorNode.pickableProperty`, so I think that should be phetioReadOnly: false.

**Comment by samreid** [comment]
Fixed and ready for review.

**Comment by arouinfar** [comment]
Looks good!
