### ISSUE TITLE
*Screen.view.controlPanel.gravityControl should have a linked property to *Screen.model.gravityEnabledProperty.

### ISSUE THREAD

**Issue by samreid** [phetsims/gravity-and-orbits#319]
From #316 

*Screen.view.controlPanel.gravityControl should have a linked property to *Screen.model.gravityEnabledProperty.

**Comment by samreid** [comment]
Implemented and ready for review.

**Comment by arouinfar** [comment]
Looks good in master, thanks @samreid!
