### ISSUE TITLE
Can modelScreen.view.playAreaNode.planetMoonSceneView.moonNode.indicatorNode be removed?

### ISSUE THREAD

**Issue by samreid** [phetsims/gravity-and-orbits#320]
From #316, 

modelScreen.view.playAreaNode.planetMoonSceneView.moonNode.indicatorNode seems irrelevant to this scene. Even with the smallest mass and the most zoomed-out view, the Moon's indicatorNode never appears. Can it be removed?

**Comment by samreid** [comment]
Isolating this as a special case and handling it differently sounds brittle and error prone and would lead to a less machine-friendly API.  For instance, if we change the zoom levels in the future, we would likely forget to "add this back".  Would it be acceptable to cover this with documentation, saying something in the documentation about the indicator node only showing when you are zoomed far enough back?

**Comment by arouinfar** [comment]
> Would it be acceptable to cover this with documentation, saying something in the documentation about the indicator node only showing when you are zoomed far enough back?

That sounds reasonable to me @samreid.

In reviewing #322, I noticed that the tree structure of the `indicatorNode` is a bit over-nested. The `indicatorNode` contains only a `labelNode` which holds all the associated properties. Do we need the `labelNode` level? Can its contents go under the `indicatorNode` itself?
![image](https://user-images.githubusercontent.com/8419308/79790231-aafe7000-8308-11ea-8043-961a26fa6ed5.png)

**Comment by samreid** [comment]
In the commit, I added documentation to the indicatorNode.  Regarding the nesting, there are actually 3 nodes at play here:

1. The parent node, which contains:
2. the line node and
3. the text node.

In order to make it so you can hide the line+text at the same time and still be able to change the text, I recommend to instrument the whole `indicatorNode` in addition to the `labelNode`.  The `lineNode` shouldn't be controllable independently, so it should be left uninstrumented.  Those changes were accomplished in the commit, can you please review?

**Comment by arouinfar** [comment]
@samreid looks good in master, thanks!
