### ISSUE TITLE
 adjusting the tree structure/naming of the modelScreen.view.massesControlPanel and toScaleScreen.view.massesControlPanel

### ISSUE THREAD

**Issue by samreid** [phetsims/gravity-and-orbits#321]
From #316 

We recommend adjusting the tree structure/naming of the `modelScreen.view.massesControlPanel` and `toScaleScreen.view.massesControlPanel` in each scene to make things more readable. Essentially, it amounts to the icon, massLabel, and massControl of each body being grouped in a container. This also allows some simplification in the naming (moonIcon > moon.icon). Here's an outline of the proposed tree structure:
```
massesControlPanel
    opacityProperty
    pickableProperty
    visibleProperty
   -planetMoonSceneMassesControlPanel
        -moon
            opacityProperty
            pickableProperty
            visibleProperty     
            +icon 
            +massControl
            +massLabel
        +planet (contents parallel to moon)
   (repeat for other three scenes)
```

**Comment by samreid** [comment]
Implemented in the commit:

![image](https://user-images.githubusercontent.com/679486/79299830-48d5e300-7ea2-11ea-8c40-5ccebea3b569.png)

Ready for review.

**Comment by arouinfar** [comment]
@samreid this is definitely an improvement, and makes the tree much more readable. 

One of the motivations for grouping the icon, massControl, and massLabel under a common container was to allow clients to hide the entire control by toggling a single visibleProperty, such as `planetMoonSceneMassesControlPanel.moon.visibleProperty`. However, the new containers don't have the usual top-level properties (opacityProperty, pickableProperty, visibleProperty). Can these be reasonably added?

**Comment by samreid** [comment]
In the commit, I instrumented the containers.  Once they were instrumented, it seemed odd to keep their names like `moon`, so I appended `ControlNode`, so it would read like `moonControlNode`.  Ready for review.

**Comment by arouinfar** [comment]
Looks great in master. Thanks @samreid!
