### ISSUE TITLE
group all the body-specific things under a common container.

### ISSUE THREAD

**Issue by samreid** [phetsims/gravity-and-orbits#322]
From #316 

We'd like to make similar changes to the `view.PlayAreaNode` on both screens. It would be nice if we could group all the body-specific things under a common container.  This doesn't seem quite as straightforward as the above item, so happy to discuss further. (An alternative we had considered was to put the {{body}}Node under the dummy {{body}} container like moon.moonNode, but that seems a little clunkier.)
```
playAreaNode
    opacityProperty
    pickableProperty
    visibleProperty
   -planetMoonSceneView
        -moon 
            opacityProperty
            pickableProperty
            visibleProperty
            +dragHandler  
            +gravityVectorNode  
            +velocityVectorNode
        +planet (contents parallel to moon)
   (repeat for other three scenes)
```

**Comment by samreid** [comment]
For consistency with our other occurrences, it seems `moon` should be `moonNode` in the example above, since it is a `Node`.

**Comment by samreid** [comment]
In order to keep the tandems consistent with the code, adding `gravityVectorNode` tandem as a child of the `moon` or `moonNode` tandem would require adding `gravityVectorNode` as a child of the `moonNode`.  May be difficult if the coordinate transforms are not set up that way.

**Comment by samreid** [comment]
On second thought, it seemed simple and clear enough to assign tandems as prescribed above without changing the scene graph.  Commits on the way.

**Comment by samreid** [comment]
Committed and ready for review.

**Comment by arouinfar** [comment]
@samreid the new tree structure is looking great in master. Thanks!
