### ISSUE TITLE
User suggestions: values, kilometers

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/gravity-and-orbits#323]
> 1. I am having my students change the mass of the “Sun” and then measure the orbit to estimate its mass via “Newton’s version of Kepler’s 3rd law”, P^2 = a^3/M in solar system units.
> 
> For the Sun-planet system, it looks like the grid squares are close to, but not exactly, 0.5 A. U. in size. Could you please make them exactly 0.5 A. U. - or smaller might be better for measuring off the screen (0.2 A.U?).
> 
> 2. Related, in the “Scale” version, the measuring tape is in miles. Please change this to kilometers for all of the examples. 
> 
> 3. I think I can understand why, but it would be nice to have the measuring tape available in the Model view as well. Perhaps call it “orbit measuring tape” if you are concerned about students getting the wrong idea about sizes.
> 
> 4. I would like students to play with the orbital velocity magnitudes, and discover escape velocity as a function of distance from the central object. Could you either have this set by value (as for Projectile Motion), or at least scale the velocity to the grid in some meaningful manner (e.g. 1 square = 10 km/s for the Sun-Earth system)?
>

**Comment by arouinfar** [comment]
> I am having my students change the mass of the “Sun” and then measure the orbit to estimate its mass via “Newton’s version of Kepler’s 3rd law”, P^2 = a^3/M in solar system units.

This goal is really better suited to My Solar System.

>For the Sun-planet system, it looks like the grid squares are close to, but not exactly, 0.5 A. U. in size. Could you please make them exactly 0.5 A. U. - or smaller might be better for measuring off the screen (0.2 A.U?).

The grid square distance is related to the perigee/perihelion distance for the system. I will clarify this in the Teacher Tips. Adding a scale bar to the grid (similar to CAF) would be a challenge here because of the varying zoom levels.

> Related, in the “Scale” version, the measuring tape is in miles. Please change this to kilometers for all of the examples.

We will be making this change in #268.

> I think I can understand why, but it would be nice to have the measuring tape available in the Model view as well. Perhaps call it “orbit measuring tape” if you are concerned about students getting the wrong idea about sizes.

We intentionally do not include a measuring tape on the model screen since the diameters of the bodies are all bogus.

> I would like students to play with the orbital velocity magnitudes, and discover escape velocity as a function of distance from the central object. Could you either have this set by value (as for Projectile Motion), or at least scale the velocity to the grid in some meaningful manner (e.g. 1 square = 10 km/s for the Sun-Earth system)?

Quantitative goals which would require number entry are really better served by My Solar System. We are considering adding values to the velocity vectors in #268.

**Comment by samreid** [comment]
@arouinfar what work remains to be done for this issue?

**Comment by arouinfar** [comment]
Looks like there isn't anything else to address for this issue, so I'll close.
