### ISSUE TITLE
Improve centering of the grid and bodies

### ISSUE THREAD

**Issue by samreid** [phetsims/gravity-and-orbits#327]
While working on #302 @arouinfar and I noticed the bodies sometimes get too close to the play/pause button:

![image](https://user-images.githubusercontent.com/679486/82354297-dfc01e80-99bd-11ea-9976-c9fa3513eff1.png)

![image](https://user-images.githubusercontent.com/679486/82354322-e64e9600-99bd-11ea-8483-ea7b1db862f8.png)

We recommend to remedy this by moving the entire grid up around 1/4 of a cell.

**Comment by samreid** [comment]
Moving the view up by 50px looks like this:

![image](https://user-images.githubusercontent.com/679486/82356462-d6848100-99c0-11ea-8549-83a2320c422c.png)

**Comment by samreid** [comment]
I tested across a few scenes and it seemed reasonable, so I committed the 50px translation.  @arouinfar can you please take a closer look?

**Comment by arouinfar** [comment]
@samreid looks good in master.
