### ISSUE TITLE
Rewrite to use common code GridNode

### ISSUE THREAD

**Issue by samreid** [phetsims/gravity-and-orbits#328]
Once GridNode review is completed in https://github.com/phetsims/scenery-phet/issues/580, Gravity and Orbits can use it.

**Comment by jessegreenberg** [comment]
https://github.com/phetsims/scenery-phet/issues/580 is complete and ready for use.

**Comment by samreid** [comment]
I ported Gravity and Orbits to use GRIDDLE/GridNode and it seems to be working well.  @arouinfar can you please test master on phettest and see if the grids are working as expected?  Just a few minutes of testing is probably sufficient, the change wasn't complicated but it was also not-quite-trivial.  Close if all is well.

**Comment by arouinfar** [comment]
@samreid something's not quite right in master.

Changing the zoom level will misalign the grid, so the bodies no longer start on grid intersections. For example:
![image](https://user-images.githubusercontent.com/8419308/90079608-9e41c580-dcc5-11ea-9968-cf6d230620ee.png)


The grid is broken on the Planet/Moon scene on both screens. Grid is checked, but doesn't appear in the play area. I tried toggling the checkbox and changing the zoom level, but the grid will not appear.
![image](https://user-images.githubusercontent.com/8419308/90079492-5458df80-dcc5-11ea-89df-d072c6c3cce7.png)

**Comment by samreid** [comment]
@jessegreenberg I would like the gridlines to stay fixed relative to the objects in space, but when the transform changes, the lines are adjusted.  Here is a movie:

![Kapture 2020-08-16 at 9 58 33](https://user-images.githubusercontent.com/679486/90338463-23b7c500-dfa7-11ea-8457-546d0330f76d.gif)

How can this be accomplished with GridNode?

**Comment by jessegreenberg** [comment]
The grid lines will be positioned with the ModelViewTransform, and so grid lines will not line up with other bodies if the GridNode's position is also modified like in https://github.com/phetsims/gravity-and-orbits/commit/c0519226a87c4afd2a5c46e90a10c548ea84e588. 

One way to do this would be to give the GridNode its own transform like
```js
   const gridTransformProperty = new ModelViewTransformProperty();

   const myGridNode = new GridNode( ..., ..., {
     modelViewTransformProperty: gridTransformProperty
   } );

    transformProperty.link( transform => {
      gridTransformProperty.set( ModelViewTransform2.createSinglePointScaleMapping(
        center, // model center
        transformProperty.get().modelToViewPosition( center ), // view center
        scene.zoomLevelProperty.get()
      ) );
    } );
```

Another way could be to not pass the GridNode a ModelViewTransform, but instead give it spacings in view coordinates and call `GridNode.setLineSpacings` whenever the `zoomLevelProperty` changes.

**Comment by samreid** [comment]
Thanks @jessegreenberg, I followed the strategy you prescribed and it is working pretty well.  The last remaining problem is that the GridNode seems to stop at the top of the dev bounds.  I haven't been able to figure out why it stops there.  Any ideas?  It looks like this:

![image](https://user-images.githubusercontent.com/679486/90463564-85bc1b80-e0c8-11ea-8233-e74850f224b5.png)

**Comment by samreid** [comment]
Also, it is centered for all scenes now except the earth/moon scene.  Leaving self-assigned for that part.

**Comment by jessegreenberg** [comment]
The transform in https://github.com/phetsims/gravity-and-orbits/issues/328#issuecomment-675167089 aligns the grid with the model origin, but the origin of the GridNode is still at (0, 0) relative to the GravityAndOrbitsSceneView. After playing with it for a bit, this is working pretty well, and makes sure that the grid fully covers the screen.
<details>

```js
  /**
   * @param {Property.<ModelViewTransform2>} transformProperty
   * @param {Property.<Number>} scaleProperty
   * @param {number} spacing - spacing between grid lines in model coordinates
   * @param {Vector2} center - center of the grid in model coordinates
   * @param {number} numGridLines - number grid lines on each side of the center
   * @param {Object} [options]
   */
  constructor( transformProperty, scaleProperty, spacing, center, numGridLines, options ) {
    const gridTransformProperty = new Property( ModelViewTransform2.createIdentity() );

    // linked lazily since screnBoundsProperty does not have defined bounds until
    // after sim is loaded
    Property.lazyMultilink( [ phet.joist.sim.screenBoundsProperty, scaleProperty ], ( bounds, scale ) => {
      const screenBounds = phet.joist.sim.screenBoundsProperty.get();
      const parentBounds = this.globalToParentBounds( screenBounds );

      // create a transform that aligns grid with origin of the model when the grid
      // has been positioned to cover screen bounds - note that this is not a transform
      // from model coordinates to view coordinates
      const centerInSceneViewFrame = transformProperty.get().modelToViewPosition( center );
      gridTransformProperty.set( ModelViewTransform2.createSinglePointScaleMapping(
        center,
        centerInSceneViewFrame.minus( parentBounds.leftTop ), // view center, relative to screen bounds
        scale
      ) );

      // ensure grid covers entire screen bounds
      this.leftTop = parentBounds.leftTop;
      this.setGridWidth( parentBounds.width );
      this.setGridHeight( parentBounds.height );
    } );

    const viewSpacing = transformProperty.get().modelToViewDeltaX( spacing );
    options = merge( {
      majorHorizontalLineSpacing: viewSpacing,
      majorVerticalLineSpacing: viewSpacing,
      modelViewTransformProperty: gridTransformProperty,
      majorLineOptions: {
        stroke: 'gray',
        lineWidth: 1
      }
    }, options );

    super( 1024, 754, options );
  }
```
</details>

There may be a better way to do this though. `sim.screenBoundsProperty` is joist-internal, so its usage is questionable. And the transform is not a model-view transform, but just handles alignment and keeps grid lines spaced in view coordinates. FInally, this doesn't work with the GravityAndOrbitsGridNode used as the icon for the checkbox in the control panel, something will have to be done about that.

@samreid reasigning back to you to review this. Please reasign to me if you would like some assistance cleaning this up and addressing the above things.

**Comment by samreid** [comment]
Thanks for all the assistance @jessegreenberg.  I tried this implementation but it was unclear where to get the `scaleProperty` and I agree with the other concerns you raised.  To meet the timeline for this simulation, I recommend to revert to the prior GridNode implementation.  In the future, if we need other features from the GRIDDLE/GridNode, including but not limited to phet-io support, accessibility, other customizations or performance, then we should re-open this issue for further investigation.  The pre-existing implementation is very clear and 10 lines of code shorter than the proposal from the preceding comment.
