### ISSUE TITLE
Projection mode makes reading tape measure difficult

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-and-orbits#329]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/505. Does not occur in published version
If you put the sim in projection mode (turning the background white) and pull out the tape measure, the text reading out the measurement is difficult or almost impossible to read. It is black text in a black bubble. In the published version it is black text on a white background.

**Visuals**
![hardtoreadmode](https://user-images.githubusercontent.com/41024075/83200997-cb88c980-a101-11ea-9f60-59f04a8b400c.png)
Here is the published version to compare:
![pubcompare](https://user-images.githubusercontent.com/41024075/83201012-d5123180-a101-11ea-9c87-af5a16c3edc4.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Gravity and Orbits‬
URL: https://phet-dev.colorado.edu/html/gravity-and-orbits/1.2.0-dev.10/phet/gravity-and-orbits_en_phet.html
Version: 1.2.0-dev.10 2020-05-26 17:36:54 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
Note that this does not seem to happen with the similar mass labels.

**Comment by samreid** [comment]
In discussion with @arouinfar we agreed this seems straightforward to fix, and it should be done before next dev release.

**Comment by samreid** [comment]
I'll work on this in #266, thanks!

**Comment by samreid** [comment]
Addressed in #266, but @KatieWoe can you please verify on phettest?  Close if all is well.
