### ISSUE TITLE
Check box sizes when text size changes

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-and-orbits#331]
For https://github.com/phetsims/QA/issues/505.
From Slack:
>Kathryn Woessner:pager:  2:18 PM
Was a consensus ever reached in regards to if checkboxes and the like should change size when their labels do? I can't find the issue in question. Masses and springs is an instance where they don't change, Gravity and Orbits they do.
Sam Reid:house_with_garden:  2:28 PM
If I recall correctly, we agreed the checkbox shouldn’t change size when the text changes size, thanks for discovering that problem!

![changecheckboxes](https://user-images.githubusercontent.com/41024075/83305981-f84ee680-a1be-11ea-9697-99dd654d3f34.png)
![dontchangecheckboxes](https://user-images.githubusercontent.com/41024075/83305983-f9801380-a1be-11ea-913b-83c1274d3511.png)

**Comment by KatieWoe** [comment]
Note: I wasn't able to find the original issue and I seem to remember there still being some disagreement in the end. This likely doesn't really need a fix.

**Comment by samreid** [comment]
In discussion with @arouinfar we agreed this seems straightforward to fix, and it should be done before next dev release.

**Comment by samreid** [comment]
Proposed fix committed, @KatieWoe can you please test on master?  Close if all is well.

**Comment by KatieWoe** [comment]
The checkboxes look better now. I did notice that the images that go with each item are now close enough to touch and it looks odd.
Now on master:
![muchclosernow](https://user-images.githubusercontent.com/41024075/84081897-11fce480-a99c-11ea-9f3d-93476d6581b7.png)
During Dev test:
![duringdevtest](https://user-images.githubusercontent.com/41024075/84081989-4375b000-a99c-11ea-972a-c35053d6c243.png)

**Comment by samreid** [comment]
Good catch, thanks!  Proposed fix is committed, please re-review.

**Comment by KatieWoe** [comment]
Looks good now
