### ISSUE TITLE
Items may not be returned, even with Return Object button

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-and-orbits#332]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Firefox
**Problem description**
For https://github.com/phetsims/QA/issues/505. Found in published version. Related to https://github.com/phetsims/gravity-and-orbits/issues/241. May be most preferable option, in which case, please close.
It is possible to permanently loose an object, so that the Return Object button does not bring it back. If this happens the Return Object button will keep popping up, but still will not return the missing object.
**Steps to reproduce**
1. Pull up any screen/scene (I find it easier to do on the second screen)
2. Zoom out all the way
3. Turn on the Velocity checkbox
4. Manipulate the velocity so that the orbiting object will shoot off screen
5. Once it has, pause the sim
6. Manipulate the large object's velocity so that it will shoot off screen next
7. Play sim again
8. Once the large object is gone, press the Return Object button

**Visuals**
![moonwontreturn](https://user-images.githubusercontent.com/41024075/83310962-f5f28980-a1ca-11ea-925f-15240e368ab8.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Gravity and Orbits‬
URL: https://phet-dev.colorado.edu/html/gravity-and-orbits/1.2.0-dev.10/phet/gravity-and-orbits_en_phet.html?colorProfile=projector
Version: 1.2.0-dev.10 2020-05-26 17:36:54 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0
Language: en-US
Window: 1536x750
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by samreid** [comment]
In discussion with @arouinfar, we agreed that since this occurs in the published version it will not block dev releases, but it should be investigated before RC.

**Comment by samreid** [comment]
This simulation records a new set of "initial conditions" when you update a position or velocity of a body.  It appears that "Return Objects" returns them to their recorded "initial conditions" instead of the simulation starting state.  Should we change the "Return Objects" button so that it returns objects to their simulation starting state?  @arouinfar what do you recommend?

**Comment by arouinfar** [comment]
After playing with this a bit more, I think the what @KatieWoe presented is more of an edge case. 

There's a lot of value in restoring the objects to the latest "initial conditions". It's likely that a user's custom orbit will lead to objects being lost off-screen. I think it's a better UX for the Return Objects button to restore the customized "initial conditions" so the experiment can be repeated.

At times, the behavior can be weird (as @KatieWoe demonstrated) but overall I think the current behavior is the better approach. Closing.
