### ISSUE TITLE
Objects Leave Play Area When Fully Zoomed In

### ISSUE THREAD

**Issue by JRomero0613** [phetsims/gravity-and-orbits#334]
For https://github.com/phetsims/QA/issues/505 on both the "model" and "to scale" screens the systems with the sun have their orbiting objects leave the play area when fully zoomed in. To see this in action go to either screen and select a system with the sun (first or second options), use the slider in the upper left corner to fully zoom in, and hit the play button to allow the orbit to process. Once the orbiting object reaches the top of the screen it will leave the play area, and the "return objects" button will appear. This happens on both screens for both systems with the sun without making any modifications to the objects masses or other simulation parameters, I think that this should not be the case and simulation parameters should have to be modified for the objects to leave the play area. By making the play area a little bigger or decreasing the magnification of the zoom option it would prevent this from occurring. I know this is a small detail so I'll leave it up to the developers if they want to address it.

**Comment by samreid** [comment]
@arouinfar how do you recommend to proceed?

**Comment by arouinfar** [comment]
@samreid this behavior is somewhat present in latest, though the Earth doesn't completely leave the frame. I think shifting the grid in #327 exacerbated the problem.

> By making the play area a little bigger or decreasing the magnification of the zoom option it would prevent this from occurring.

I agree @JRomero0613. 

@samreid let's reduce the maximum zoomLevelProperty to 1.4 for the sun-containing scenes.

**Comment by samreid** [comment]
More questions on this before I proceed:

1. Currently there is one zoom level applied to all of the scenes.  It could take some work to make it so each scene can have an independent zoom level.  But I wonder if that would be confusing--for instance, wouldn't users expect that max zoom is the same in different scenes?

2. I tried changing the max zoom to 1.4 and found the planet (in star/planet) still left the dev bounds at full zoom.  Turning the max zoom down to 1.17 kept everything within bounds.

3. Changing the max zoom to 1.17 and leaving the default and minimum zoom means the slider starts up like so:

![image](https://user-images.githubusercontent.com/679486/84077659-eb877b00-a994-11ea-9194-44c56c47795d.png)

Maybe we should allow the user to zoom in far enough that some objects go out of view?  

@arouinfar what do you recommend?

**Comment by samreid** [comment]
Moving to high priority since this is one of (or the only?) remaining issue before 2nd dev test.

**Comment by arouinfar** [comment]
> Currently there is one zoom level applied to all of the scenes. It could take some work to make it so each scene can have an independent zoom level. But I wonder if that would be confusing--for instance, wouldn't users expect that max zoom is the same in different scenes?

Oh, that's a good point. I think it'd be preferable to keep the zoom ranges the same across all scenes.

> I tried changing the max zoom to 1.4 and found the planet (in star/planet) still left the dev bounds at full zoom. Turning the max zoom down to 1.17 kept everything within bounds.

I must not have had the sim iframe in studio at the proper aspect ratio when I came up with 1.4. Testing at the dev aspect ratio, it seems like 1.3 could work. The planet briefly leaves the visible bounds, but isn't gone long enough to trigger the Return Objects button.

> Changing the max zoom to 1.17 and leaving the default and minimum zoom means the slider starts up like so:
Maybe we should allow the user to zoom in far enough that some objects go out of view?

@samreid let's try 1.3 instead.

**Comment by samreid** [comment]
In the commit, I reduced the max zoom to 1.3.  @arouinfar can you please review on phettest?

**Comment by arouinfar** [comment]
@samreid looks good in master. At max zoom, the Return Objects button does get briefly triggered in the StarPlanetMoonScene, but I think it's still an improvement and retains a more useful range for custom orbits.
