### ISSUE TITLE
Easy to grab wrong object when pointer areas overlap

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-and-orbits#338]
**Test device**
Lovelace
**Operating System**
ChromeOS
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/505. Pointer areas were looked at in https://github.com/phetsims/gravity-and-orbits/issues/199, but I noticed some potential issues.
When pointer areas overlap and you grab an area in both boxes, the one layered on top gets dragged, even if it wasn't the intended target. I have seen this quite often on the sun-planet-moon system on the first screen. When you go to drag the planet down and away (at default zoom/settings) there is about a 50% chance that you will grab the moon instead. @arouinfar indicated that cases like this may warrant a second look.

**Visuals**
![grabthemooooon](https://user-images.githubusercontent.com/41024075/83675483-53edeb00-a596-11ea-9e09-4eafd5f5d7fb.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Gravity and Orbits‬
URL: https://phet-dev.colorado.edu/html/gravity-and-orbits/1.2.0-dev.10/phet/gravity-and-orbits_en_phet.html?showPointerAreas
Version: 1.2.0-dev.10 2020-05-26 17:36:54 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by arouinfar** [comment]
@samreid is it possible to pick up the object whose center is closest to the click point?

**Comment by samreid** [comment]
@jonathanolson is there a nice way in scenery to deal with overlapping pointer areas?

**Comment by samreid** [comment]
I asked for recommendations on slack:

> We have some overlapping pointer areas in https://github.com/phetsims/gravity-and-orbits/issues/338 and would like to pick the “closest” instead of the “highest in z-order”, what have others done in this case?

@chrisklus and I brainstormed: 

* What about reshaping the pointer areas when they overlap?
* What about moving one object to the front based on whether it is closer to the mouse?
* Making the pointer areas smaller?

**Comment by samreid** [comment]
In Slack @pixelzoom said:

> Looks like you'd have to remove pointer area dilations and handle this yourself, likely by putting a listener on the entire play area that selects the "closest" planet. Similar to what I originally did for BunnyNodes in NS (before I switched to Sprites). (edited)

**Comment by samreid** [comment]
I investigated several strategies and the most promising are:

(a) reduce the pointer areas so there is less chance of overlap.  That could look something like this:

![image](https://user-images.githubusercontent.com/679486/90323405-26220c80-df1e-11ea-92f5-990a7f626d65.png)

(b) clip each pointer area based on a rotated square when another body comes too close.  That could be done with a patch that begins like so (see details).  This would likely take 2-6 more hours, will lead to increased code complexity and possibly performance issues when touch areas overlap.

<details>

```diff
Index: js/common/view/GravityAndOrbitsSceneView.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/view/GravityAndOrbitsSceneView.js	(revision 49906dbd94d25ea71a1d3b84de2c4cf331d02124)
+++ js/common/view/GravityAndOrbitsSceneView.js	(date 1597534655972)
@@ -11,10 +11,13 @@
 import DerivedProperty from '../../../../axon/js/DerivedProperty.js';
 import Property from '../../../../axon/js/Property.js';
 import Bounds2 from '../../../../dot/js/Bounds2.js';
+import Util from '../../../../dot/js/Utils.js';
+import Shape from '../../../../kite/js/Shape.js';
 import platform from '../../../../phet-core/js/platform.js';
 import MeasuringTapeNode from '../../../../scenery-phet/js/MeasuringTapeNode.js';
 import PhetColorScheme from '../../../../scenery-phet/js/PhetColorScheme.js';
 import PhetFont from '../../../../scenery-phet/js/PhetFont.js';
+import DragListener from '../../../../scenery/js/listeners/DragListener.js';
 import Rectangle from '../../../../scenery/js/nodes/Rectangle.js';
 import Color from '../../../../scenery/js/util/Color.js';
 import TextPushButton from '../../../../sun/js/buttons/TextPushButton.js';
@@ -39,6 +42,7 @@
 const HEIGHT = 618 * ( 1 / SCALE );
 const STAGE_SIZE = new Bounds2( 0, 0, WIDTH, HEIGHT );
 const buttonBackgroundColor = new Color( 255, 250, 125 );
+const TOUCH_DILATION = 5; // dilation factor, produces touch bounds which are easy to drag
 
 class GravityAndOrbitsSceneView extends Rectangle {
 
@@ -69,7 +73,8 @@
 
     // Use canvas coordinates to determine whether something has left the visible area
     const isReturnableProperties = [];
-    bodies.forEach( body => {
+
+    const bodyNodes = bodies.map( body => {
       const bodyNode = new BodyNode( body, body.labelAngle, model.isPlayingProperty, scene, tandem.createTandem( body.bodyNodeTandemName ) );
       const massReadoutNode = scene.massReadoutFactory( bodyNode, model.showMassProperty );
       this.addChild( bodyNode );
@@ -83,6 +88,52 @@
         return !STAGE_SIZE.intersectsBounds( bodyNode.bounds ) && !atRewindPosition;
       } );
       isReturnableProperties.push( isReturnableProperty );
+      return bodyNode;
+    } );
+
+    const p = [];
+    bodyNodes.forEach( bodyNode => {
+      bodyNode.setAllBodyNodes( bodyNodes );
+      p.push( bodyNode.body.positionProperty );
+      p.push( bodyNode.body.diameterProperty );
+    } );
+    p.push( scene.zoomLevelProperty );
+
+    // When any body size or position changes, update the pointer areas
+    Property.multilink( p, () => {
+
+      bodyNodes.forEach( bodyNode => {
+        const center = bodyNode.bodyRenderer.bounds.center;
+        const circle = Shape.circle( center.x, center.y, bodyNode.getViewDiameter() / 2 + TOUCH_DILATION );
+        bodyNode.touchArea = circle;
+        bodyNode.mouseArea = circle;
+
+        // const otherBodyNodes = bodyNodes.filter( b => b !== bodyNode && !b.body.isCollidedProperty.value );
+        //
+        // const getEdgeDistance = b => b.center.minus( bodyNode.center ).magnitude - b.getViewDiameter() - bodyNode.getViewDiameter() - TOUCH_DILATION * 2;
+        // const closestOtherBodyNode = _.minBy( otherBodyNodes, getEdgeDistance );
+        // const edgeDistance = getEdgeDistance( closestOtherBodyNode );
+        // console.log( edgeDistance );
+        // if ( edgeDistance < 0 ) {
+        //   const otherBodyCenter = closestOtherBodyNode.bodyRenderer.bounds.center;
+        //   const otherShape = Shape.circle( otherBodyCenter.x, otherBodyCenter.y, closestOtherBodyNode.getViewDiameter() );
+        //
+        //   // touch areas need to change with diameter
+        //   const circle = Shape.circle( center.x, center.y, bodyNode.getViewDiameter() + TOUCH_DILATION ).shapeDifference( otherShape );
+        //   bodyNode.touchArea = circle;
+        //   bodyNode.mouseArea = circle;
+        // }
+        // else {
+        //   const circle = Shape.circle( center.x, center.y, bodyNode.getViewDiameter() + TOUCH_DILATION );
+        //   bodyNode.touchArea = circle;
+        //   bodyNode.mouseArea = circle;
+        // }
+
+
+        // reduce touch dilatation if the body is too close to another body
+
+
+      } );
     } );
 
     // Add gravity force vector nodes
Index: js/common/view/PathsCanvasNode.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/view/PathsCanvasNode.js	(revision 49906dbd94d25ea71a1d3b84de2c4cf331d02124)
+++ js/common/view/PathsCanvasNode.js	(date 1597526339270)
@@ -22,7 +22,7 @@
 class PathsCanvasNode extends CanvasNode {
   /**
    *
-   * @param {Body} bodies
+   * @param {Body[]} bodies
    * @param {Property.<ModelViewTransform2>} transformProperty
    * @param {Property.<boolean>} visibleProperty
    * @param {Bounds2} canvasBounds
Index: js/common/view/BodyNode.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/view/BodyNode.js	(revision 49906dbd94d25ea71a1d3b84de2c4cf331d02124)
+++ js/common/view/BodyNode.js	(date 1597526497682)
@@ -15,13 +15,11 @@
 import DragListener from '../../../../scenery/js/listeners/DragListener.js';
 import Line from '../../../../scenery/js/nodes/Line.js';
 import Node from '../../../../scenery/js/nodes/Node.js';
+import Shape from '../../../../kite/js/Shape.js';
 import Text from '../../../../scenery/js/nodes/Text.js';
 import gravityAndOrbits from '../../gravityAndOrbits.js';
 import GravityAndOrbitsColorProfile from '../GravityAndOrbitsColorProfile.js';
 
-// constants
-const TOUCH_DILATION = 15; // dilation factor, produces touch bounds which are easy to drag
-
 class BodyNode extends Node {
 
   /**
@@ -41,6 +39,7 @@
 
     this.modelViewTransformProperty = scene.transformProperty; // @private
     this.body = body; // @public
+    this.bodyNodes = null;
 
     this.body.isCollidedProperty.link( isCollided => this.setVisible( !isCollided ) );
 
@@ -95,12 +94,9 @@
     };
     Property.multilink( [ this.body.positionProperty, this.modelViewTransformProperty ], this.positionListener );
 
-    this.diameterListener = ( position, modelViewTransform ) => {
-      this.bodyRenderer.setDiameter( this.getViewDiameter() );
-
-      // touch areas need to change with diameter
-      this.touchArea = this.bodyRenderer.bounds.dilated( TOUCH_DILATION );
-      this.mouseArea = this.bodyRenderer.bounds.dilated( TOUCH_DILATION );
+    this.diameterListener = () => {
+      const viewDiameter = this.getViewDiameter();
+      this.bodyRenderer.setDiameter( viewDiameter );
     };
     Property.multilink( [ this.body.diameterProperty, this.modelViewTransformProperty ], this.diameterListener );
 
@@ -125,6 +121,14 @@
     this.addChild( this.createArrowIndicator( this.body, labelAngle, tandem.createTandem( 'indicatorNode' ) ) );
   }
 
+  /**
+   * @param {BodyNode[]} bodyNodes - all body nodes, to disambiguate drag events.
+   * @public
+   */
+  setAllBodyNodes( bodyNodes ) {
+    this.bodyNodes = bodyNodes;
+  }
+
   /**
    * Return a Node that points to the sphere with a text indicator and line when it is too small to see (in modes
    * with realistic units)

```

</details>

@arouinfar how do you recommend to proceed with this issue?

**Comment by jonathanolson** [comment]
> @jonathanolson is there a nice way in scenery to deal with overlapping pointer areas?

Either having a "background" that receives the event, and manually looks up what object is the potential drag target, OR adjusting the touch areas during the animation (probably won't work here for performance).

**Comment by samreid** [comment]
When I first investigated the background strategy, it was unclear how I could accomplish "allowTouchSnag" with it.  That's why I focused on the other strategies mentioned in https://github.com/phetsims/gravity-and-orbits/issues/338#issuecomment-674458293.  If we do come back to the "background" strategy, we could likely use the "drag forwarding" approach to use most of the information in DragListener (including transforms, data stream, etc).  But adjusting the pointer areas would be far simpler.

**Comment by arouinfar** [comment]
> (a) reduce the pointer areas so there is less chance of overlap.  That could look something like this:
![image](https://user-images.githubusercontent.com/679486/90323405-26220c80-df1e-11ea-92f5-990a7f626d65.png)

This looks like a reasonable approach to me, given that the Moon label is also grabbable. For two-body systems, I would want the pointerArea diameter to match the current square side in master.

**Comment by samreid** [comment]
I made the pointer areas circular, keeping the diameter the same as the edge length as the rectangles.  I also reduced the touch dilatation for the earth and moon in the sun/earth/moon system and it looks good to me.  As I was testing scenarios I also noticed the satellite overlaps the earth pointer areas, so I'll correct that as well:

![image](https://user-images.githubusercontent.com/679486/90705354-ff324600-e24f-11ea-9f17-c73cc01088d9.png)

**Comment by samreid** [comment]
I corrected that scene as well. Back to @arouinfar for review, please close if all is well.

**Comment by arouinfar** [comment]
Looks good @samreid.
