### ISSUE TITLE
Snag to pick up star/planet/moon but not velocity vector

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-and-orbits#339]
**Test device**
iPad
**Operating System**
iPadOS 13
**Browser**
Safari
**Problem description**
For https://github.com/phetsims/QA/issues/505. More noticeable on smaller screens where objects are harder to pick up accurately.
The snag-to-pick-up feature will work to pick up objects in the sim, which is very useful. However, the velocity vector control is of a comparable size and I found myself missing it relatively often on iPad. This control does not have snag-to-pick-up and I think it may be worth considering adding it.

**Visuals**
![ezgif com-optimize](https://user-images.githubusercontent.com/41024075/83690102-590a6480-a5ad-11ea-8a71-3264003abe5c.gif)

**Comment by samreid** [comment]
@arouinfar and I agreed we should have touch snag for the velocity vector.  It sounds easy, so let's do it for the upcoming dev version.  If this becomes difficult, it can wait until RC.

**Comment by samreid** [comment]
Fixed in the commit, @KatieWoe would you like to test/verify in master?

**Comment by KatieWoe** [comment]
Looks good in master.

**Comment by samreid** [comment]
Thanks, closing.
