### ISSUE TITLE
Mirror Wrapper on IE lags while sim is unpaused

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/gravity-and-orbits#341]
**Test device**

Windows 10 Laptop

**Operating System**

Windows 10 v. 1903

**Browser**

Internet Explorer v. 11.836.18362.0

**Problem description**

For https://github.com/phetsims/QA/issues/505

The Mirror Wrapper on IE lags while the sim is unpaused. 

**Steps to reproduce**

1. Open the IE wrapper
2. Unpause the sim
3. Manipulate the stars or planets to observe lag easier

**Visuals**

![2020-06-03Grv OrbitsIEMirror](https://user-images.githubusercontent.com/54685448/83698199-10a77280-a5be-11ea-9520-1d52a6218d07.gif)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
  
Name: ‪Gravity and Orbits‬

URL: https://phet-dev.colorado.edu/html/gravity-and-orbits/1.2.0-dev.10/phet/gravity-and-orbits_en_phet.html

Version: 1.2.0-dev.10 2020-05-26 17:36:54 UTC

Features missing: touch, fullscreen

Flags: pointerEnabled, msPointerEnabled, pixelRatioScaling

User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0; rv:11.0) like Gecko

Language: en-US

Window: 1574x773

Pixel Ratio: 1.2200000286102295/1

WebGL: WebGL 0.94

GLSL: WebGL GLSL ES 0.94

Vendor: Microsoft (Internet Explorer)

Vertex: attribs: 16 varying: 15 uniform: 512

Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)

Max viewport: 16384x16384

OES_texture_float: true

Dependencies JSON: {}

**Comment by samreid** [comment]
In discussion with @arouinfar, we agreed: The mirror inputs wrapper is a more of an "internal testing" tool that tests the events transmit from one frame to another.  Low performance on IE sounds acceptable, closing.
