### ISSUE TITLE
Touch snag picks up planet and tape measure

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-and-orbits#342]
**Device**
Dell
**OS**
Win 10
**Browser**
Chrome
**Problem Description**
For https://github.com/phetsims/QA/issues/505. Bug does not happen in published version.
It is possible to snag the tape measure while already dragging another object. This does not occur in the opposite direction.
**Steps**
1. Go to the second screen and go to the Earth+space station scene (easiest to see)
2. Turn on the tape measure option
3. Using touch, pick up the planet
4. Drag the planet over the tape measure, so that your finger also passes it over

**Visual**
![ezgif com-optimize](https://user-images.githubusercontent.com/41024075/83795829-4b141c80-a65d-11ea-8f3e-8e5f76a0ab7c.gif)

**Comment by samreid** [comment]
In discussion with @arouinfar, we agreed this would be important for the RC but not necessarily for the dev version.  But if it is easy, dev version would be nice!

**Comment by samreid** [comment]
Proposed fix committed, @KatieWoe can you please verify in master?

**Comment by KatieWoe** [comment]
Looks good in master.

**Comment by samreid** [comment]
Thanks, closing.
