### ISSUE TITLE
Should scene reset also reset to launched settings?

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-and-orbits#343]
**Device**
Dell
**OS**
Win 10
**Browser**
Chrome
**Problem Description**
For https://github.com/phetsims/QA/issues/505.
In studio, when you launch a sim and hit the reset all button, it resets to the state it launched in. In the Gravity and Orbits sim there are also scene resets. In a launched sim these buttons reset the scene to the default position, instead of the launched position. Should this be changed?
![smallreset](https://user-images.githubusercontent.com/41024075/83803327-9af8e080-a669-11ea-8dad-741f1190cc6a.gif)

**Comment by KatieWoe** [comment]
I also noticed that the skip back button goes back to the default starting position, rather than the position at launch.
![skipback](https://user-images.githubusercontent.com/41024075/83915281-2a68c700-a730-11ea-8213-fe6ce8af0de6.png)

**Comment by samreid** [comment]
In discussion with @arouinfar, we agreed this should be investigated, and we can try a `restoreStateForScene` strategy inspired by the `restoreStateForScreen` implementation.  This will likely require that everything to be reset requires the same phetioID prefix, or we may need to visit several prefixes.  This may be difficult due to the existing tandem structures.

We would like to investigate before the next dev version.

Tagging @zepumph since he was instrumental in creating the `restoreStateForScreen` implementation.

**Comment by zepumph** [comment]
@pixelzoom mentioned this before in https://github.com/phetsims/phet-io/issues/1678, and I think that it is worth taking a step back, and trying to handle this behavior more generally. 

Potential solutions:
1. Build some sort of functionality into a common code view component like StartOverButton.js. To me this is just expanding the problems we have with MVC in the ResetAllButton to this case.
2. Build out API functionality into phetioStateEngine, and then add sim specific code to set the appropriate state when start over occurs.
3. Bring back setting the initial value in `PropertyIO.setValue` in some cases, perhaps only opting into this behavior, and not doing it all the time. This will potentially fix some cases, but suffers from the need for supporting other types.
4. Develop an MVC approach to ResetAllButton and StartOver together, and figure out a way that a model can specify the desired start-over code that should be run, that somehow demonstrates the appropriate behavior with setting state too.

I currently don't like the idea of building out our ResetAllButton behavior for this case.

**Comment by pixelzoom** [comment]
I don't have a complete understanding of all of the subtleties here. But my gut feeling is that solution 4 (above) would be worth exploring first.

**Comment by samreid** [comment]
It's unclear how to proceed for this, I marked for discussion on Wednesday's PhET-iO subteam meeting.

**Comment by samreid** [comment]
@chrisklus @zepumph and I discussed it today, and proposed the direction in this patch:

<details>

```diff

Index: main/gravity-and-orbits/js/common/model/GravityAndOrbitsModel.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- main/gravity-and-orbits/js/common/model/GravityAndOrbitsModel.js	(revision d05521f46c6bbfe8adac6eeb0d10b605fcf47936)
+++ main/gravity-and-orbits/js/common/model/GravityAndOrbitsModel.js	(date 1592413170863)
@@ -18,6 +18,7 @@
 import Property from '../../../../axon/js/Property.js';
 import PropertyIO from '../../../../axon/js/PropertyIO.js';
 import PhysicalConstants from '../../../../phet-core/js/PhysicalConstants.js';
+import PhetioStateEngine from '../../../../phet-io/js/PhetioStateEngine.js';
 import TimeSpeed from '../../../../scenery-phet/js/TimeSpeed.js';
 import Tandem from '../../../../tandem/js/Tandem.js';
 import ObjectIO from '../../../../tandem/js/types/ObjectIO.js';
@@ -130,6 +131,8 @@
     for ( let i = 0; i < this.sceneList.scenes.length; i++ ) {
       this.sceneList.scenes[ i ].reset();
     }
+
+    Tandem.PHET_IO_ENABLED && PhetioStateEngine.restoreState(/* on those things*/ );
   }
 }
 
Index: main/phet-io/js/PhetioStateEngine.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- main/phet-io/js/PhetioStateEngine.js	(revision 5e249f15bfd58d4553163c30c0f50fbbbda64f6c)
+++ main/phet-io/js/PhetioStateEngine.js	(date 1592413125004)
@@ -168,6 +168,8 @@
     return state;
   }
 
+  restoreStateRecursively(...phetioIDPrefix){}
+
   /**
    * Sets entire state from an object that represents the state.
    *
@@ -175,7 +177,7 @@
    * @param {PhetioState} state - a json object (not a string) that specifies the values to set
    * @param {string} [phetioIDPrefix] - if provided, state will only be set on phetioID subtrees of this prefix.
    */
-  setState( state, phetioIDPrefix = '' ) {
+  getAllChildren( state, phetioIDPrefix = '' ) {
     this.isSettingStateProperty.value = true;
     assert && assert( state !== undefined );
     assert && assert( ( typeof state ) !== 'string' );
@@ -196,6 +198,8 @@
     }
     const phetioIDsToSet = _.keys( stateToSet );
 
+    this.setState(phetioIDsToSet);// Non-recursive.
+
     // called with the list of elements phetioIDs that are about to get set
     this.onBeforeStateSetEmitter.emit( Object.keys( stateToSet ) );
 
Index: main/gravity-and-orbits/js/common/model/Body.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- main/gravity-and-orbits/js/common/model/Body.js	(revision d05521f46c6bbfe8adac6eeb0d10b605fcf47936)
+++ main/gravity-and-orbits/js/common/model/Body.js	(date 1592411612033)
@@ -19,6 +19,7 @@
 import Vector2IO from '../../../../dot/js/Vector2IO.js';
 import Vector2Property from '../../../../dot/js/Vector2Property.js';
 import merge from '../../../../phet-core/js/merge.js';
+import PhetioStateEngine from '../../../../phet-io/js/PhetioStateEngine.js';
 import PhetioObject from '../../../../tandem/js/PhetioObject.js';
 import ArrayIO from '../../../../tandem/js/types/ArrayIO.js';
 import BooleanIO from '../../../../tandem/js/types/BooleanIO.js';
@@ -83,7 +84,7 @@
     // @public (read-only) {string}
     this.bodyNodeTandemName = `${tandem.name}Node`;
 
-    this.accelerationProperty = new Vector2Property( new Vector2( 0, 0 ) );
+    this.accelerationProperty = new Vector2Property( new Vector2( 0, 0 ) ); //
     this.diameterProperty = new NumberProperty( diameter, {
       tandem: tandem.createTandem( 'diameterProperty' ),
       units: 'm',
@@ -438,17 +439,24 @@
     this.clearedEmitter.emit( this.type );
   }
 
+  restoreState() {
+    // PhetioStateEngine.setStateWithChildren(this.phetioID);
+    PhetioStateEngine.restoreInitialState( this );
+  }
+
   // @public
   resetAll() {
     this.positionProperty.reset();
     this.velocityProperty.reset();
-    this.accelerationProperty.reset();
+    this.accelerationProperty.reset(); // TODO: instrument?
     this.forceProperty.reset();
     this.massProperty.reset();
     this.diameterProperty.reset();
     this.isCollidedProperty.reset();
     this.clockTicksSinceExplosionProperty.reset();
     this.rotationProperty.reset();
+
+    // TODO: put in array, and pass through to PhetioStateEngine
     this.clearPath();
   }
 
Index: main/gravity-and-orbits/js/common/GravityAndOrbitsScene.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- main/gravity-and-orbits/js/common/GravityAndOrbitsScene.js	(revision d05521f46c6bbfe8adac6eeb0d10b605fcf47936)
+++ main/gravity-and-orbits/js/common/GravityAndOrbitsScene.js	(date 1592411151438)
@@ -234,9 +234,16 @@
    * @public
    */
   resetScene() {
+
     this.physicsEngine.resetBodies();
-    this.deviatedFromDefaultsProperty.set( false );
+    this.deviatedFromDefaultsProperty.set( false ); // TODO: this should probably be instrumented!
     this.getClock().setSimulationTime( 0.0 );
+
+    if ( Tandem.PHET_IO_ENABLED ) {
+      this.physicsEngine.restoreStateForScene();
+      this.getClock.restoreStateForScene();
+      phet.phetio.phetioEngine.phetioStateEngine.restoreStateForElement( this.deviatedFromDefaultsProperty );
+    }
   }
 
   /**
Index: main/gravity-and-orbits/js/common/model/GravityAndOrbitsPhysicsEngine.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- main/gravity-and-orbits/js/common/model/GravityAndOrbitsPhysicsEngine.js	(revision d05521f46c6bbfe8adac6eeb0d10b605fcf47936)
+++ main/gravity-and-orbits/js/common/model/GravityAndOrbitsPhysicsEngine.js	(date 1592413124995)
@@ -9,6 +9,7 @@
  */
 
 import Emitter from '../../../../axon/js/Emitter.js';
+import PhetioStateEngine from '../../../../phet-io/js/PhetioStateEngine.js';
 import TimeSpeed from '../../../../scenery-phet/js/TimeSpeed.js';
 import gravityAndOrbits from '../../gravityAndOrbits.js';
 import ModelState from './ModelState.js';
@@ -183,6 +184,9 @@
   resetBodies() {
     for ( let i = 0; i < this.bodies.length; i++ ) {
       this.bodies[ i ].resetAll();
+      if ( Tandem.PHET_IO_ENABLED ) {
+        PhetioStateEngine.restoreStateRecursively( this.bodies[ i ].tandem.phetioID );
+      }
     }
     this.updateForceVectors(); // has to be done separately since physics is computed as a batch
   }
Index: main/gravity-and-orbits/js/common/view/GravityAndOrbitsScreenView.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- main/gravity-and-orbits/js/common/view/GravityAndOrbitsScreenView.js	(revision d05521f46c6bbfe8adac6eeb0d10b605fcf47936)
+++ main/gravity-and-orbits/js/common/view/GravityAndOrbitsScreenView.js	(date 1592413187160)
@@ -111,7 +111,10 @@
 
     // Create and add the Reset All Button in the bottom right, which resets the model
     const resetAllButton = new ResetAllButton( {
-      listener: () => model.reset(),
+      phetioRestoreScreenStateOnReset: false,
+      listener: () => {
+        model.reset();
+      },
       right: this.layoutBounds.right - MARGIN - 4,
       bottom: this.layoutBounds.bottom - MARGIN - 4, // slight difference centers below panels
       tandem: tandem.createTandem( 'resetAllButton' )
Index: main/tandem/js/PhetioDynamicElementContainer.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- main/tandem/js/PhetioDynamicElementContainer.js	(revision 4a035869c3e67a235c610b2ab77950f0cc2d5b56)
+++ main/tandem/js/PhetioDynamicElementContainer.js	(date 1592412154950)
@@ -140,7 +140,7 @@
         }
       } );
 
-      phetioStateEngine.addSetStateHelper( ( state, stillToSetIDs ) => {
+      phetioStateEngine.addSetStateHelper( this,this.phetioID,( state, stillToSetIDs ) => {
         let creationNotified = false;
 
         while ( this.deferredCreations.length > 0 ) {

```

</details>

**Comment by samreid** [comment]
I'm reviewing the change set and cannot remember or figure out why we changed:

```js
phetioStateEngine.addSetStateHelper( ( state, stillToSetIDs ) => {
```

to 

```js
phetioStateEngine.addSetStateHelper( this, this.phetioID, ( state, stillToSetIDs ) => {
```

**Comment by zepumph** [comment]
Perhaps that was just a discussion topic that we didn't end up going with for this issue. It seems like it belongs with https://github.com/phetsims/phet-io/issues/1682. I don't even see you using addSetStateHelper here.

**Comment by samreid** [comment]
As I proceed on this, I'm seeing this pattern multiple times:

```js
property1.reset();
property2.reset();
PhetioStateEngine.restoreInitialStateForProperties(property1,property2);
```

What happened when we tried to put `restoreInitialState` as a step in `Property.reset`, and how did we rule that out?  Because it seems that could be a simplifying step for this issue.

**Comment by zepumph** [comment]
I have a side thought. Do you think that `restoreInitialStateForProperties` may belong in `PropertyStateHandler`?

**Comment by samreid** [comment]
I'm hoping that the patch in https://github.com/phetsims/gravity-and-orbits/issues/343#issuecomment-648332171 eliminates the need for `restoreInitialStateForProperties`, but thanks for reminding me about `PropertyStateHandler`!

**Comment by samreid** [comment]
I addressed this in https://github.com/phetsims/phet-io/issues/1678, @KatieWoe can you please verify using phettest/master?    @arouinfar would you also like to review the behavior?

**Comment by KatieWoe** [comment]
Looks mostly good. But I did notice that pause/play setting isn't included. Is that intended @samreid?

**Comment by samreid** [comment]
Can you please clarify?  Are you asking if resetting a scene should restore the play/pause state?

**Comment by KatieWoe** [comment]
Yes, that's what I'm asking

**Comment by samreid** [comment]
To me, it doesn't seem like resetting a scene should change the play/pause buttons, since those apply to all scenes.  Let me know if you disagree or if I'm missing something.

**Comment by arouinfar** [comment]
Looks good in master @samreid.

**Comment by samreid** [comment]
In https://github.com/phetsims/phet-io/issues/1678 we decided to use a different approach that will require updating this issue.

**Comment by samreid** [comment]
@arouinfar should this be repaired before dev.2?

**Comment by samreid** [comment]
Following the strategy in https://github.com/phetsims/phet-io/issues/1678 I restore the scene on scene reset and it is working well.  The last part for this issue is to get the "rewind" button to have the correct behavior, but this has been tricky and I don't know if it can be accomplished with the heuristic recommended in https://github.com/phetsims/phet-io/issues/1678 about not changing reset semantics.  Calling `reset` on a `RewindableProperty` takes the initial value, and sets the rewindable value to be the same thing.  So when pressing "Reset All" on the simulation, even though configure initial states are restored, the rewindable points are set back to simulation initial values.

I experimented with one patch to set the rewind values to the customized state, but it isn't working properly.

<details>

```diff
Index: js/common/model/Body.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/model/Body.js	(revision 5dc13a266148431a8027cd31138492dd5056f11e)
+++ js/common/model/Body.js	(date 1594440796134)
@@ -20,6 +20,7 @@
 import Vector2Property from '../../../../dot/js/Vector2Property.js';
 import merge from '../../../../phet-core/js/merge.js';
 import PhetioObject from '../../../../tandem/js/PhetioObject.js';
+import Tandem from '../../../../tandem/js/Tandem.js';
 import ArrayIO from '../../../../tandem/js/types/ArrayIO.js';
 import BooleanIO from '../../../../tandem/js/types/BooleanIO.js';
 import NumberIO from '../../../../tandem/js/types/NumberIO.js';
@@ -287,6 +288,15 @@
       // max path length is ~0.85 of a full orbit
       this.maxPathLength = 0.85 * 2 * Math.PI * distToCenter + this.pathLengthBuffer;
     }
+
+    if ( Tandem.PHET_IO_ENABLED ) {
+      const listener = () => {
+        this.saveBodyState();
+        console.log( 'State set complete, setting rewind values' );
+        phet.phetio.phetioEngine.phetioStateEngine.stateSetEmitter.removeListener( listener );
+      };
+      phet.phetio.phetioEngine.phetioStateEngine.stateSetEmitter.addListener( listener );
+    }
   }
 
   /**
@@ -354,6 +364,7 @@
    * @public
    */
   saveBodyState() {
+    console.log('saving body state');
     assert && assert( !this.isPlayingProperty.get(), 'saveBodyState should only be called when sim is paused' );
 
     this.positionProperty.storeRewindValueNoNotify();
```

</details>

**Comment by samreid** [comment]
After adding another PhET-iO state Property in the commit, and also separating between partial and full state in https://github.com/phetsims/phet-io/issues/1678, this is working as expected.  @arouinfar or @KatieWoe can you please test the behavior of reset scene/rewind on a customized sim launched from studio?  If all is well, this issue can be closed.

**Comment by KatieWoe** [comment]
The skip back button still goes back to the default start, rather than the new start from what I can tell.

**Comment by samreid** [comment]
Yes, I observed the same behavior.  I rationalized it by seeing that in Studio, the "rewind" button goes to the default start, and that you can use studio to drag the objects to create a "new start" that it will reset to in the customized version.  Let's check in with @arouinfar about this.

**Comment by arouinfar** [comment]
The behavior generally seems ok in master, but I find it odd that the RestartButton returns the sim to its default (or saved) state rather than the launched state. It's likely that the state restored by the RestartButton will be very different from the one restored by the ResetAllButton or scene reset buttons. This interaction doesn't feel particularly intuitive.

The goal of the RestartButton is to allow users to repeat some custom experiment, which is somewhat parallel to the experience in launching a simulation from studio. I would expect the RestartButton's state to get overridden when launching. Is that possible to do @samreid?

**Comment by samreid** [comment]
I tried to achieve the behavior of having rewind go back to the customized value, but as noted in https://github.com/phetsims/gravity-and-orbits/issues/343#issuecomment-656985108 it was complex and I was unable to get it working it after several attempts.  I am happy to work on it further, and it may help for @zepumph or @chrisklus to help out.  Should this block a dev version, or just RC?

**Comment by samreid** [comment]
This patch gets everything working except the enabled/disabled nature of the rewind button:

<details>


```diff
Index: js/common/GravityAndOrbitsScene.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/GravityAndOrbitsScene.js	(revision 1eab3d09146421bb952332b97bad661874959130)
+++ js/common/GravityAndOrbitsScene.js	(date 1594777908266)
@@ -138,6 +138,9 @@
 
     // @private (phet-io only)
     this.pairs = pairs;
+
+    // @private
+    this.stateSaved = false;
   }
 
   /**
@@ -261,11 +264,15 @@
     this.physicsEngine.updateForceVectors();
 
     this.rewindingProperty.set( false );
+
+    if ( !this.stateSaved ) {
+      Tandem.PHET_IO_ENABLED && phet.phetio.phetioEngine.phetioStateEngine.restoreStateForPhetioObject( this );
+    }
   }
 
   /**
-   * Save the state of the orbital system, which includes all rewindable properties
-   * of all bodies. This should only be called when the sim is paused.
+   * Save the state of the orbital system, which includes all rewindable properties of all bodies. This should only be
+   * called when the sim is paused.
    * @public
    */
   saveState() {
@@ -275,6 +282,7 @@
     for ( let i = 0; i < bodies.length; i++ ) {
       bodies[ i ].saveBodyState();
     }
+    this.stateSaved = true;
   }
 
   /**

```

<details>

**Comment by samreid** [comment]
The commit also gets the enabled/disable nature working.  It seems OK in my tests.  @arouinfar can you please test it on your side?  If the behavior is good, we should run it past @zepumph for a mini-review before we go to testing dev.2.

**Comment by arouinfar** [comment]
@samreid this only seems to be working if the RestartButton state was anything other than the default when the sim is launched.

For example:
1. Model screen, any scene
2. Press play, and wait for the planet to move a bit
3. Launch the sim
4. Press RestartButton, planet returns to default position not launched position

**Comment by samreid** [comment]
I followed the steps above and found an error in the console.  When I tried the same steps with a "pause" between steps 2-3, then it worked OK.  Based on this, I made a change that allows the state to be initialized even while not paused, and now the steps above are working for me (even without pause).

Thanks for identifying this problem @arouinfar, can you please re-test at your convenience?

**Comment by arouinfar** [comment]
Looks good in master @samreid!
