### ISSUE TITLE
Destroyed objects "explode" in launched sim

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-and-orbits#344]
**Device**
Dell
**OS**
Win 10
**Browser**
Chrome
**Problem Description**
For https://github.com/phetsims/QA/issues/505. 
When in studio, if you make objects crash together and destroy each other, then launch the sim, you will see the "explosion" animation even though the object should just be gone. This happens when you would first view the changed scene, even if you have to navigate to it after the sim is launched.
**Steps**
1. Go the first screen
2. Drag the planet into the star
3. Go to the second scene in the first screen
4. Drag that planet into the star
5. Go back to the first scene
6. Launch the sim and observe both scenes

**Visual**
![shouldexplode](https://user-images.githubusercontent.com/41024075/83805582-5f601580-a66d-11ea-8c06-09fe1c65af24.gif)

**Comment by samreid** [comment]
@arouinfar and I agreed this would be nice to fix in the next dev version, since it seems like it could impact a customized version.  However, it is unlikely that the client would want to create a customized sim that has a pre-exploded object.  So if it is difficult to solve, it could wait for RC.

**Comment by samreid** [comment]
I pushed a proposed fix, @KatieWoe can you please test in master?

**Comment by KatieWoe** [comment]
Looks fixed in master
