### ISSUE TITLE
Use DragListener instead of SimpleDragHandler and MovableDragHandler

### ISSUE THREAD

**Issue by samreid** [phetsims/gravity-and-orbits#349]
Use DragListener instead of SimpleDragHandler and MovableDragHandler.  Not necessary for dev version but would be nice for production RC.

**Comment by samreid** [comment]
After the commits, we are using DragListener for the BodyNodes and DraggableVectorNodes.  @arouinfar can you please double check that all is behaving as expected?  Please also be aware of https://github.com/phetsims/gravity-and-orbits/issues/354, ?dev now shows the draggable play area bounds and there was an issue there which I think is resolved.

**Comment by arouinfar** [comment]
> After the commits, we are using DragListener for the BodyNodes and DraggableVectorNodes.

@samreid I pulled all and cleared my cache, but I'm only seeing DragHandler under the BodyNodes and the DraggableVectorNodes in master.

For example:
![image](https://user-images.githubusercontent.com/8419308/90702228-ff2e4800-e247-11ea-8878-36fdc996a0dd.png)

That said, I haven't noticed any issues with dragging bodies/vectors.

**Comment by samreid** [comment]
In the commit, I also renamed the tandems.  @arouinfar back to you for review, please close if all is well.

**Comment by arouinfar** [comment]
It's looking good in master. Thanks @samreid.
