### ISSUE TITLE
Nest the reset buttons with the scene radio buttons

### ISSUE THREAD

**Issue by samreid** [phetsims/gravity-and-orbits#350]
From https://github.com/phetsims/gravity-and-orbits/issues/348:

> The better long-term fix would be to reimplement that code around the idea of putting the reset button as part of the radio button components (instead of parallel). That was desired for the original design, but we decided against it in order to speed up turnaround time for a dev version.

I searched for another issue about this, but couldn't find one.

**Comment by samreid** [comment]
I'd like to double check with @arouinfar before working on this.  Currently the scene reset buttons are under the `sceneControl` like so:

![image](https://user-images.githubusercontent.com/679486/90340988-0986e280-dfb9-11ea-82e2-c66408dc2d34.png)

This issue is about moving them to be children of their corresponding radio buttons, like the `planetMoonSceneResetButton` would move under `sceneControl.sceneSelectionRadioButtonGroup.planetMoonSceneRadioButton`.  But that could be confusing, since it isn't coded as a child of the `planetMoonSceneRadioButton` and making the `planetMoonSceneRadioButton` invisible will not make the `planetMoonSceneResetButton` invisible.  So I thought I should double check about what is desired here before spending time on it.

**Comment by arouinfar** [comment]
Thanks for checking in @samreid. I think it would be confusing to make the `SceneResetButton` a child of the corresponding `SceneRadioButton`. Let's leave the tree structure as-is.
