### ISSUE TITLE
Minor Pointer Area inconsistency between moon and planet model

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-and-orbits#356]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/519
Very minor. Feel free to close if it doesn't need to be addressed. On the second screen, if you have the Sun/Planet/Moon scene active and you have `?showPointerAreas` on you will see that the area for the Moon is larger than the area for the Earth. This difference seems odd to me. May have come out of other Pointer Area changes.

**Visuals**
![whymoonbigger](https://user-images.githubusercontent.com/41024075/93397969-e65d8600-f837-11ea-968b-8578dcc76d9e.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Gravity and Orbits‬
URL: https://phet-dev.colorado.edu/html/gravity-and-orbits/1.2.0-dev.16/phet/gravity-and-orbits_all_phet.html?showPointerAreas
Version: 1.2.0-dev.16 2020-09-15 16:33:11 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by samreid** [comment]
This was fine tuned in https://github.com/phetsims/gravity-and-orbits/issues/338, @arouinfar can you please advise?

**Comment by arouinfar** [comment]
@samreid I think it's fine as-is. We fine-tuned the touch areas in #338, which optimized things for the Model screen where the bodies are visible. On the To Scale screen, the objects are so small that users are likely grabbing the label.
