### ISSUE TITLE
Moon and Planet strings overlap 

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/gravity-and-orbits#357]
**Test device**

Windows 10 Laptop

**Operating System**

Windows 10

**Browser**

Chrome

**Problem description**

For https://github.com/phetsims/QA/issues/519

In the To Scale screen, with the Sun, Moon, and Planet models selected, longer strings cause an overlap of the moon and planet descriptions.

**Steps to reproduce**

1. Add the long or double query parameter
2. Enter the To Scale screen
3. Select the Sun, Moon, and Planet model group 

**Visuals**

![2020-09-16Gravity OrbitsStringOverlap](https://user-images.githubusercontent.com/54685448/93401598-24fb3c80-f848-11ea-8256-75bdc4a0400e.PNG)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Gravity and Orbits‬:‪Gravity and Orbits‬
URL: https://phet-dev.colorado.edu/html/gravity-and-orbits/1.2.0-dev.16/phet/gravity-and-orbits_all_phet.html?stringTest=double
Version: 1.2.0-dev.16 2020-09-15 16:33:11 UTC
Features missing: generatedcontent, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
Language: en-US
Window: 1536x754
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by samreid** [comment]
@arouinfar can you please comment on whether this is acceptable and, if not, how it should be corrected?

**Comment by arouinfar** [comment]
@samreid seems like the overlap would be eliminated if the maxWidth of each string is reduced by 1 px. Can you try that @samreid?

**Comment by samreid** [comment]
I had to reduce the width from 75 to 65 to get them to separate.  @arouinfar can you please review on master?

**Comment by arouinfar** [comment]
The size looks good in master, but there's a strange blue background behind the strings. Can you remove it @samreid?

![image](https://user-images.githubusercontent.com/8419308/94640337-a072da00-029b-11eb-8ae9-9174888bc0cb.png)

**Comment by samreid** [comment]
Thanks, I removed the blue background.  Ready for re-evaluation in master.  @loganbraywork can you please test if this eliminates the artifacts?

**Comment by brooklynlash** [comment]
On Windows 10 Chrome, still see this issue. 
![gaotextoverlap](https://user-images.githubusercontent.com/72031637/95614892-861bc780-0a24-11eb-85dc-13817f520eaf.PNG)

**Comment by samreid** [comment]
![image](https://user-images.githubusercontent.com/679486/95989007-ed4fc800-0de6-11eb-867c-6a1e79a56298.png)

**Comment by arouinfar** [comment]
@samreid could we instead make the indicator lines slightly different lengths? That way there could be some vertical offset in the strings.

**Comment by samreid** [comment]
I tried making the indicator lines a different length:

![image](https://user-images.githubusercontent.com/679486/96277348-5d01b680-0f91-11eb-8134-80554c540c29.png)

This feels asymmetrical to me--I'll leave a patch here in case I'm outvoted but I think we should pursue other options:

<details>

```diff
Index: js/common/view/GravityAndOrbitsSceneView.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/view/GravityAndOrbitsSceneView.js	(revision 77b688cb26bb65e5570da599b356f7c59cc3be02)
+++ js/common/view/GravityAndOrbitsSceneView.js	(date 1602861310984)
@@ -70,7 +70,7 @@
     // Use canvas coordinates to determine whether something has left the visible area
     const isReturnableProperties = [];
     bodies.forEach( body => {
-      const bodyNode = new BodyNode( body, body.labelAngle, model.isPlayingProperty, scene, tandem.createTandem( body.bodyNodeTandemName ) );
+      const bodyNode = new BodyNode( body, body.labelAngle, body.labelLength, model.isPlayingProperty, scene, tandem.createTandem( body.bodyNodeTandemName ) );
       const massReadoutNode = scene.massReadoutFactory( bodyNode, model.showMassProperty );
       this.addChild( bodyNode );
       bodyNode.addChild( massReadoutNode );
Index: js/common/model/Body.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/model/Body.js	(revision 77b688cb26bb65e5570da599b356f7c59cc3be02)
+++ js/common/model/Body.js	(date 1602861437441)
@@ -47,13 +47,14 @@
    * @param {function.<Body, number, BodyRenderer>} renderer - way to associate the graphical representation directly
    *                                                          instead of later with conditional logic or map
    * @param {number} labelAngle
+   * @param {number} labelLength
    * @param {number} tickValue - default value for mass setting
    * @param {string} tickLabel - translatable label for the mass slider labeling the default value
    * @param {GravityAndOrbitsModel} model
    * @param {Tandem} tandem
    * @param {Object} [options]
    */
-  constructor( type, bodyConfiguration, color, highlight, renderer, labelAngle, tickValue, tickLabel, model,
+  constructor( type, bodyConfiguration, color, highlight, renderer, labelAngle, labelLength, tickValue, tickLabel, model,
                tandem, options ) {
 
     options = merge( {
@@ -160,6 +161,8 @@
     this.freezeRewindChangeProperty = new Property( false );
 
     this.labelAngle = labelAngle; // @public
+
+    this.labelLength = labelLength;
     const changeRewindValueProperty = new DerivedProperty( [
         this.isPlayingProperty,
         steppingProperty,
Index: js/common/SceneFactory.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/SceneFactory.js	(revision 77b688cb26bb65e5570da599b356f7c59cc3be02)
+++ js/common/SceneFactory.js	(date 1602861746063)
@@ -422,6 +422,7 @@
       Color.white,
       getImageRenderer( spaceStationImage ),
       -Math.PI / 4,
+      50,
       earthSpaceStation.satellite.mass,
       spaceStationString,
       model,
@@ -456,6 +457,7 @@
       Color.white,
       getSwitchableRenderer( moonImage, genericMoonImage, bodyConfiguration.mass ),
       -3 * Math.PI / 4,
+      37,
       bodyConfiguration.mass,
       ourMoonString,
       model,
@@ -481,6 +483,7 @@
       Color.lightGray,
       getSwitchableRenderer( earthImage, genericPlanetImage, bodyConfiguration.mass ),
       -Math.PI / 4,
+      63,
       bodyConfiguration.mass,
       earthString,
       model,
@@ -506,6 +509,7 @@
       Color.white,
       getImageRenderer( sunImage ),
       -Math.PI / 4,
+      50,
       bodyConfiguration.mass,
       ourSunString,
       model,
Index: js/common/view/BodyNode.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/view/BodyNode.js	(revision 77b688cb26bb65e5570da599b356f7c59cc3be02)
+++ js/common/view/BodyNode.js	(date 1602861590222)
@@ -28,11 +28,13 @@
    * @param {Body} body
    * @param {number} labelAngle - Angle at which to show the name label, different for different BodyNodes so they
    *                              don't overlap too much
+   * @param {number} labelLength - Angle at which to show the name label, different for different BodyNodes so they
+   *                              don't overlap too much
    * @param {Property.<boolean>} isPlayingProperty is the simulation playing?
    * @param {GravityAndOrbitsScene} scene
    * @param {Tandem} tandem
    */
-  constructor( body, labelAngle, isPlayingProperty, scene, tandem ) {
+  constructor( body, labelAngle, labelLength, isPlayingProperty, scene, tandem ) {
     super( {
       cursor: 'pointer',
       tandem: tandem,
@@ -150,7 +152,7 @@
     const viewCenter = new Vector2( 0, 0 );
     const northEastVector = Vector2.createPolar( 1, labelAngle );
     const tip = northEastVector.times( 10 ).plus( viewCenter );
-    const tail = northEastVector.times( 50 ).plus( viewCenter );
+    const tail = northEastVector.times( body.labelLength ).plus( viewCenter );
 
     node.addChild( new Line( tail.x, tail.y, tip.x, tip.y, { stroke: GravityAndOrbitsColorProfile.arrowIndicatorProperty } ) );
     const labelNode = new Text( body.labelString, {

```

</details>

Other options to investigate:
1. Reduce the width on the strings a little more
2. Change the angle of the indicator lines from 45 degrees to 30 degrees
3. Make all the indicator lines a little longer

**Comment by samreid** [comment]
I tested (3) above.  The default line extension was 50.  I changed it to 60 and with stringTest=long it looks like this:

![image](https://user-images.githubusercontent.com/679486/96278027-38f2a500-0f92-11eb-9471-0efb9a7fc7e2.png)

That seems preferable of the options listed, so I'll commit and ask for review on the Windows 10 Chrome @brooklynlash reported.

**Comment by samreid** [comment]
@brooklynlash or @KatieWoe can you please re-test after the commit?

**Comment by brooklynlash** [comment]
@samreid Unsure why it still does not work on my computer. I am on the latest version of Chrome on a 15 inch Lenovo laptop. 
![grav1](https://user-images.githubusercontent.com/72031637/96280095-cd5e0700-0f94-11eb-9e5c-e9696cdfc8c1.PNG)
![grav2](https://user-images.githubusercontent.com/72031637/96280252-f7afc480-0f94-11eb-80ef-d7cf8eca9328.PNG)

**Comment by samreid** [comment]
Thanks for testing, it looks like it is a little better.  Let's try 70 next.

**Comment by samreid** [comment]
I increased it to 70, can you please re-test?

**Comment by brooklynlash** [comment]
No change, unfortunately.

**Comment by samreid** [comment]
Can you please make sure it is not cached following one or more of these strategies?

1. Clear the browser cache
2. Run with dev tools open and "Disable cache (while DevTools is open) selected

**Comment by brooklynlash** [comment]
![grav3](https://user-images.githubusercontent.com/72031637/96282252-b5d44d80-0f97-11eb-9026-f6bce0f33958.PNG)
Cleared cache on my browser and still looks like this. New to this so also unsure if I am missing something.

**Comment by brooklynlash** [comment]
![grav4](https://user-images.githubusercontent.com/72031637/96283354-5414e300-0f99-11eb-9a90-1b9553ec3b71.PNG)
What it looks like in the dev website. Looks like 60 or 70 would work. 
@samreid

**Comment by samreid** [comment]
@arouinfar can you please take a look and advise?

**Comment by arouinfar** [comment]
I'm not sure what angle is currently in master, but it looks good to me. Let's go with that @samreid.

Here's what it looks like with `stringTest=long`
![image](https://user-images.githubusercontent.com/8419308/96671850-10670400-1320-11eb-821f-0fbff24f39d3.png)

**Comment by samreid** [comment]
OK, leaving master as it is, and closing.
