### ISSUE TITLE
Use PhetColorScheme for vectors

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gravity-and-orbits#360]
In https://github.com/phetsims/scenery-phet/issues/621 we modernized the color used for velocity. 

This sim is using currently using the deprecated PhetColorScheme.RED_COLORBLIND for velocity, see https://github.com/phetsims/gravity-and-orbits/blob/master/js/common/view/GravityAndOrbitsSceneView.js#L67.

@samreid please update the velocity fill to PhetColorScheme.VELOCITY.

**Comment by samreid** [comment]
Fixed in the play area and control panel, and ready for review.

**Comment by arouinfar** [comment]
The green looks good to me @samreid.

It looks like the gravitational force uses `rgb( 50, 130, 215 )` which is the same as PhetColorScheme.GRAVITATIONAL_FORCE. It might be nice to update it so it's using PhetColorScheme too.

**Comment by samreid** [comment]
I switched to use `PhetColorScheme.GRAVITATIONAL_FORCE` in the commit.  Ready for review.

**Comment by arouinfar** [comment]
👍
