### ISSUE TITLE
Measuring Tape does not move in State wrapper

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-and-orbits#362]
For https://github.com/phetsims/QA/issues/519. Found on ChromeOS.
In the State wrapper, the bottom wrapper does not move the measuring tape when it is moved in the top sim. The tape does appear when checked, but does not change position or lengthen/shorten/rotate.
![Screen Shot 2020-10-15 at 4 30 02 PM](https://user-images.githubusercontent.com/41024075/96193447-69403200-0f05-11eb-810d-62ebd4d9d83e.png)

**Comment by samreid** [comment]
I instrumented the measuring tape positions, please see the commit or studio for the tandem names.  @arouinfar can you please review and test (including but not limited to reviewing the tandem names)?

**Comment by arouinfar** [comment]
Things seem to be working in the state wrapper. From the commit, it looks like the new tandem names are `measuringTapeStartPointProperty` and `measuringTapeEndPointProperty`. I don't see them in the studio tree (cleared the cache, pulled all, viewing all Elements), but I'm not sure if I should or not.

![image](https://user-images.githubusercontent.com/8419308/96672433-815aeb80-1321-11eb-831a-3507a59cb850.png)

**Comment by samreid** [comment]
Those are the correct tandem names, but those model properties are instrumented in the view, such as:

````
gravityAndOrbits.modelScreen.model.starPlanetMoonScene.measuringTapeEndPointProperty
```

Does that sound good to you?  Or should we switch it to something more like:

```
gravityAndOrbits.modelScreen.model.starPlanetMoonScene.measuringTape.endPointProperty
```

**Comment by arouinfar** [comment]
Thanks for the clarification @samreid.

If it's not too troublesome, I think it would be nice to nest things under `model.measuringTape` like:

```
model
   measuringTape
        endPointProperty
        startPointProperty
```

**Comment by samreid** [comment]
It was not too troublesome.  It's pushed and ready for review.

**Comment by arouinfar** [comment]
Looks good in master, thanks @samreid.

**Comment by KatieWoe** [comment]
Looks good in rc.2
