### ISSUE TITLE
There are 18 instances of gravityVectorNode.pickableProperty that seem unnecessary.

### ISSUE THREAD

**Issue by samreid** [phetsims/gravity-and-orbits#363]
Related to https://github.com/phetsims/scenery/issues/1047 and https://github.com/phetsims/scenery/issues/1046.  In slack @kathy-phet said:

> Can @arouinfar review the changes to button and enabledproperty and opacityproperty and visibleproperty as they are relevant to GAO before we go to RC-lite?

@arouinfar can you please review Gravity and Orbits Node sub-properties such as `visibleProperty`, `opacityProperty`, `pickableProperty`, `textProperty`

**Comment by arouinfar** [comment]
* There are no instances of `opacityProperty`, as I would expect.
* There are 18 instances of `gravityVectorNode.pickableProperty` that seem unnecessary. I double checked my notes for phetioFeatured as well as the overrides history, and I don't think `gravityVectorNode.pickableProperty` was ever featured, so it seems like it was mistakenly given a pickableProperty in https://github.com/phetsims/scenery/issues/1047. Perhaps all vectors were given a pickableProperty, but it's only desirable for the velocityVector. If it's not feasible to uninstrument the pickableProperty of the gravity vectors, I will need to unfeature them in the overrides.
* It is unclear what exactly I need to review in regards to `visibleProperty` and `textProperty`, but searching for either results in the same number of hits as 1.2.0-dev.10 which was QA tested ~5 months ago. It doesn't seem like anything has changed recently. Please let me know if there is something more specific I need to look at.
* The quoted comment mentions buttons and `enabledProperty` but from the Slack discussion https://github.com/phetsims/sun/issues/515 is still in progress. I don't know enough about that issue to know if it should be blocking or what exactly needs designer review, so we should probably discuss it at phet-io meeting.

**Comment by samreid** [comment]
Thanks, the button enabledProperty will be reviewed in another issue when ready.  Leaving self-assigned to work on `pickableProperty` for Gravity and Orbits.

**Comment by samreid** [comment]
I uninstrumented `gravityVectorNode.pickableProperty`.  Ready for review, at high priority since this is one of the last issues before RC-lite.

**Comment by arouinfar** [comment]
Looks good in master @samreid!
