### ISSUE TITLE
incorrect alignment of "Clear" button?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gravity-and-orbits#364]
From https://github.com/phetsims/QA/issues/572#issuecomment-719880346

@ariel-phet noted that the alignment of the "Clear" button seems to have regressed.

Gravity and Orbits (Published)
![gao published](https://user-images.githubusercontent.com/4051174/97771423-67c85980-1b02-11eb-8e16-2fcd7554b058.PNG)

Gravity and Orbits (Master)
![gao master](https://user-images.githubusercontent.com/4051174/97771426-7151c180-1b02-11eb-807e-7dd44e1f0bbd.PNG)

The change in "look" is OK for now.  It's due to sun buttons now using opacity instead of grayscale to denote "disabled".

**Comment by samreid** [comment]
The alignment was purposefully changed in https://github.com/phetsims/gravity-and-orbits/issues/359, please comment there if you prefer a different strategy.
