### ISSUE TITLE
TimeControlNode changes?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gravity-and-orbits#365]
From https://github.com/phetsims/QA/issues/572#issuecomment-719880346, and similar to https://github.com/phetsims/wave-interference/issues/506.  It's unlikely that this is related to sun button changes, and more likely related to changes to TimeControlNode.

@ariel-phet noted that TimeControlNode layout and sizing differs between published and master. If this is a know (or acceptable) regression, that's fine.  

GAO published (1.1.5):
<img width="542" alt="screenshot_643" src="https://user-images.githubusercontent.com/3046552/97906246-91e76a80-1d00-11eb-8d0f-ea9c1c4ea144.png">

GAO master:
<img width="567" alt="screenshot_644" src="https://user-images.githubusercontent.com/3046552/97906251-9449c480-1d00-11eb-9652-8b41bd6ea9ed.png">

The change in "look" of disabled buttons is OK for now. It's due to sun buttons now using opacity instead of grayscale to denote "disabled".

**Comment by samreid** [comment]
This change is likely due to conversion to use TimeControlNode.  That seems reasonable to me, but please reopen if changes are recommended.
