### ISSUE TITLE
Icons and screenshots may need to be retaken

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-and-orbits#366]
**Test device**
MacBook Air
**Operating System**
10.15.7
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/567
I noticed that the velocity arrow is now a different color (now green instead of red). However, the icon for the second screen on the home page and in the nav bar still shows the arrow as red. I also noticed that the changes to the color of inactive buttons means that screenshots may need to be changed.

**Visuals**
![Screen Shot 2020-11-03 at 3 41 38 PM](https://user-images.githubusercontent.com/41024075/98049122-5033ee00-1dec-11eb-804d-d8bcec0c89e7.png)
![Screen Shot 2020-11-03 at 3 41 48 PM](https://user-images.githubusercontent.com/41024075/98049126-51651b00-1dec-11eb-8f76-e3950fc9ad41.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Gravity and Orbits‬
URL: https://phet-dev.colorado.edu/html/gravity-and-orbits/1.2.0-rc.2/phet/gravity-and-orbits_all_phet.html
Version: 1.2.0-rc.2 2020-11-02 23:34:16 UTC
Features missing: applicationcache, applicationcache, touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36
Language: en-US
Window: 1306x685
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by samreid** [comment]
The screen icons are checked in to mipmaps/ rather than generated.  @arouinfar can you please take the lead on this?

**Comment by arouinfar** [comment]
@samreid I updated the screen icons and cleaned them up a bit. The .ai assets currently checked in for the icons (cartoon_icon.ai and to_scale_icon.ai) have a weird encoding issue and look like text files when trying to open them up in Illustrator. Luckily, I had a local copy from when they were originally created that didn't have this issue. I am going to delete the old .ai files and upload the new screen icons as a single file, screen_icons.ai. I'm not sure why the .png versions of the icons aren't currently checked in. I'm not 100% where those should go, so attaching them here instead: 
[model-screen-icon](https://user-images.githubusercontent.com/8419308/98144146-43b0a380-1e87-11eb-9415-d65a2a5b5923.png)
[to-scale-screen-icon](https://user-images.githubusercontent.com/8419308/98144149-44493a00-1e87-11eb-96f5-753f558b54b0.png)

**Comment by arouinfar** [comment]
Okay, scratch that, screen-icons.ai comes in at a whopping 43MB which is too big to commit through the GitHub web interface and doesn't zip small enough to attach to the issue. The large file size is due to the image of the Earth used in the icons. I don't want to compress it down because it could compromise the quality in the exported images. @samreid I've temporarily uploaded the screen icons to the sim design folder on Drive. I'm assuming there shouldn't be a file size issue if you commit it from your local machine.
https://drive.google.com/file/d/1nt7D0RGT3txOcgvj1-_fDFU87mcwUHjp/view

**Comment by arouinfar** [comment]
I was able to reduce the source image of the Earth down to 2.6 MB, resulting in a final .ai size of 10.2 MB. @samreid here are the updated assets. 
[screen-icons-reduced-size.zip](https://github.com/phetsims/gravity-and-orbits/files/5490587/screen-icons-reduced-size.zip)

**Comment by arouinfar** [comment]
I updated the screenshots in master and the 1.2 branch in the above commits.

**Comment by samreid** [comment]
Thanks! I will run `grunt modulify` to produce the JS assets.  Also, I think the next version will take SHAs from master and go forward as 1.3

**Comment by samreid** [comment]
I pushed the icons in the commit, @arouinfar can you please check that they are correct?

**Comment by arouinfar** [comment]
Looks great @samreid!

**Comment by samreid** [comment]
Thanks, closing.
