### ISSUE TITLE
Existing Path does not show up in first state setting

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-and-orbits#367]
For https://github.com/phetsims/QA/issues/576. Mac 10.15 Chrome. Found in new version of State wrapper. Assigning @zepumph as well, in case this is related to wrapper.

When on the state wrapper, the first time the state is set when there is an existing path line, that line does not show up in the resulting sim. Any subsequent time, the whole path line shows up.

Steps:
1. Refresh the page
2. Set State Rate to 0
3. On top sim, go to one of the screens and turn on path
4. Play top sim to create a visible path
5. Press Set State Now button and observe bottom sim

![pathinstatewrapper](https://user-images.githubusercontent.com/41024075/99309643-03eaa400-2817-11eb-8a02-39c0edf8098c.gif)

**Comment by brooklynlash** [comment]
Replicated on Windows 10 Chrome.

**Comment by samreid** [comment]
I added a commit which corrects the problem in my testing.  @KatieWoe can you please test on phettest?

**Comment by KatieWoe** [comment]
Looks fixed in master

**Comment by samreid** [comment]
I cherry picked the commit to the 1.3 branch.  It will be ready for spot testing in the next RC.

**Comment by samreid** [comment]
@KatieWoe identified a problem with the fix--when clicking "play" then "path" it doesn't show the path from the time clicked, but from the beginning of time.  This should be fixed before next rc.  Self-assigning.

**Comment by samreid** [comment]
I committed a fix for this to master.  @KatieWoe can you please test in master?  If it seems OK, I'll cherry pick it to the RC branch for next RC.

**Comment by KatieWoe** [comment]
Looks good from what I can tell on master.

**Comment by samreid** [comment]
I cherry-picked the change to the 1.3 branch and tested, could not find any problems.  Leaving open for confirmation in next RC.

**Comment by arouinfar** [comment]
@samreid this looks fixed in 1.3.0-rc.3. I tested on macOS 10.15.7 Chrome/Safari in both the State Wrapper and launching from Studio. The state of the path was correct every time.
