### ISSUE TITLE
Moving text jiggles

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-and-orbits#368]
**Test device**
MacBook
**Operating System**
11.0.1
**Browser**
Safari
**Problem description**
For https://github.com/phetsims/QA/issues/576. Not seen on Chrome. Didn't really see on my 10.15.7 Safari, but it may be due to screen resolution. I did see it in the published sim.
I noticed that text that moves around to follow orbiting objects jiggled around and the spaces between letters and numbers jiggled as well.
**Steps to reproduce**
1. Go to the second page
2. Use planet/moon scene
3. Make the masses visible
4. Increase planet mass as much as possible
5. Press play and watch planet mass

**Visuals**
![jiggletext](https://user-images.githubusercontent.com/41024075/99465524-dd506a00-28f7-11eb-8eb2-78630b0a6123.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Gravity and Orbits‬
URL: https://phet-dev.colorado.edu/html/gravity-and-orbits/1.3.0-rc.2/phet/gravity-and-orbits_all_phet.html
Version: 1.3.0-rc.2 2020-11-14 17:28:31 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15
Language: en-us
Window: 1355x860
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by arouinfar** [comment]
I tested on macOS 10.15.7, and I see the wobbly kerning in Safari 14, but not in Chrome or Firefox. It's present in the latest published version as well as this rc. I think this is a relatively minor issue, and should not block the upcoming phet-io publication. I'm fine with closing, but I'll leave it up to @samreid to decide the next steps.

**Comment by samreid** [comment]
It seems possible to rasterize the text, but that would probably cause more problems than it solves.  I think we should close and hold out hope that Safari will one day render the text better.
