### ISSUE TITLE
Client guide does not include Sun pickable property

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-and-orbits#369]
For https://github.com/phetsims/QA/issues/576
One of the client instructions is:
>To prevent a body from being moved, set its pickableProperty to false.

In the model screen section, the starPlanetMoon scene does not include a Star option in the section. It does exist in Studio as `gravityAndOrbits.modelScreen.view.playAreaNode.starPlanetMoonSceneView.starNode.pickableProperty`. The To Scale section does include all 9 options.
<img width="647" alt="pickable" src="https://user-images.githubusercontent.com/41024075/100163851-d2f01c00-2e73-11eb-910e-ecd3ced35d31.png">

**Comment by arouinfar** [comment]
Nice find @KatieWoe!

Fixed in master, off to @samreid for cherry-picking.

**Comment by samreid** [comment]
Since this is from another repo, I'll wait to see if there are other cherry-picks to do at the same time, once testing is complete.

**Comment by samreid** [comment]
OK I cherry picked this.

**Comment by arouinfar** [comment]
Looks good in 1.3.0-rc.3 @samreid

**Comment by samreid** [comment]
Thanks, closing.
