### ISSUE TITLE
User reported orbit inconsistencies between speeds

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-and-orbits#373]
Email to phethelp reads:
> To begin, I love your simulations and I use them in both my Earth & Space and Chemistry classes.  One of my students did make an observation in the gravity and orbit simulation that made me wonder if there may be a "calculation" problem.  Referring to the screenshot below, if you run the sim in fast forward, Normal or slow motion you get different planetary path results.  I expected the same results but viewed over longer or shorter lengths of time. The student was simulating "normal mass" but was asked to reduce the velocity of the planet.
Depending on the speed of the simulation, the planet's path differs.

![image](https://user-images.githubusercontent.com/41024075/102268449-947cd880-3ed8-11eb-9555-c70066c4255d.png)

I reproduced using the above settings and did see some difference between speeds:
Slow:
![slow](https://user-images.githubusercontent.com/41024075/102268567-bb3b0f00-3ed8-11eb-81d5-303389820c99.gif)
Normal:
![normalspeed](https://user-images.githubusercontent.com/41024075/102268607-c726d100-3ed8-11eb-8bbf-72773991e15d.gif)
Fast:
![fastforward](https://user-images.githubusercontent.com/41024075/102268656-d148cf80-3ed8-11eb-8da7-374759b93504.gif)

**Comment by oliver-phet** [comment]
Removing my assignment for now. Feel free to reassign if we need to communicate back with the user.

**Comment by jessegreenberg** [comment]
This looks exactly like https://github.com/phetsims/gravity-and-orbits/issues/253, which @samreid fixed. So I think this is going to be resolved when this sim is redeployed. But @samreid can you please confirm?

**Comment by samreid** [comment]
Yes, I think that will be fixed in the upcoming deploy.  Leaving open until a new version is out, to help us remember to notify the client.

**Comment by KatieWoe** [comment]
This looks fixed in rc.1. Will reopen if something comes up.
