### ISSUE TITLE
Publish Gravity and Orbits PhET/PhET-iO 1.4

### ISSUE THREAD

**Issue by samreid** [phetsims/gravity-and-orbits#374]
For milestone https://github.com/phetsims/gravity-and-orbits/milestone/3

As mentioned in https://github.com/phetsims/gravity-and-orbits/issues/372#issuecomment-748389357

> It's unclear whether we will want to take new shas from master or try to cherry pick things like this into the branch.

**Comment by samreid** [comment]
Gravity and Orbits 1.3 SHAs were taken Nov 14, how can I determine if there were important bugfixes made to common code repos since then, so I can see if they need to be cherry-picked?  Or would it be better to take shas from master?

**Comment by ariel-phet** [comment]
@samreid I would recommend revisiting with the dev team at our meeting on Jan 7, and if master seems reasonably stable, taking new SHA's at that point and doing a full retest as the sim is unlikely to get any QA attention until that point anyhow. I think especially with iO, regularly doing some full testing from master (every couple of months) is generally a healthy practice for evaluating the state of the code.

**Comment by samreid** [comment]
In dev meeting, we agreed to use master SHAs.

SR: On Dec 8, @kathy-phet said our client could wait until Jan or Feb for GAO to go through full RC.
SR: I’d prefer to go with master if QA has time and we are not backlogged
AP: The QA should be able to get to it in this timeline.  Let’s go with master.
Go with master because of Pan-and-Zoom + PhET-iO support

**Comment by samreid** [comment]
In discussion today, @kathy-phet asked what kind of testing we should start with.  She recommends dev testing first, but @samreid said we would like to have SHAs.  Can we create an RC and do "dev testing" on it?  That seemed reasonable to everyone.  

@pixelzoom said we could use the RC-lite process.  That is sort of similar to dev testing.

@samreid: If QA does RC lite testing, do they know that doesn't need to be tested for full RC?
@ariel-phet: That sounds reasonable

**Comment by samreid** [comment]
I opened a placeholder QA issue here: https://github.com/phetsims/QA/issues/595

**Comment by samreid** [comment]
RC2 will be tracked in https://github.com/phetsims/QA/issues/623

**Comment by samreid** [comment]
1.4.0 was published.  Assigning to @arouinfar to see if there are any post-publication steps.  Please close if there's nothing else to do.

**Comment by arouinfar** [comment]
I should update the teacher tips, but that's being tracked in #325, so we can close this issue.
