### ISSUE TITLE
Paths don't fade out when objects are destroyed

### ISSUE THREAD

**Issue by DevonQui** [phetsims/gravity-and-orbits#377]
**Test device**
MacBook Pro

**Operating System**
11.2.1

**Browser**
Safari

**Problem description**
This is for https://github.com/phetsims/QA/issues/595

It's not a particularly egregious bug, but I noticed that the paths of destroyed objects/planets after colliding do not disappear. They just stay there forever until the simulation scene is restarted. 

**Steps to reproduce**
1. Open the simulation
2. Open the "Model" section of the simulation (although, this will work for both sections)
3. Enable the "path" option on the right hand side
4. Click the play button on the simulation
5. Now intentionally destroy one of the objects/planets once a path has had time to develop
6. Let the sim continue and notice how the path doesn't disappear
**Visuals**
<img width="793" alt="Screen Shot 2021-03-02 at 11 53 26 AM" src="https://user-images.githubusercontent.com/72042459/109699771-357d4600-7b4e-11eb-9d9a-5b1d59fd9b3f.png">

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Gravity and Orbits‬
URL: https://phet-dev.colorado.edu/html/gravity-and-orbits/1.4.0-rc.1/phet/gravity-and-orbits_all_phet.html
Version: 1.4.0-rc.1 2021-01-28 19:09:23 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15
Language: en-us
Window: 1440x792
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

**Comment by samreid** [comment]
In the commit, I made it so that collided body paths still animate.  The "fade out the tail" code only supports non-collided bodies though, so the tail for the collided bodies looks truncated like so:

![image](https://user-images.githubusercontent.com/679486/110552802-2faad600-80f5-11eb-89ed-d8011fa6cd37.png)

I did not see an easy, obvious way to keep the continuous fade trail for collided bodies (it depends on how far the body das traveled), but I wasn't sure it was worth the effort to develop one.  @arouinfar can you please advise?

**Comment by arouinfar** [comment]
@samreid the behavior in master looks strange to me. For example: 

1. Model Screen, Star/planet/moon scene, Path on
2. Start the system, and let it go for a few days
3. Maximize planet mass and the moon will be destroyed
4. Moon path remains static until the planet reaches ~75% of the orbit around the sun, at which point both paths start to fade
5. Moon path doesn't entirely disappear, it leaves behind a magenta dot
![image](https://user-images.githubusercontent.com/8419308/111668639-91e19600-87db-11eb-9752-229a999d0e0f.png)

The behavior in steps 4/5 seems really weird to me. The moon path fading seems random, and it's hard to understand why it was triggered. I don't think it's worth the time investment to clean it up.

I compared the rc behavior to 1.0.0 and 1.1.15 (latest), and it's the same. The path of the destroyed object does not disappear or fade away. It's not the most beautiful thing in the world, but the path serves as a history of the destroyed object.

@samreid please revert the change.

**Comment by samreid** [comment]
I reverted the change, and will not cherry-pick into the RC.  Should this issue remain open in case we want to improve steps 4-5 in a future version?

**Comment by arouinfar** [comment]
Thanks @samreid. I think this is a fairly minor issue, so I'm more inclined to close as wontfix.
