### ISSUE TITLE
Only one scene listed to "Hide Earth Days"

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-and-orbits#379]
For https://github.com/phetsims/QA/issues/595.
In the Client Requests guide, the client wants to hide the Earth Days counter. Only one scene is listed for this. However, two other scenes have Earth Days, and one other has Earth Minutes. Should these be listed too?
<img width="683" alt="onlyonescene" src="https://user-images.githubusercontent.com/41024075/110164825-277a3000-7daf-11eb-8190-c340025ca432.png">

**Comment by arouinfar** [comment]
Nice catch @KatieWoe!

I added the missing phetioIDs for the other scenes to the client guides and committed the changes to master and gravity-and-orbits-1.3.

**Comment by samreid** [comment]
I labeled this for the milestone and will mark it qa ready for review for testing in the next RC.

**Comment by samreid** [comment]
I noticed the commit is on the 1.3 branch, but we are publishing the 1.4 branch.

**Comment by samreid** [comment]
Tagging for testing as part of https://github.com/phetsims/QA/issues/623

**Comment by brooklynlash** [comment]
Looks good on rc.2
