### ISSUE TITLE
Loading saved studio state may not work on Safari

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-and-orbits#380]
For https://github.com/phetsims/QA/issues/595. In studio, if you save a studio state, and then try to load in in studio on Safari it does not seem to do anything. The same file does seem to work in Chrome and Firefox. However, after trying several times, I did find that Safari would load the file sometimes, but there did not seem to be a set pattern to it.

**Comment by samreid** [comment]
It seems that safari requires the input type=file to be in the DOM.

**Comment by samreid** [comment]
I added the file input to the DOM and now it is working reliably on Chrome and Safari.  Since our old implementation was creating and throwing away listeners, it masked another cleanup problem with `window.phetio.phetioClient.isSettingState` which I corrected in this version.  @zepumph can you please review?  If it checks out, please reassign to @KatieWoe to test in master.  If all that goes well, we can cherry pick this into the next Gravity and Orbits RC, or determine if it needs to be maintenance patched to other RCs.

**Comment by KatieWoe** [comment]
On master on MacOS 11 Safari, the first load seemed to work, but any subsequent attempts did not. I also wasn't able to open the saved files as a sim.

**Comment by samreid** [comment]
@KatieWoe and I met on a zoom call and confirmed that subsequent loads are not working in Safari or Chrome. Perhaps the single DOM file input isn't triggering a change after files change?

**Comment by samreid** [comment]
> @KatieWoe and I met on a zoom call and confirmed that subsequent loads are not working in Safari or Chrome. 

Testing today, I can see that subsequent loads are working correctly on my local/master and https://bayes.colorado.edu/dev/phettest/studio/?sim=gravity-and-orbits&phetioDebug&phetioElementsDisplay=all

**Comment by KatieWoe** [comment]
It still isn't working for me. Same problem as last time

**Comment by kathy-phet** [comment]
Please reconnect and see if you can figure out the steps to reproduce again.

**Comment by samreid** [comment]
@KatieWoe and I determined the problem is only when loading the same file twice.  I'll take a look.

**Comment by samreid** [comment]
In the commit, I null out the value on every click to make sure we still get a notification when selecting the same file.  I tested this in Chrome, Safari and with a touch device simulator.  It worked OK in all cases.  @KatieWoe can you please verify?  If it seems OK, I'll cherry pick it to the RC branch.

**Comment by zepumph** [comment]
Good idea!

**Comment by samreid** [comment]
Aside from @KatieWoe testing, this is also ready for code review.  @zepumph can you please take a look?

**Comment by KatieWoe** [comment]
Looks fixed on master.

**Comment by zepumph** [comment]
The change looks simple, suave, and nice. I might recommend adding the click listener in studio js code, just so that it is clearer that this logic is needed, and why. Perhaps above the current logic?

```diff

Index: index.html
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/index.html b/index.html
--- a/index.html	(revision 0c675eb47ef96c242182b5e5c5ab26bbe602a10a)
+++ b/index.html	(date 1615946379607)
@@ -80,7 +80,7 @@
 
           <!-- Null out the value on every click so that we still get a change notification even if the same file is selected,
           ----see https://stackoverflow.com/questions/4109276/how-to-detect-input-type-file-change-for-the-same-file-->
-          <input type="file" id="file-input" style="display:none" onclick="this.value=null;"/>
+          <input type="file" id="file-input" style="display:none"/>
           <br>
           <h4 class="heading-title">HTML Output</h4>
 
Index: js/customizeWrapperTemplateForAction.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/customizeWrapperTemplateForAction.js b/js/customizeWrapperTemplateForAction.js
--- a/js/customizeWrapperTemplateForAction.js	(revision 0c675eb47ef96c242182b5e5c5ab26bbe602a10a)
+++ b/js/customizeWrapperTemplateForAction.js	(date 1615946350435)
@@ -229,4 +229,7 @@
 }, false );
 
 // Load in a previously saved file.
-document.getElementById( 'load-button' ).addEventListener( 'click', () => fileInput.click() );
\ No newline at end of file
+document.getElementById( 'load-button' ).addEventListener( 'click', () => {
+  document.getElementById( 'load-button' ).value = null;
+  fileInput.click();
+} );
\ No newline at end of file

```

Or do you need a separate listener? In that case, it would definitely be better to put it right next to that listener and document the relationship.

Otherwise it is great.

**Comment by samreid** [comment]
I adopted the patch from above (with a bugfix) and tested that it works well, thanks for the recommendation!  I'll cherry pick this for RC.2.

**Comment by samreid** [comment]
Tagging for testing as part of https://github.com/phetsims/QA/issues/623

**Comment by liam-mulhall** [comment]
To test this for https://github.com/phetsims/QA/issues/623, I changed `simNameProperty`. When you first open the modified file, it shows the old sim name for a second, and then it changes to the modified sim name.

**Comment by samreid** [comment]
The "flicker' of the old values before the new values are populated is a known issue with a proposed solution documented in https://github.com/phetsims/phet-io/issues/1337.

**Comment by KatieWoe** [comment]
I think this can be closed. Will reopen if something comes up
