### ISSUE TITLE
Sim may not load on android app

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-and-orbits#382]
For https://github.com/phetsims/QA/issues/595.
When trying to use the sim on the debug version of the android app (Galaxy Tablet) the sim did not load. The PhET loading menu appeared, but it never started to fill in. I waited a few minutes before giving up.

**Comment by KatieWoe** [comment]
Should we pair to try and figure it out?

**Comment by samreid** [comment]
Does this happen on any other sims?  How much memory does the Galaxy Tablet have?  What year is it?

**Comment by KatieWoe** [comment]
I hadn't seen it in other sims when testing the app last week. 623 MB free. Galaxy Tab A SM-T580, can't seem to find a year.

**Comment by mattpen** [comment]
https://www.gsmarena.com/samsung_galaxy_tab_a_10_1_(2016)-8090.php

Looks like 2GB @samreid

**Comment by samreid** [comment]
Thanks, should this issue block publication of the upcoming RC.2?

**Comment by kathy-phet** [comment]
Does the website version of GAO work? Does the built version on phettest work? Which version exactly isn't working?

**Comment by samreid** [comment]
We measured https://phet-dev.colorado.edu/html/gravity-and-orbits/1.4.0-rc.1/phet/gravity-and-orbits_all_phet.html at around 28MB--not too high, so memory may not be the problem.

**Comment by mattpen** [comment]
@KatieWoe - Here are instructions for connecting an android device to the Chrome Developer Tools: https://developers.google.com/web/tools/chrome-devtools/remote-debugging

Can you check the console for any errors?  Let me know if you need help setting up the remote debugging.

**Comment by KatieWoe** [comment]
Noting that, during troubleshooting, we saw that https://github.com/phetsims/QA/issues/603 was impacted by this.

**Comment by samreid** [comment]
The commit makes it possible for the sim to load on the Android app. @KatieWoe confirmed that https://phet-dev.colorado.edu/html/gravity-and-orbits/1.5.0-dev.1/phet/gravity-and-orbits_en_phet.html launched correctly (though now it has the wrong font).

**Comment by samreid** [comment]
I reached out to @jonathanolson on slack:

> Hi Jonathan, Katie and I discovered a font problem that only affects Android sims running in the apps.  I thought you would have the most expertise in the area (fonts and fallbacks).  Can you take a look?  Want a voice meeting?  Katie and I just ended a call but could rejoin if you want to touch base.

**Comment by KatieWoe** [comment]
@mattpen it looks like we may have a solution, but in the future, is there a way to get console errors in the app, rather than in a chrome tab? We only saw the bug in the app and the method described above only seems to open a console for a browser tab, at least from what we could see.

**Comment by samreid** [comment]
I asked on Slack

> We tracked https://github.com/phetsims/gravity-and-orbits/issues/382 to be a font problem.  If we want to take a shortcut to unblock the RC testing, we could put code that says “on android, use ‘monospace’ font”, everywhere else, use the preferred font list.  Or it could be a few days to investigate why the font is failing and look for an alternate solution.  What do you recommend?

@kathy-phet replied:

> Put in the shortcut to unblock. But it would be good to do the tests to figure out what is going on so we can understand for future sim deployments. Is the device Katie has popular

**Comment by mattpen** [comment]
@KatieWoe the solution I posted can be used to get console output from the app. It uses a Chromium webview, so it will show up when you go the device inspector screen. Happy to help with setup if needed, just ping me on slack.

**Comment by samreid** [comment]
Getting a debugger would be the best way to understand how the font is failing. In case we need a shortcut to get RC.2 going, I added a commit that uses 'monospace' for the time readout when the android query parameter is present.  Here is a dev version with that change, which can be tested on the tablet:
https://phet-dev.colorado.edu/html/gravity-and-orbits/1.5.0-dev.2/phet/gravity-and-orbits_en_phet.html

@KatieWoe can you please test and let me know if that is running OK?  If so, I can cherry pick that commit to the RC branch for RC2.

**Comment by KatieWoe** [comment]
Got the debugger to work and got this error message with it:
<img width="629" alt="consoleerror" src="https://user-images.githubusercontent.com/41024075/111512939-e589ac00-8715-11eb-8263-79c7221b184c.png">
This was for the rc.2 version.
I was able to open and load the dev.2 version linked above just fine.

**Comment by samreid** [comment]
That looks like the same problem as https://github.com/phetsims/phet-android-app/issues/155, I should investigate and make sure the RC has the patch.

**Comment by jessegreenberg** [comment]
Sorry to have caused wasted time in this issue, please see https://github.com/phetsims/scenery-phet/issues/674#issuecomment-801334462, and I expect this to be fixed in rc.2.

**Comment by samreid** [comment]
Tagging for testing as part of https://github.com/phetsims/QA/issues/623

**Comment by samreid** [comment]
In https://github.com/phetsims/scenery-phet/issues/674#issuecomment-803017481 we determined the font was a red herring, so we can roll back the workaround.  We can even do a maintenance release for it, if we don't want to use "monospace" on the Android app.

**Comment by KatieWoe** [comment]
This looks good in rc.3
