### ISSUE TITLE
PhET-iO: Instrument the separators in the control panel

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/gravity-and-orbits#384]
Sometime after @arouinfar and I reviewed this sim, we standardized on instrumenting the separators so customization could include their removal (see Molecule Polarity). Names are "separator 1" and "separator 2" with only visible property instrumented. 

@samreid - Can you add this to these GAO panels where separators are present? I noticed in a demo that I could not hide them. Thanks! (We will want to cherry pick that into the rc).

**Comment by samreid** [comment]
I'll add this for RC.2 but will also point out that the proposed layout engine prototype has a new feature that automatically hides separators when appropriate (if there is nothing to separate, or if >1 separators are adjacent), as part of https://github.com/phetsims/sun/issues/48

**Comment by kathy-phet** [comment]
OK, but for now, we should do this as the standard.

**Comment by samreid** [comment]
Agreed, I don't think the layout engine will be ready for production in time, but I'm excited that it's on the horizon.

**Comment by samreid** [comment]
In the commit, I converted the sim to use HSlider (it was formerly using Rectangles) and added PhET-iO instrumentation.  I checked that the behavior seemed similar to molecule polarity.  @kathy-phet or @arouinfar can you please test this in master on phettest?  If it seems good, I will cherry pick it to the branch for RC.2.

**Comment by arouinfar** [comment]
The separators are looking good in master. There are four instances of `separator*.visibleProperty` that should be phetioFeatured.

I also took a look at the sliders, and nothing seems to have been disturbed (including phetioFeatured).

**Comment by samreid** [comment]
I featured the separators visibleProperties in the commit.

**Comment by samreid** [comment]
Tagging for testing as part of https://github.com/phetsims/QA/issues/623

**Comment by KatieWoe** [comment]
Looks good in rc.3
