### ISSUE TITLE
Cherry pick "pin phetioEngine to the top" commits to the release branch

### ISSUE THREAD

**Issue by samreid** [phetsims/gravity-and-orbits#385]
From https://github.com/phetsims/studio/issues/210, we would like to cherry pick the commits that put phetioEngine at the top of the studio list.

The commit is https://github.com/phetsims/studio/commit/da2f18be1ecf6ecdd21e179c9405d154716b8670

**Comment by samreid** [comment]
I cherry picked it and updated the SHAs.  This should be verified in next RC.

**Comment by KatieWoe** [comment]
This looks good in rc.4
