### ISSUE TITLE
Pointer areas of time control buttons overlap

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-and-orbits#388]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/657. Seen in published sim. Very minor and probably does not need to be addressed.
The play button's pointer area overlaps slightly with the pointer area of the step forward button to it's right. They both have larger touch areas, while the step back button on the right does not, so it is not impacted. This is so small that you may need to zoom in to see it. May be more noticeable on other platforms however.

**Visuals**
<img width="806" alt="zoominpointerareas" src="https://user-images.githubusercontent.com/41024075/122979426-c4f47200-d354-11eb-8089-4e0e4946c051.png">

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Gravity and Orbits‬
URL: https://phet-dev.colorado.edu/html/gravity-and-orbits/1.5.0-rc.1/phet/gravity-and-orbits_all_phet.html
Version: 1.5.0-rc.1 2021-06-21 17:57:44 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
Language: en-US
Window: 1280x657
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by samreid** [comment]
Not planning to include fixes for this in the 1.5 branch, unassigning until we start work on the 1.6 codebase.

**Comment by samreid** [comment]
Fixed, it was straightforward and easy to verify so I do not think it needs a separate review step.  Closing.
