### ISSUE TITLE
Cannot drag velocity vector to zero

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-and-orbits#389]
**Test device**
Dell/Mac
**Operating System**
Win 10/MacOS 11.4
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/657. Seen in published
It seems there is a minimum velocity vector size (non-zero) that a user can drag the vector to. If the user wanted to make velocity zero they would not be able to. This is easiest to see with an object that start with a zero velocity vector.

**Steps to reproduce**
1. Go to the second screen
2. Go to the planet-satellite scene
3. Turn on velocity vectors
4. Drag the zero vector on Earth
5. Try to return the vector to zero

**Visuals**
![cantdragzero](https://user-images.githubusercontent.com/41024075/122986964-4ea83d80-d35d-11eb-9661-4d7cf229095d.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Gravity and Orbits‬
URL: https://phet-dev.colorado.edu/html/gravity-and-orbits/1.5.0-rc.1/phet/gravity-and-orbits_all_phet.html
Version: 1.5.0-rc.1 2021-06-21 17:57:44 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
Language: en-US
Window: 1280x657
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by samreid** [comment]
@arouinfar would you like to add some kind of snapping functionality?

**Comment by arouinfar** [comment]
Nice catch @KatieWoe. Users might find it annoying that they cannot zero out the velocity without resetting the scene. @samreid can you snap the velocity to zero if its size goes below the current minimum?

**Comment by samreid** [comment]
Proposed fix is in the commit, @arouinfar and/or @KatieWoe can you please test in master in a few scenes in a few zoom levels?

**Comment by arouinfar** [comment]
Thanks @samreid! Looks good in master across a variety of scenes and zoom levels.

**Comment by KatieWoe** [comment]
Very minor thing, but may be worth noting @arouinfar, some of the items start with very small, but non-zero, velocities that will then jump to zero. I do think this is better though.
![smallnonzero](https://user-images.githubusercontent.com/41024075/123686624-388ef700-d80d-11eb-91ec-24fff5d601bf.gif)

**Comment by samreid** [comment]
Another option would be to get rid of all thresholds and snapping altogether.  Then the user can set near-zero velocities.  (May be difficult to get exactly 0 though).

**Comment by arouinfar** [comment]
I prefer the current behavior. I find it more useful to set the velocity to precisely zero. If the user wants to return to the default tiny velocities, they are better off resetting the scene.

**Comment by samreid** [comment]
I added a cherry-pick commit to the release branch, ready for testing in next RC.

**Comment by samreid** [comment]
This can be tested by dragging a velocity vector through zero and seeing if it snaps.
