### ISSUE TITLE
All instances of velocityVectorNode.inputEnabledProperty should be phetioReadOnly: false

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gravity-and-orbits#395]
For https://github.com/phetsims/QA/issues/657

@KatieWoe asked me on Slack:
> should the velocity vectors also be able to be made non-interactive? I found `gravityAndOrbits.modelScreen.view.playAreaNode.planetMoonSceneView.moonNode.velocityVectorNode.inputEnabledProperty` but you can't seem to make a change

Over in #318 `velocityVectorNode.pickableProperty` were made phetioReadOnly: true, and then reverted back to false (the original request was an error on my part). Perhaps conversion over to inputEnabledProperty accidentally made these read-only again? I couldn't find an issue related to the conversion, though.

@samreid please make all instances of `velocityVectorNode.inputEnabledProperty` phetioReadOnly: false.

**Comment by KatieWoe** [comment]
For additional context, I thought of this in the context of the client request to make objects unmovable. You can do that, but you can still alter that object path through it's velocity.

**Comment by samreid** [comment]
I removed the override in VelocityVectorNode that was setting the inputEnabledProperty to phetioReadOnly: true.  @arouinfar can you please review?

**Comment by arouinfar** [comment]
> I removed the override in VelocityVectorNode that was setting the inputEnabledProperty to phetioReadOnly: true.

🤦🏻‍♀️ Not sure how that ended up in the phetioFeatured overrides, but thanks for fixing it @samreid. 

I seem to recall the circled v at the tip of the vector disappearing when it's no longer interactive. Perhaps it was around during the days of `pickableProperty`? I tried to find an old dev version to confirm, but I didn't have any success finding a version where the `velocityVectorNode.pickableProperty` was phetioReadOnly: false. @samreid can you hide the circled v when `velocityVectorNode.inputEnabledProperty` is false?

**Comment by samreid** [comment]
I made it so when inputEnabledProperty false hides the velocity vector circled v.  Can you please test?  Unassign and mark as ready-for-cherry-pick if all is well.

**Comment by arouinfar** [comment]
Looks great, thanks @samreid!

**Comment by samreid** [comment]
I cherry picked all commits for this issue, ready for spot check then QA check in next RC.

**Comment by samreid** [comment]
This can be verified by checking that `velocityVectorNode.inputEnabledProperty` are `phetioReadOnly: false` and that setting inputEnabledProperty to false hides the velocity vector circled v.

**Comment by phet-steele** [comment]
This looks great to me on Win 10 Chrome!
