### ISSUE TITLE
Freeze on ChromeOS when leaving preview HTML

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/gravity-and-orbits#396]
### Test Device

Chromebook

### Operating System

Chrome OS 81.0.4044.141

### Problem Description

For https://github.com/phetsims/QA/issues/657

Studio freezes on ChromeOS when returning from Preview HTML

### Visuals

https://user-images.githubusercontent.com/54685448/123179998-afac4000-d447-11eb-9e6c-d6162109c802.MOV

**Comment by KatieWoe** [comment]
I tried to reproduce this on Win 10 Chrome and on my Chromebook. @loganbraywork can you do a few things? First can you reproduce this while looking at the console and see if any errors show up? Second, can you check for updates on the device, my Chromebook is around version 90. If it can be updated, please do so and see if you can reproduce this after that.

**Comment by loganbraywork** [comment]
So no errors appeared in the console when I attempted to reproduce on the older version, although the issue still appeared, but when I updated it the issue seems to have resolves itself

**Comment by KatieWoe** [comment]
Even though this seems fixed by updating the device I'm assigning @pixelzoom as well in case this is important for https://github.com/phetsims/QA/issues/662

**Comment by samreid** [comment]
Good discovery, and it is good to know the problem resolved when updating the device.  Let's reopen if we see this problem again, or can easily reproduce it on another platform.
