### ISSUE TITLE
Update credits

### ISSUE THREAD

**Issue by samreid** [phetsims/gravity-and-orbits#399]
Hi @KatieWoe are there any changes to the credits for this release?

**Comment by KatieWoe** [comment]
Add Liam Mulhall and Emily Miller

**Comment by samreid** [comment]
I added them, ready for cherry picking.

**Comment by samreid** [comment]
I made a cherry-pick commit to the 1.5 branch, ready for testing when RC.2 is ready.

**Comment by samreid** [comment]
This can be confirmed by checking that Liam and Emily appear in the about dialog credits.
