### ISSUE TITLE
Cherry pick smooth playbacks

### ISSUE THREAD

**Issue by samreid** [phetsims/gravity-and-orbits#404]
Playback wrapper has been smoothed out in https://github.com/phetsims/natural-selection/issues/297#issuecomment-877844269 and should be cherry-picked.

**Comment by samreid** [comment]
Cherry picked and ready for testing in RC.2

**Comment by samreid** [comment]
This can be tested by making a recording and playing it back, to see if there are lags, delays or other problems.

**Comment by stemilymill** [comment]
@samreid how picky should we be? The playback is much much smoother than before, but it still took about 15 seconds to get from 0:01 to 0:02, then it sped forward to 0:28 when real time was 22 seconds. The rest of my 3-minute test recording played back very smoothly and with accurate timing (consistently six seconds ahead) until the last two seconds, which were slightly jerky.

**Comment by samreid** [comment]
Based on your description, it seems like it would not block publication.  But to understand better, I'll test with a longer recording to see if I can replicate that.  What platform were you on?

**Comment by stemilymill** [comment]
Win10 Chrome

**Comment by samreid** [comment]
Thanks, I recorded 2 minutes and 46 seconds on macOS/Chrome totaling a 45.8MB file, and did not see any delays or hiccups like you described.  How big is the file you described?  Can you file share it to me somehow?

**Comment by stemilymill** [comment]
I sent it on slack, hopefully that works

**Comment by samreid** [comment]
Thanks!  I got the file, and confirmed that I see the same laggy startup behavior in the first 6-7 seconds of sim playback on my mac/Chrome.  It seems to be related to the large file size, 244MB, and the parsing steps:

![image](https://user-images.githubusercontent.com/679486/125532599-e21ca22f-ec5f-4f2a-9f4d-afd6b97325c0.png)

**Comment by samreid** [comment]
I got sublime to format all 15 million lines of JSON here (took ~5 minutes), and it just looks like this sim has a very rich data stream.  We may want to balance this in the future, or add a mode where playbacks intended for visual playback omit non-input events, if we want to support that one day.

**Comment by samreid** [comment]
Thanks, I opened https://github.com/phetsims/phet-io-wrappers/issues/421 and recommend closing and checking off this issue.
