### ISSUE TITLE
Remove setting default option for enabledProperty of TimeControlNode StepForwardButton

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/gravity-and-orbits#410]
I think this line can be removed since it is setting the default behavior for TimeControlNode but didn't want to do so without checking with the responsible dev.

https://github.com/phetsims/gravity-and-orbits/blob/2db84ee3d9c5d6677a3c9bb0f6a6a3786926774b/js/common/view/GravityAndOrbitsTimeControlNode.ts#L59

**Comment by jessegreenberg** [comment]
I noticed this because in https://github.com/phetsims/scenery-phet/issues/563 we are replacing isPlayingProperty with enabledProperty so the result is changing the line to 
```
enabledProperty: DerivedProperty.not( model.isPlayingProperty ),
```

But I cannot commit to gravity-and-orbits because I am getting some "Could not find a declaration file for module..." errors. So sorry @samreid, can you look into making this change? The behavior of the TimeControlNode will be broken until fixed.

**Comment by jessegreenberg** [comment]
Actually...the point of this issue was that using this option may not be necessary in this sim, so the usage of TimeControlNode is probably not broken since I suspect using the default `enabledProperty` is OK.

**Comment by samreid** [comment]
It seemed to work OK without it, thanks!  Also, if you'd like to investigate "Could not find a declaration file for module..." more, please reach out to me on slack or create a new issue.  Closing.
