### ISSUE TITLE
Some iO Type links don't lead anywhere

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-and-orbits#414]
For https://github.com/phetsims/qa/issues/744. Seen in Win 11 Firefox.
When clicking links in the iO Type Doc section, when Selected is chosen, some of the links don't do anything. If All is chosen, then these links do seem to work. I saw this with `gravityAndOrbits.modelScreen.model.showPathProperty` element and the links that say 
```
StateSchema:
value: | BooleanIO
validValues: | NullableIO<ArrayIO<BooleanIO>>
units: | NullableIO<StringIO>
```

![linksdontlead](https://user-images.githubusercontent.com/41024075/143282990-74744ed1-0f19-42a3-a74e-429e78863ae6.gif)

**Comment by samreid** [comment]
Thanks, this looks related to https://github.com/phetsims/phet-io/issues/1781, I'll open a common code issue for it.

**Comment by samreid** [comment]
Fixed in https://github.com/phetsims/phet-io/issues/1781, closing.
