### ISSUE TITLE
Step forward button doesn't stay disabled when loaded into current studio version

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/gravity-and-orbits#420]
**Test device**
MacBook Air (m1 chip)

**Operating System**
macOS 12.4 

**Browser**
Safari

**Problem description**
For https://github.com/phetsims/qa/issues/816, I disabled the step forward button in the version 1.5 and then when I opened this saved state in the current version (1.6.0-dev.2) it was enabled. This happens in both screens. 

**Steps to reproduce**
1. In studio version 1.5, in the Model screen, set `gravityAndOrbits.modelScreen.view.timeControlNode.playPauseStepButtons.stepForwardButton.enabledProperty` to false.
2. Press the Save button
3. In the current studio version (1.6.0-dev.2), press the Load button and select that saved state

**Visuals**

https://user-images.githubusercontent.com/87318828/175437616-d5449c3c-b9de-4fdc-bcfe-50ecf2198729.mp4

**Comment by Nancy-Salpepi** [comment]
Or is this behavior correct because the ability to disable this control was deleted? 

<img width="498" alt="Screen Shot 2022-06-24 at 8 16 00 AM" src="https://user-images.githubusercontent.com/87318828/175532328-4e44854d-30cd-4be6-97d8-889321c9096a.png">

**Comment by zepumph** [comment]
>https://github.com/phetsims/gravity-and-orbits/issues/420#issuecomment-1165517211

Yes precisely! We unfortunately were not able to make this Property migrate, we had to delete it. This behavior is expected, as you see in the console. Closing
