### ISSUE TITLE
Launched sim performance severely affected in Safari

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/gravity-and-orbits#421]
**Test device**
MacBook Air (m1 chip) and iMac Desktop

**Operating System**
12.4 and 10.15.7

**Browser**
Safari

**Problem description**
For https://github.com/phetsims/qa/issues/816, when I launch the sim in studio, after checking a few checkboxes in the Model screen, the sim will basically come to a standstill and then sputter forward ~every second. 

* This will only happen the first time the sim is launched. The issue won't repeat itself unless I clear my history
*  Not seen with mac + chrome

**Steps to reproduce**
1. In studio, go to the Model screen
2. Press the Preview Sim button
3. In the launched sim, check the path and velocity checkboxes
4. Press Play button

**Visuals**

https://user-images.githubusercontent.com/87318828/175643407-ff21a8ef-1287-422f-b211-29e815977a25.mov

**Comment by samreid** [comment]
Please see notes in https://github.com/phetsims/friction/issues/278#issuecomment-1197329695 about a potential flaw in safari 15.3 through 15.5.  @Nancy-Salpepi can you please test this issue in 15.6?

**Comment by Nancy-Salpepi** [comment]
@samreid all looks good with Safari 15.6. I was unable to reproduce in 4 attempts.

**Comment by zepumph** [comment]
Excellent! I'm going to close this, @samreid please reopen if there are any other thoughts. Thanks all!
