### ISSUE TITLE
Red line under phet-io menu in studio

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-and-orbits#422]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome and Firefox
**Problem description**
For https://github.com/phetsims/qa/issues/816. In studio, in or out of projector mode, there is a red line under the phet-io button. This line does not appear in the Simulation wrapper or when the sim is launched from Studio.

**Visuals**
<img width="960" alt="menuredline" src="https://user-images.githubusercontent.com/41024075/175995979-dfbd76db-6731-4fc7-b0fe-218abe7c4ad6.png">

**Comment by zepumph** [comment]
Thanks for the report. This was added in https://github.com/phetsims/joist/issues/802 as a way to communicate to PhET-iO clients when assertions are enabled. This is expected. Please update necessary QA documentation.
