### ISSUE TITLE
Pan Zoom link has a typo

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-and-orbits#425]
For https://github.com/phetsims/qa/issues/816. In the [PhET-iO Guide](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.6.0-dev.2/phet-io/doc/guides/phet-io-guide.html) the link to the false pan and zoom for stand alone says `&asupportsPanAndZoom=false` instead of `&supportsPanAndZoom=false` which means the parameter does not work.

**Comment by samreid** [comment]
Fixed in the commit, thanks!
