### ISSUE TITLE
Gravity and Velocity Arrows missing in Screenshot

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/gravity-and-orbits#426]
**Test device**
MacBook Air (m1 chip)

**Operating System**
macOS 12.4

**Browser**
Safari and chrome

**Problem description**
For https://github.com/phetsims/qa/issues/816

When I take a screenshot in the Screenshot Wrapper, the velocity and gravity arrows are missing. Also seen in master, but nothing came up in the console. 

**I tried version 1.5 and the screenshot was correct. 

**Steps to reproduce**
1. Go to either screen in the Screenshot Wrapper
2. Check Gravity Force and Velocity checkboxes
3. Press Take Screenshot button

**Visuals**
<img width="549" alt="Screen Shot 2022-06-30 at 5 03 23 PM" src="https://user-images.githubusercontent.com/87318828/176780374-ba591fc1-88d1-43f9-a994-75fa0e40ce84.png">

**Comment by zepumph** [comment]
Seems like a sim-specific issue

**Comment by Nancy-Salpepi** [comment]
I am also seeing this when I take a screenshot from the PhET menu in the standalone sim and the PhET brand sim.

**Comment by Nancy-Salpepi** [comment]
This issue is also seen with iOS 15.5 using both the screenshot wrapper and the screenshot tool in the PhET menu.

**Comment by samreid** [comment]
Good catch, it's fixed in the commit and ready for review in the upcoming RC.  We will also need to check that the fix doesn't negatively impact performance.

**Comment by samreid** [comment]
No performance problem were reported in the preceding dev tests. Closing.
