### ISSUE TITLE
Unknown API changes

### ISSUE THREAD

**Issue by zepumph** [phetsims/gravity-and-orbits#429]
I was about to just commit these under another commit that changed the API but I thought I'd make sure @samreid felt they were purposeful since GAO is in the publication process. Likely they are! Feel free to close.

**Comment by samreid** [comment]
Thanks, I saw those same changes when testing playwright in https://github.com/phetsims/chipper/issues/1273#issuecomment-1176764865, and they seemed reasonable to me.
