### ISSUE TITLE
Screen Name resets to original locale in Standard PhET-iO wrapper with Reset All

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/gravity-and-orbits#433]
**Test device**
MacBook Air (m1 chip)

**Operating System**
macOS 12.5.1

**Browser**
Safari 15.6.1

**Problem description**
For https://github.com/phetsims/qa/issues/830, when changing the locale in the Standard PhET-iO wrapper, pressing the Reset All button results in the screen name returning to the original local the sim was launched in. All other words remain in the current, chosen locale. 

**Steps to reproduce**
1. In Studio, go to the Model Screen
2. Change the locale in the Preferences menu to español
3. Press the Test button
4. In the Standard PhET-iO wrapper, change the locale in the Preferences menu to English
5. Press the Reset All button -- everything stays in English, except the screen name becomes Modelo

*if you then switch to the To Scale screen and press the Reset All button, that screen name will change to Spanish as well. 

**Visuals**

https://user-images.githubusercontent.com/87318828/186480977-6f390cee-a8b5-4444-955e-204e8c28386d.mp4

**Comment by samreid** [comment]
Great discovery, thanks @Nancy-Salpepi.  I believe the problem is that the state is restored when reset all is pressed, and the string values are now in the state.  I'll have to take a closer look.  Also notifying @zepumph in case he knows a solution.

**Comment by samreid** [comment]
@zepumph said:

> Yes, because of this line. The PhET-iO state has a localeProperty that, when restored, will change just for that screen. We need to be exclude locale-related items from that call.
https://github.com/phetsims/scenery-phet/blob/7310d354798d65e93c42a8327a25995b82c9879e/js/buttons/ResetAllButton.ts#L82

I tried:

```diff
Index: js/PhetioStateEngine.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/PhetioStateEngine.ts b/js/PhetioStateEngine.ts
--- a/js/PhetioStateEngine.ts	(revision 1daf8f2a7faee8de6b33a671339cacec5eb00a9d)
+++ b/js/PhetioStateEngine.ts	(date 1661362909620)
@@ -213,7 +213,10 @@
       const allPhetioIDs = _.keys( this.mostRecentSavedState );
       for ( let i = 0; i < allPhetioIDs.length; i++ ) {
         const phetioID = allPhetioIDs[ i ];
-        if ( phetioID.startsWith( phetioObject.tandem.phetioID ) ) {
+        if ( phetioID.startsWith( phetioObject.tandem.phetioID ) &&
+             !phetioID.includes( 'nameProperty' ) &&
+             !phetioID.includes( 'StringProperty' ) ) {
+
           stateToSet[ phetioID ] = this.mostRecentSavedState[ phetioID ];
         }
       }
```

And it appeared to correct the problem.  But the heuristics for detecting the localized properties are probably too general.  Do we have to introduce new PhetioObject metadata indicating whether a Property is locale related or not?  What's the best solution?

**Comment by zepumph** [comment]
What about firing the localeProperty listeners one more time after setting screen state?

**Comment by samreid** [comment]
I was suprised to see that this error is no longer happening because of the change in https://github.com/phetsims/axon/issues/409.  Avoiding that change like so reintroduces the problem:

```diff
Index: js/ReadOnlyProperty.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/ReadOnlyProperty.ts b/js/ReadOnlyProperty.ts
--- a/js/ReadOnlyProperty.ts	(revision c00fd248d2e8849fc5c78257dace29bbe39dd4f7)
+++ b/js/ReadOnlyProperty.ts	(date 1661387997117)
@@ -234,7 +234,7 @@
                                     // However, DerivedProperty should be able to update during PhET-iO state set
                                     && this.isSettable();
 
-    if ( !setManagedByPhetioState ) {
+    if ( true ) {
       this.unguardedSet( value );
     }
   }

```

I'm not sure why it works but I'm glad it does.  @zepumph can this issue be closed?

**Comment by zepumph** [comment]
I think that makes sense to me. I am ready to close
