### ISSUE TITLE
Unable to test version migration

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/gravity-and-orbits#434]
For https://github.com/phetsims/qa/issues/830 I keep getting this message after trying to load a saved state from version 1.5 into version 1.6

<img width="1253" alt="Screen Shot 2022-08-24 at 2 16 48 PM" src="https://user-images.githubusercontent.com/87318828/186494185-43ceb668-8289-4faa-9af1-021f7325a99e.png">

**Comment by zepumph** [comment]
Could you please pull on phettest and try to reproduce this there. I just improved the error messaging so it won't say "[Object]"

**Comment by Nancy-Salpepi** [comment]
@zepumph I can't try on Master at the moment because of a different issue. I tried a couple of different sims on PhetMarks and the screens are just black when I try to open studio. I'm getting:
<img width="514" alt="Screen Shot 2022-08-24 at 3 22 33 PM" src="https://user-images.githubusercontent.com/87318828/186505411-c587c755-4850-479c-8654-78bee840f905.png">

**Comment by samreid** [comment]
I removed `?locales=*` on my working copy test and tried to load a 1.5 wrapper and saw these errors:

<img width="910" alt="image" src="https://user-images.githubusercontent.com/679486/186515828-5f0becc4-d2a8-487e-a987-a1b2e299d4cd.png">

So it seems some tandems were moved into the preferences dialog and this needs to be updated.

**Comment by zepumph** [comment]
We need migration rules!

**Comment by samreid** [comment]
I got the 1.5 state to load into 1.6 via the commits.  Would be great if @zepumph can take a look, especially at the change in LinkedElementIO which was unusual but I couldn't figure out a better way.

**Comment by zepumph** [comment]
GAO migration rules are now passing on master. @Nancy-Salpepi can you please test studio on master against 1.5 to ensure migration is supported now?

**Comment by Nancy-Salpepi** [comment]
@zepumph I was only able to load wrapper version 1.5 into 1.6 after removing the query parameter "keyboardLocaleSwitcher" from the url. Without removing, I am getting this message:
<img width="467" alt="Screen Shot 2022-08-31 at 10 03 20 AM" src="https://user-images.githubusercontent.com/87318828/187700045-a170a993-4289-47be-9b45-5af4aa0f0bb8.png">

which causes the load to be rejected

<img width="493" alt="Screen Shot 2022-08-31 at 10 04 33 AM" src="https://user-images.githubusercontent.com/87318828/187700539-e4ca5a03-56f2-4215-a0a5-f250cadd747f.png">

**Comment by zepumph** [comment]
Gotcha. Yes, that is expected behavior. We want to make sure that query parameters match between version to ensure that APIs are identical when migrating. I think this issue is ready to close. Thanks.
