### ISSUE TITLE
Query parameter for locale does not work in studio

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-and-orbits#436]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/830
When trying to load studio with the `?locale=es` parameter, an error pop-up appears, the console shows the same error, and studio does not load. The screens parameter seems to work as expected, so I believe this is connected to locale specifically.

**Visuals**
![localestudio](https://user-images.githubusercontent.com/41024075/187752750-4c9df774-fe2a-4cb4-a4df-5bf0a0d23b63.gif)

**Comment by zepumph** [comment]
My notes are in https://github.com/phetsims/scenery/issues/1124. This is the first time that we have a consistent hit on this assertion. I don't want to just remove the assertion and drop the data stream event without some discussion over in https://github.com/phetsims/scenery/issues/1124, though likely that is how we will unblock this.

**Comment by samreid** [comment]
I added this to the project board and will self-unassign until we discuss https://github.com/phetsims/phet-io/issues/1875#issuecomment-1235819514

**Comment by zepumph** [comment]
https://github.com/phetsims/phet-io-wrappers/commit/463cf19d4dbd2fc79b32209097004517ae2ec870 is the fix here. We were hitting an assertion from over in https://github.com/phetsims/studio/issues/268 that I don't think should apply here. Instead we can just assert if the query parameter values differ. @KatieWoe can you please confirm fixes on master and feel free to close.

**Comment by zepumph** [comment]
Oops, still working on this. Hold on.

**Comment by zepumph** [comment]
https://github.com/phetsims/tandem/commit/db0956f2b7e2cd276d7d614dfef6fdc8df1ecbd7 should fix this. @KatieWoe can you please test and feel free to close.

**Comment by KatieWoe** [comment]
Looks fixed on master
