### ISSUE TITLE
Checkbox Text not discoverable in studio

### ISSUE THREAD

**Issue by samreid** [phetsims/gravity-and-orbits#437]
This may have broken when we started using VerticalCheckboxGroup

**Comment by samreid** [comment]
I fixed the radio buttons and checkboxes in the commit.  @pixelzoom I called them `labelNode`, does that match what you have been doing and/or sound reasonable?  Would you like to review the commit?

**Comment by pixelzoom** [comment]
I've been using the Node type as the suffix. That seeems to be what designers have typically requested.  So if the checkbox  labels are of type Text, I've been calling using tandem name `labelText`. E.g. in `VisibilityCheckboxGroup`:

`        tandem: tandem.createTandem( 'labelText' ),`

I should also note that there are surely exceptions to this in my code. And I don't know it's something that needs to be consistent throughout - a question for designers.

**Comment by pixelzoom** [comment]
Looks like I was fairly consistent in geometric-optic.  I used `labelText` for all but one control label.  And I fixed that one case, since geometric-optic has never been published.

**Comment by pixelzoom** [comment]
Looks like I was fairly consistent in geometric-optics.  I used `labelText` for all but one control label.  And I fixed that one case, since geometric-optic has never been published.

I used `titleText` for titles on things like panels and accordion boxes.

**Comment by samreid** [comment]
I'm seeing 29 occurrences of `createTandem( 'labelNode' )` across our sims, many (all?) of them in Text or RichText instances.  @kathy-phet or @arouinfar do we want to rename all of these to `labelText`?

**Comment by pixelzoom** [comment]
And to clarify for @kathy-phet and @arouinfar...  This is related to https://github.com/phetsims/tandem/issues/267 (Tandem name conventions are applied haphazardly), where we've decided that it's useful to have conventions for tandem names, for 2 reasons: 
(1) Instructional designers can tell the type of the element from its tandem name, and know what to expect for child elements.
(2) Fewer PhET-iO elements will need to manually reviewed/changed.  

For most elements, we use a tandem-name suffix that matches the type of the JavaScript/TypeScript class name.  For example, "limitedFoodCheckbox", "massAccordionBox", "raysRadioButtonGroup".  We have not been doing that consistently for elements that are `Text` and `RichText` nodes.

**Comment by pixelzoom** [comment]
natural-selection, geometric-optics, phet-scale, and fourier-making-waves are all consistent about using the "Text" suffix for tandem names related to Text and RichText nodes.

**Comment by pixelzoom** [comment]
+1 for renaming.

**Comment by zepumph** [comment]
We will suffix with `Text` over in https://github.com/phetsims/tandem/issues/267#issuecomment-1241116079. Keeping open to make sure usages in this sim are covered.

**Comment by zepumph** [comment]
All looks good here! https://github.com/phetsims/gravity-and-orbits/blob/d0420b63cf512da58eca1adefcff138dbd3f83b5/js/common/view/CheckboxPanel.ts#L67
