### ISSUE TITLE
Return Objects button needs a maxWidth

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gravity-and-orbits#439]
For #440 

@samreid the Return Objects button doesn't have a maxWidth, as revealed by editing the `returnObjectsStringProperty`.

<img width="806" alt="image" src="https://user-images.githubusercontent.com/8419308/191074043-48530700-cffc-422b-b321-388240d02500.png">.

This problem exists in the latest published version of the sim, but `stringTest=long` isn't long enough to reveal the layout issues, so it's flown under the radar for a while now.

**Comment by samreid** [comment]
Fixed and ready for review, thanks.

**Comment by arouinfar** [comment]
@samreid this looks fixed in master, but I'm not seeing the change in rc.1. Seems like something that will need cherry-picking.
<img width="797" alt="image" src="https://user-images.githubusercontent.com/8419308/193109423-aacd8dea-8660-4525-9a86-5ea7f7b375a1.png">

**Comment by samreid** [comment]
Needed for https://github.com/phetsims/qa/issues/841

**Comment by Nancy-Salpepi** [comment]
Return objects button has a max width in RC.3
<img width="369" alt="Screen Shot 2022-10-06 at 1 38 28 PM" src="https://user-images.githubusercontent.com/87318828/194381567-98c6810a-c75d-4155-a5d0-1eb9cf53c848.png">



Closing
