### ISSUE TITLE
`deviatedFromDefaultsProperty` should be read-only

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gravity-and-orbits#442]
For #440 

Looks like `deviatedFromDefaultsProperty` was instrumented for #343. The documentation indicates that it is for internal use, so it should probably be `phetioReadOnly: true`.

**Comment by samreid** [comment]
Fixed, can you please spot check on phettest?

**Comment by arouinfar** [comment]
Thanks @samreid, looks good.
