### ISSUE TITLE
`controlPanel.visibleProperty` and `massesControlPanel.visibleProperty` should not be read-only

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gravity-and-orbits#443]
For #440 

In master, `controlPanel.visibleProperty` and `massesControlPanel.visibleProperty` are `phetioReadOnly: true`, which is a deviation from the behavior in the lastest published version. @samreid can you switch these back to `phetioReadyOnly: false`?

**Comment by samreid** [comment]
Fixed, can you please spot check on phettest?

**Comment by arouinfar** [comment]
Thanks, looks good @samreid
