### ISSUE TITLE
`massesControlPanel` should resize dynamically

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gravity-and-orbits#444]
For #440 

The `massesControlPanel` does not resize dynamically when its contents are hidden. The `controlPanel` resizes, so this seems like an oversight.

<img width="276" alt="image" src="https://user-images.githubusercontent.com/8419308/191620294-3da50ae6-a06d-4aef-b9f3-89163f4cf9b2.png">

**Comment by samreid** [comment]
Fixed and ready for review.

**Comment by arouinfar** [comment]
Thanks @samreid. Looks good in master, but not in rc.1, so tagging for cherry-picking.

**Comment by samreid** [comment]
Needed for https://github.com/phetsims/qa/issues/841

**Comment by Nancy-Salpepi** [comment]
This looks good in RC.3! Closing.
