### ISSUE TITLE
Does `massProperty` need a range?

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gravity-and-orbits#445]
During #440 I noticed that `massProperty` doesn't have a range. I'm not sure if this will cause issues with the new data-entry functionality of Studio, so I'm wondering if we should impose a range. If we do need a `massProperty.rangeProperty`, is it reasonable to match the range to what is used for the sliders -- 0.5x-2.0x the default value?

**Comment by samreid** [comment]
Good catch.  This sim has a constraint that the Properties are "rewindable" for when you restore initial conditions. The rewindable nature is currently incompatible with NumberProperty, which is the part of the code that manages the range.  Adding range behavior to a new subtype of RewindableProperty seems prohibitively expensive. The behavior in studio is that you can enter any number, and the slider will just go to the extremum if out of range.  Negative mass does crash the sim.

**Comment by arouinfar** [comment]
Thanks for the explanation @samreid. Negative masses do not seem reasonable, so I think we can continue without a range.
