### ISSUE TITLE
Outline appears around scenes

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/gravity-and-orbits#446]
**Test device**
MacBook Air (m1 chip)

**Operating System**
macOS 12.6

**Browser**
Safari 16.0

**Problem description**
For https://github.com/phetsims/qa/issues/838, when I hover the mouse over different scenes an outline appears. This issue is related to https://github.com/phetsims/sun/issues/772 and has been addressed by @jbphet on master. Assigning this issue to him as well, so that he can link the commit. 

**Visuals**

<img width="283" alt="Screen Shot 2022-09-27 at 3 10 51 PM" src="https://user-images.githubusercontent.com/87318828/192776976-fe2f955c-deb8-4e5d-9761-357a50f6345f.png">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Gravity and Orbits‬
URL: https://phet-dev.colorado.edu/html/gravity-and-orbits/1.6.0-rc.1/phet/gravity-and-orbits_all_phet.html
Version: 1.6.0-rc.1 2022-09-27 17:23:51 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Language: en-US
Window: 1815x925
Pixel Ratio: 1.3333333730697632/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by jbphet** [comment]
This is fixed in master, and there are two commits that should both be picked up to resolve it in a release branch.  They are:

- https://github.com/phetsims/sun/commit/3733859aa8261342e8530d66c063e35373614f74
- https://github.com/phetsims/sun/commit/43e6e01e5cc3054579a4d3871c356acfc46ebd6c

I'm going to discuss some of these changes with another dev tomorrow, and I'll amend this if anything changes, so I'll leave the issue assigned to myself for now.

**Comment by jbphet** [comment]
The changes are finalized.  I've added some documentation but didn't change the functionality any further, so the two commits listed above should do the trick.  Assigning to @samreid, since I believe he is working on the release of this sim.

**Comment by arouinfar** [comment]
Thanks @jbphet looks good in master.

**Comment by Nancy-Salpepi** [comment]
Looks good on master and in 1.6.0-rc.3! Closing.
