### ISSUE TITLE
Flickering Mass images

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-and-orbits#449]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome (Have not yet seen on Firefox)
**Problem description**
For https://github.com/phetsims/qa/issues/838. Also seen in published, but I do not believe I have encountered this in the past, so it may be related to some recent update.
The images of the sun, planet, moon, and satellite, next to the mass sliders may flicker in and out of visibility in the base sim. I have even seen this happen when first loading the sim and entering a page. The flickering seems to happen most consistently when moving the associated mass slider. It does not always happen and seems to happen most often when the sim has first loaded.
**Steps to reproduce**
1. Refresh the page (seems to happen most consistently on a fresh load)
2. Go to the first screen
3. Try the sun mass slider
4. If this does not work, go to the Earth Moon scene and try the Earth mass slider (this seems fairly consistent for me)

**Visuals**
<img width="960" alt="imagesdisappear" src="https://user-images.githubusercontent.com/41024075/192841699-9523532f-329d-422a-b465-0027959701e1.png">

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Gravity and Orbits‬
URL: https://phet-dev.colorado.edu/html/gravity-and-orbits/1.6.0-rc.1/phet/gravity-and-orbits_all_phet.html
Version: 1.6.0-rc.1 2022-09-27 17:23:51 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
I was able to see this on a Mac device after updating Chrome, but not before, so I think it is safe to think this has to do with a recent Chrome update, possibly within the last day or so.

**Comment by jonathanolson** [comment]
Reproducing this in chrome 105 on macOS.

**Comment by jonathanolson** [comment]
<img width="180" alt="image" src="https://user-images.githubusercontent.com/480878/192847848-cbef9c61-d224-4206-97ec-7070406a1a65.png">

Can also get partial images

**Comment by Nancy-Salpepi** [comment]
I was also able to reproduce with mac + chrome 106 but haven't seen it on safari yet. When I switch to the planet/moon scene, the planet is missing initially but reappears once I move the slider. 
I also got flickering to occur while moving the slider.

https://user-images.githubusercontent.com/87318828/192849518-0b9b1618-eb66-4576-aa22-1522eccc1b5e.mp4

**Comment by Nancy-Salpepi** [comment]
After refreshing studio and switching to the planet/moon scene, moving Earth (instead of the slider) also produces the flickering.

**Comment by arouinfar** [comment]
> When I switch to the planet/moon scene, the planet is missing initially but reappears once I move the slider.

This happened to me once in Mac/Chrome 106, but I otherwise haven't been able to reproduce this issue.

@samreid since this seems to be a Chrome issue, we can probably close as wontfix.

**Comment by Nancy-Salpepi** [comment]
@arouinfar to clarify--it is a chrome issue in general, not just on the mac. It was originally reported with Win11 + chrome.

**Comment by samreid** [comment]
@zepumph and I met with @jonathanolson and we considered this is probably a browser-specific bug.  We may need to work around it via something like `renderer: 'canvas'`.  But we would want to make sure to only do that for the icons and not for the bodies in the play area.

**Comment by samreid** [comment]
In the next round of QA, please make sure this change didn't introduce a performance degradation.

**Comment by KatieWoe** [comment]
The flashing seems fixed in RC 3. Leaving open to test performance.

**Comment by KatieWoe** [comment]
I haven't seen any new performance problems. Closing
