### ISSUE TITLE
PhET-iO Guide contains unneeded curly bracket

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-and-orbits#450]
For https://github.com/phetsims/qa/issues/838.
There is an extra curly bracket, `{` at the end of the PhET-iO Guide. It is after PhET-iO API Documentation in the More Details for Developers section.
<img width="352" alt="curlybracket" src="https://user-images.githubusercontent.com/41024075/192880321-2eeffa56-4dd8-49ed-90b8-4fb3b84183cc.png">

**Comment by arouinfar** [comment]
Thanks @KatieWoe. I can take care of fixing this, but I'd like to wait and see how many issues require editing the PhET-iO Guide so I can group everything into one commit. Related issues #451 #452.

**Comment by zepumph** [comment]
All fixed! ready for cherry pick.

**Comment by KatieWoe** [comment]
Fixed in RC3
