### ISSUE TITLE
Unable to hide screen icons as instructed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-and-orbits#451]
For https://github.com/phetsims/qa/issues/838, seen on Win 11 Chrome.
The element `gravityAndOrbits.general.model.screens.isUserNavigatableProperty` is given in the model as being able to hide screen icons in the nav bar. However, this element does not seem to exist. I suspect `gravityAndOrbits.general.model.screens.isUserNavigableProperty` should be the element instead.

**Comment by arouinfar** [comment]
Thanks @KatieWoe. I can take care of fixing this, but I'd like to wait and see how many issues require editing the PhET-iO Guide so I can group everything into one commit. Related issues #450 #452.

**Comment by zepumph** [comment]
@samreid and I are cruising through issues linked in the GAO rc, and fixed this guy. Ready for cherry pick.

**Comment by KatieWoe** [comment]
This is fixed in RC3
