### ISSUE TITLE
simName in curly brackets should be replaced with actual sim name

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-and-orbits#452]
For https://github.com/phetsims/qa/issues/838. Seen on Win 11 Chrome.
The element `gravityAndOrbits.general.model.strings.{{simName}}` is described in the PhET-iO Guide. The sim name is already included in the first part of this element, so I am unsure why it is not filled in at the end of the element.

**Comment by arouinfar** [comment]
Thanks @KatieWoe. I can take care of fixing this, but I'd like to wait and see how many issues require editing the PhET-iO Guide so I can group everything into one commit. Related issues #450 #451 .

**Comment by zepumph** [comment]
Fixed above!

**Comment by KatieWoe** [comment]
Looks good in RC3
