### ISSUE TITLE
Listed elements can cause studio to crash

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-and-orbits#453]
For https://github.com/phetsims/qa/issues/838.
The PhET-iO guide discusses the different preference elements and notes that not all are supported. However, they are in the tree, and trying to use them will cause a crash. Some of these elements may be listed specifically in the document, even though using them causes a crash and reload of studio. `gravityAndOrbits.general.view.audioManager.audioEnabledProperty` is an example for this sim.
![mentionsound](https://user-images.githubusercontent.com/41024075/192897513-2f8f20b4-de4a-4f64-8248-9b26622def1a.gif)

**Comment by zepumph** [comment]
Right! We should not crash if we don't support sound. Fixed above with @samreid and ready for cherry pick. We also changed manually all other preferences Properties and didn't encounter errors.

**Comment by KatieWoe** [comment]
This seems fixed in RC3
