### ISSUE TITLE
should projector mode be stateful?

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/gravity-and-orbits#458]
For https://github.com/phetsims/qa/issues/838, if I turn on projector mode in studio it will be on in the standard wrapper. I'm still not sure what in the preferences menu is stateful.

**Comment by samreid** [comment]
From slack:

<img width="687" alt="image" src="https://user-images.githubusercontent.com/679486/193880077-73f3f434-8d2f-4a49-95e4-7c92e2d63086.png">

<img width="697" alt="image" src="https://user-images.githubusercontent.com/679486/193880159-9e2c3e41-f6fa-48d0-9f30-194769438801.png">

**Comment by samreid** [comment]
Based on the conversation above, it seems like projector mode is supposed to be stateful, and it is stateful in the RC.  Therefore I think this issue can be closed.
