### ISSUE TITLE
Restart button stays disabled after pressing play in launched sim

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/gravity-and-orbits#460]
**Test device**
MacBook Air (m1 chip)

**Operating System**
macOS 12.6

**Browser**
Chrome and Safari

**Problem description**
For https://github.com/phetsims/qa/issues/838 and related to https://github.com/phetsims/gravity-and-orbits/issues/459:

In studio or state wrappers: After pressing the Reset button next to a scene, pressing play doesn't trigger the Restart button to become enabled. 

**Steps to reproduce**
Here is an example:
1. Go to the Studio wrapper, Model screen, Star/Planet scene 
2. Press Play and then Pause
3. Launch sim
4. Press the reset button next to Star/Plant scene
5. Press Play

**Visuals**

https://user-images.githubusercontent.com/87318828/193622918-e6a3654e-bbfc-4c6a-88f3-3aa43c7b4d1c.mp4

**Comment by samreid** [comment]
This was fixed by https://github.com/phetsims/gravity-and-orbits/issues/459, should be tested in RC.2.
