### ISSUE TITLE
Reset button returns measuring tape to default position

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/gravity-and-orbits#461]
**Test device**
MacBook Air (m1 chip)

**Operating System**
macOS 12.6

**Browser**
chrome and safari

**Problem description**
For https://github.com/phetsims/qa/issues/838 pressing the reset button in the standard wrapper returns the measuring tape to its default location, which is different behavior than in the Studio wrapper, upstream sim of the State wrapper, or the standalone sim. 

**Steps to reproduce**
1. In Studio, go to the To Scale screen
2. Launch the standard wrapper
3. Check the Measuring Tape checkbox and move the measuring tape
4. Press the Reset button next to the selected scene

**Visuals**

https://user-images.githubusercontent.com/87318828/193632258-e499bee8-7947-46c7-a953-92b0bedfcace.mp4

**Comment by Nancy-Salpepi** [comment]
The reset button also returns the zoom controls back to the default setting.

**Comment by samreid** [comment]
The standard wrapper "reset all" button is supposed to restore the PhET-iO saved state for that screen.  We decided for this sim that the "reset scene" button should restore the PhET-iO saved state for that scene.  The measuring tape is part of the scene data.  @arouinfar what do you recommend?

**Comment by samreid** [comment]
In discussion with @arouinfar and @marlitas, we observed that the measuring tape coordinates are part of the scene, and therefore it is OK to restore those coordinates when the scene is restored.  Therefore, we think this issue can be closed.
