### ISSUE TITLE
Update QA credits

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/gravity-and-orbits#464]
For https://github.com/phetsims/qa/issues/841, please add Clifford Hardin and Nancy Salpepi to QA Credits. Thanks!

**Comment by samreid** [comment]
Fixed and ready for cherry-picking.

**Comment by samreid** [comment]
Please close after verifying.

**Comment by samreid** [comment]
Tagging for https://github.com/phetsims/gravity-and-orbits/issues/464

**Comment by samreid** [comment]
Ready for testing in https://github.com/phetsims/qa/issues/857, please close if all is well.

**Comment by Nancy-Salpepi** [comment]
Jaron has been added to credits in  1.6.0-rc.6. Closing.
