### ISSUE TITLE
No audio tab to hide

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-and-orbits#465]
**Test device**
MacBook Pro
**Operating System**
MacOS 12.6
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/841
The guide contains this element: `gravityAndOrbits.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.preferencesDialog.preferencesTabs.audioTab.visibleProperty` but no such element is in the tree as there is no sound.

**Comment by samreid** [comment]
@zepumph and I fixed the documentation above, for cherry-picking we only need phet-io-sim-specific.
https://github.com/phetsims/phet-io-sim-specific/commit/59fb542016aded667261c8958912bfed8e5de81e

**Comment by samreid** [comment]
Please close after verifying.

**Comment by KatieWoe** [comment]
The changes in the linked commit are present. Closing
