### ISSUE TITLE
Use HSeparator instead of HSeparatorDeprecated

### ISSUE THREAD

**Issue by samreid** [phetsims/gravity-and-orbits#468]
So they will autocollapse, see https://github.com/phetsims/scenery/issues/1480

**Comment by samreid** [comment]
Fixed, and I observed that they correctly collapse in studio.

**Comment by samreid** [comment]
I also added migration rules so 1.5 will still load.  @arouinfar want to review this issue in studio?

**Comment by arouinfar** [comment]
@samreid the separators disappear as expected, so that's looking good. However, there are a few issues:

* The separators extend beyond the bounds of the control panel
   <img width="250" alt="image" src="https://user-images.githubusercontent.com/8419308/198159354-8cbabdf4-eff2-4541-ac22-9fc41f4267a9.png">

* Setting `sceneControl.visibleProperty` to false centers the remaining contents creating an odd indentation effect.
   <img width="250" alt="image" src="https://user-images.githubusercontent.com/8419308/198159440-b2a22fe0-e343-41f4-b097-f7c34e0acdb0.png">

**Comment by samreid** [comment]
> The separators extend beyond the bounds of the control panel

I fixed that in the commits.

> Setting sceneControl.visibleProperty to false centers the remaining contents creating an odd indentation effect.

This is controlled by the AlignBox in the outer panel.  When I change it like so:

<details>

```diff

Index: js/common/view/GravityAndOrbitsScreenView.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/GravityAndOrbitsScreenView.ts b/js/common/view/GravityAndOrbitsScreenView.ts
--- a/js/common/view/GravityAndOrbitsScreenView.ts	(revision ec65d67b845667482590271d9ef113387e746596)
+++ b/js/common/view/GravityAndOrbitsScreenView.ts	(date 1667859736948)
@@ -77,13 +77,17 @@
       right: this.layoutBounds.right - MARGIN,
       spacing: MARGIN,
       children: [
-        new Panel( alignGroup.createBox( controlPanel ), merge( {}, GravityAndOrbitsConstants.CONTROL_PANEL_OPTIONS, {
+        new Panel( alignGroup.createBox( controlPanel, {
+          xAlign: 'left'
+        } ), merge( {}, GravityAndOrbitsConstants.CONTROL_PANEL_OPTIONS, {
           tandem: controlPanelTandem,
           visiblePropertyOptions: {
             phetioReadOnly: false
           }
         } ) ),
-        new Panel( alignGroup.createBox( massesControlPanel ), merge( {}, GravityAndOrbitsConstants.CONTROL_PANEL_OPTIONS, {
+        new Panel( alignGroup.createBox( massesControlPanel, {
+          xAlign: 'left'
+        } ), merge( {}, GravityAndOrbitsConstants.CONTROL_PANEL_OPTIONS, {
           tandem: massesControlPanelTandem,
           visiblePropertyOptions: {
             phetioReadOnly: false

```

</details>

The HSeparator doesn't fill the width.

<img width="113" alt="image" src="https://user-images.githubusercontent.com/679486/200427973-5bbbe100-513d-4d0f-8003-ee27e0c9baaa.png">

@marlitas or @jonathanolson can you please comment how the `GravityAndOrbitsControls` can fill to fit its container bounds, while keeping its contents left-aligned?

**Comment by marlitas** [comment]
Did some initial research on this, and I would assume that passing a `stretch: true` to GravityAndOrbitsControl would solve the problem. However, even with `stretch: true` the VBox is calculating it's width to be about `65 px` less than the parent AlignBox's width.

This screenshot shows the behavior with scenery helper outlines. The red dash represents the AlignBox bounds.
<img width="307" alt="Screenshot 2022-11-07 at 6 00 04 PM" src="https://user-images.githubusercontent.com/42476338/200448333-72a8be23-0d50-455b-8a0a-d2c9ac1bd961.png">

I have a couple of hypotheses for what might be going on here:
- The AlignBox is constraining the VBox to a width that is inaccurate once it's width is updated by the AlignGroup
- The VBox is not calculating it's `line.size` appropriately and is not taking into consideration extra space it may have.

This seems like buggy behavior to me, and something that @jonathanolson and I should look into on scenery's end.

**Comment by jonathanolson** [comment]
AlignGroup doesn't currently set preferred sizes for anything, and this really isn't a good place to use AlignGroup. The AlignBox is just padding out the content. https://github.com/phetsims/scenery/issues/1493 exists to look into whether AlignGroup should be improved to do this type of thing.

Instead, just use the VBox itself and toss the AlignBoxes/AlignGroups for a simpler approach:

<details>

```diff
Index: js/common/view/GravityAndOrbitsScreenView.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/GravityAndOrbitsScreenView.ts b/js/common/view/GravityAndOrbitsScreenView.ts
--- a/js/common/view/GravityAndOrbitsScreenView.ts	(revision ec65d67b845667482590271d9ef113387e746596)
+++ b/js/common/view/GravityAndOrbitsScreenView.ts	(date 1667924635611)
@@ -9,10 +9,9 @@
 
 import Vector2 from '../../../../dot/js/Vector2.js';
 import ScreenView from '../../../../joist/js/ScreenView.js';
-import merge from '../../../../phet-core/js/merge.js';
 import ResetAllButton from '../../../../scenery-phet/js/buttons/ResetAllButton.js';
-import { AlignGroup, Node, VBox } from '../../../../scenery/js/imports.js';
-import Panel from '../../../../sun/js/Panel.js';
+import { Node, VBox } from '../../../../scenery/js/imports.js';
+import Panel, { PanelOptions } from '../../../../sun/js/Panel.js';
 import gravityAndOrbits from '../../gravityAndOrbits.js';
 import GravityAndOrbitsConstants from '../GravityAndOrbitsConstants.js';
 import GravityAndOrbitsControls from './GravityAndOrbitsControls.js';
@@ -20,6 +19,7 @@
 import MassControlPanel from './MassControlPanel.js';
 import GravityAndOrbitsModel from '../model/GravityAndOrbitsModel.js';
 import Tandem from '../../../../tandem/js/Tandem.js';
+import { combineOptions } from '../../../../phet-core/js/optionize.js';
 
 // constants
 const MARGIN = 5;
@@ -35,10 +35,6 @@
       tandem: tandem
     } );
 
-    const alignGroup = new AlignGroup( {
-      matchVertical: false
-    } );
-
     // Control panel in the upper right of the play area.
     const controlPanelTandem = tandem.createTandem( 'controlPanel' );
     const controlPanel = new GravityAndOrbitsControls( model, {
@@ -76,18 +72,21 @@
       top: this.layoutBounds.top + MARGIN,
       right: this.layoutBounds.right - MARGIN,
       spacing: MARGIN,
+      stretch: true,
       children: [
-        new Panel( alignGroup.createBox( controlPanel ), merge( {}, GravityAndOrbitsConstants.CONTROL_PANEL_OPTIONS, {
+        new Panel( controlPanel, combineOptions<PanelOptions>( {}, GravityAndOrbitsConstants.CONTROL_PANEL_OPTIONS, {
           tandem: controlPanelTandem,
           visiblePropertyOptions: {
             phetioReadOnly: false
-          }
+          },
+          align: 'left'
         } ) ),
-        new Panel( alignGroup.createBox( massesControlPanel ), merge( {}, GravityAndOrbitsConstants.CONTROL_PANEL_OPTIONS, {
+        new Panel( massesControlPanel, combineOptions<PanelOptions>( {}, GravityAndOrbitsConstants.CONTROL_PANEL_OPTIONS, {
           tandem: massesControlPanelTandem,
           visiblePropertyOptions: {
             phetioReadOnly: false
-          }
+          },
+          align: 'left'
         } ) )
       ]
     } ) );
```

</details>

<img width="173" alt="image" src="https://user-images.githubusercontent.com/480878/200620389-e7358474-66d5-4924-8b1e-81cdbcfc26ef.png">
