### ISSUE TITLE
Index.HTML does not work for Phet.io offline test

### ISSUE THREAD

**Issue by JaronDroder** [phetsims/gravity-and-orbits#474]
Test Device
Alien ware m15 r7

Operating System
Windows 11

Browser
Version 106.0.5249.119

Problem Description

Seen in phetsims/qa/issues/850
For the offline test on the Phet.io, the index.html just goes to a white screen

### Steps to Reproduce

Download the phet.io zip file and open the index.html
### Visuals
![Screenshot (7)](https://user-images.githubusercontent.com/115029534/200972947-b2eb8c82-8c26-41bf-bf36-f793916c7fae.png)

**Comment by samreid** [comment]
Was the file decompressed?  From the url in the screenshot above, it seems the browser is pointed to the file still within the compressed zip?  After decompression on Mac/Chrome the index page launches the sim correctly on my platform.

**Comment by KatieWoe** [comment]
I checked this and I believe this is what happened. I think this can be closed. Thanks for the catch @samreid
