### ISSUE TITLE
Reset/Reset All doesn't interrupt grabbed object 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/gravity-and-orbits#478]
**Test device**
iPad 9th generation

**Operating System**
iPadOS 16

**Browser**
safari

**Problem description**
For https://github.com/phetsims/qa/issues/850. If I press Reset or Reset All with one finger, while I still have a planet/sun/moon grabbed with another, the planet/sun/moon will return to its current position after reset instead of the default. 

This also occurs with the published version. 

**Steps to reproduce**
1. On either screen, with any scene, move an object with one finger and hold it there.
2. With another finger, press the Reset or Reset all button.
3. Lift your finger that held the object.

**Visuals**

https://user-images.githubusercontent.com/87318828/201692382-372e3699-dcac-47b1-a11b-4cc5cb538790.mov

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Gravity and Orbits‬
URL: https://phet-dev.colorado.edu/html/gravity-and-orbits/1.6.0-rc.3/phet/gravity-and-orbits_all_phet.html
Version: 1.6.0-rc.3 2022-10-06 04:17:15 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Language: en-US
Window: 2068x1047
Pixel Ratio: 1.3333333730697632/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by samreid** [comment]
Ready for testing in https://github.com/phetsims/qa/issues/857, please close if all is well.

**Comment by Nancy-Salpepi** [comment]
Looks good in 1.6.0-rc.6. Closing.
