### ISSUE TITLE
Maintenance release GAO 1.6 for changes from ph-scale 1.6 RC testing 

### ISSUE THREAD

**Issue by zepumph** [phetsims/gravity-and-orbits#481]
We want to a maintenance release for GAO 1.6 to make sure we  have a consistent PhET-iO product. Here is what @samreid and I recommend:

* In https://github.com/phetsims/phet-io-wrappers/issues/483 we will make sure that it works as an "old version" of the version migration wrapper.
* ~For a more full migration support, we need the "ConvertToStringsStateForLocale" rule in https://github.com/phetsims/joist/issues/899.~ This would be too hard, and not enough gain.
* We want LinkedElements to be stateful, from https://github.com/phetsims/phet-io/issues/1903.

**Comment by samreid** [comment]
It doesn't feel important to do this eagerly (wouldn't save much time or increase product value in the long run).  I'll demote priority for now, but others feel free to disagree.
