### ISSUE TITLE
Performance drops when the "velocity" arrow + text goes offscreen on iPad3

### ISSUE THREAD

**Issue by samreid** [phetsims/gravity-and-orbits#81]
Performance drops when the "velocity" arrow + text goes offscreen.

To reproduce the problem:
1. Get out your iPad3 (or perhaps other versions of iPad)
2. launch:
http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.0.0-dev.12/gravity-and-orbits_en.html
3. Choose "cartoon" scene.
4. Turn on "velocity" vectors
5. Press play.

Notice the motion becomes choppy when the vector tip goes off the top of the screen, and smooth again when it comes back onscreen.

**Comment by aaronsamuel137** [comment]
Pre-rewrite issue, so very likely doesn't apply anymore. Closing
