### ISSUE TITLE
Making the Cartoon scene more cartoon like

### ISSUE THREAD

**Issue by phet-steele** [phetsims/gravity-and-orbits#83]
Trish and I thought that it might be best to either change the name of the "Cartoon" scene to something that better states that's it's not to scale, or to make the images in that scene more cartoon like and less realistic. We thought it might be somewhat confusing to show the Earth and Moon orbiting so close to each other when it wasn't actually what happens. Maybe make it just a colored ball? Is this something worth looking into? I know for some people the word "Cartoon" is sufficient for stating the non realism of the scene.

**Comment by ariel-phet** [comment]
@arouinfar thoughts on this? I would be fine changing the name, but I am not sure we want to bother with artwork.

**Comment by arouinfar** [comment]
@ariel-phet, I would rather not change the artwork, but I think we can come up with a different name. I'll starting thinking of possible alternatives.

**Comment by arouinfar** [comment]
@ariel-phet how about we change Cartoon to Model? I think "Model" conveys that things aren't to scale, especially since the other screen is "To Scale".

**Comment by ariel-phet** [comment]
Ah...I think that is a perfect name, especially since NGSS and such mentioning thinking about models, and we use that naming convention in Molecule shapes.

**Comment by ariel-phet** [comment]
@aaronsamuel137 please change this name

**Comment by aaronsamuel137** [comment]
Forgot about this issue until just now. I've changed the name (on master). Assigning to @arouinfar for review.

**Comment by arouinfar** [comment]
Thanks @aaronsamuel137! Looks good, closing.
