### ISSUE TITLE
Small arrow behavior should match the original.

### ISSUE THREAD

**Issue by samreid** [phetsims/gravity-and-orbits#89]
In the original Java version, the smallest an velocity arrow can be shown is like so:

![arrow](https://f.cloud.github.com/assets/679486/2514381/77557cbc-b438-11e3-91b3-e0b4d017bea1.png)

In the latest HTML5 version, the arrows can get much smaller, and are much wider than the Java version:

![arrow2](https://f.cloud.github.com/assets/679486/2514405/a500a89e-b438-11e3-9754-24585c6d3543.png)

Can the HTML5 version be made to match the Java version in this respect?  We show near-zero velocities as larger than zero so it is always possible to see the direction of motion in this sim, even for a slowly moving object.  I noticed this issue while I was investigating #87

**Comment by aaronsamuel137** [comment]
ArrowNode takes care of this now. Closing
